### ISSUE TITLE
How to confine the bot in a certain area

### ISSUE THREAD

**Issue by kenkclam** [PokemonGoF/PokemonGo-Bot#3926] opened 2016-08-14 13:46 UTC
### Expected Behaviour
I would like to confine movement of the bot in a park near my house.
I can find the coordinates of the boundaries of the park. 
I would like to have randomised walking pattern within the park. (like MoveToFort walking pattern)

### Actual Behaviour
If I use MoveToFort + FollowSpiral, the bot goes straight out of the park and goes very far away after some time. 
If I use FollowPath and loop, without MoveToFort, there is no randomised factor, and it does not look like human walking at all. (With MoveToFort, the bot just completely ignores my paths)

### Your config.json (remove your credentials and any other private info)
{
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_start_mode": "first",
          "path_file": "configs/path.json"
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 10
    },

### Steps to Reproduce
Tried playing with diameter, step size, max circle size, max lure distance etc, all without success.
Any suggestions?

Are there ways to mask the pokestop outside the park so that the bot does not see them?

### Other Information
OS: Mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by k4n30** [comment] 2016-08-14 14:13
Duplicate of #3580

**Closed by k4n30** 2016-08-14 14:13 UTC
Labels: duplicate
