### ISSUE TITLE
Enabling lucky egg yields api_error

### ISSUE THREAD

**Issue by JonesN7** [PokemonGoF/PokemonGo-Bot#3329] opened 2016-08-09 17:35 UTC
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Enabling lucky egg, should start the bot normally, and pop a lucky egg for evolves

### Actual Behavior
Bot starts, logs in, then yeilds 
`[INFO] [api_error] Server is throttling, reconnecting in 30 seconds`

### Steps to Reproduce
Set "use_lucky_egg": true, and start a bot.

### Other Information
OS: Linux
Git Commit: c8aaf4b82ca2733897a1a32dac203e23ca605a8d 
Python Version:  Python 2.7.12

**Comment by TD-Stanley** [comment] 2016-08-09 17:37
Set it to false until the current one expires, then set it back to true. Happens if you restart while one is currently activated.

**Comment by k4n30** [comment] 2016-08-16 04:35
Duplicate of #3253

**Closed by k4n30** 2016-08-16 04:35 UTC
Labels: Duplicate
