### ISSUE TITLE
 It does not work evolve?

### ISSUE THREAD

**Issue by StarForser** [PokemonGoF/PokemonGo-Bot#1221] opened 2016-07-27 16:23 UTC
"evolve_all": "Pidgey,Weedle,Rattata",
    "evolve_speed": 20,
    "cp_min": 80,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
    },
    "release": {
      "any": {"release_below_cp": 250, "release_below_iv": 0, "logic": "or"},
	  "Weedle": {"always_release": false},
	  "Pidgey": { "always_release" : false },
	  "Rattata": { "always_release" : false }
    }
}

All evolve is not working? How to configure it?

**Comment by DavidTai1** [comment] 2016-07-27 16:32
#1151

**Comment by TheGoldenXY** [comment] 2016-07-27 17:31
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1151

/closed

**Closed by TheGoldenXY** 2016-07-27 17:31 UTC
Labels: duplicate
