### ISSUE TITLE
Login process failed: Invalid JSON And location error

### ISSUE THREAD

**Issue by peterkristel** [PokemonGoF/PokemonGo-Bot#5970] opened 2017-03-19 15:36 UTC
[2017-03-19 16:36:34] [PokemonGoBot] [INFO] Login process failed: Invalid JSON response: No JSON object could be decoded
Sun 19 Mar 16:36:34 CET 2017 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
  2017-03-19 16:36:55,210 [       cli] [INFO] PokemonGO Bot v1.0
2017-03-19 16:36:55,214 [       cli] [INFO] commit: bd5d340a
2017-03-19 16:36:55,216 [       cli] [INFO] Configuration initialized
2017-03-19 16:36:55,216 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2017-03-19 16:36:55,216 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2017-03-19 16:36:55,222 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(27437) wsgi starting up on http://127.0.0.1:4000
[2017-03-19 16:36:55] [PokemonGoBot] [INFO] Setting start location.
[2017-03-19 16:36:55] [PokemonGoBot] [INFO] Location found: 9240 (36.6022443, -91.75687169999999, 0.0)
[2017-03-19 16:36:55] [PokemonGoBot] [INFO] Now at (36.6022443, -91.75687169999999, 0.0)
[2017-03-19 16:36:55] [PokemonGoBot] [INFO] Login procedure started.
[2017-03-19 16:36:55] [PokemonGoBot] [INFO] Login process failed: Could not retrieve token! 'location'
Sun 19 Mar 16:36:55 CET 2017 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

-----------------------------------------------------------------------------------------------------------------
  2017-03-19 16:36:34,180 [       cli] [INFO] PokemonGO Bot v1.0
2017-03-19 16:36:34,184 [       cli] [INFO] commit: bd5d340a
2017-03-19 16:36:34,187 [       cli] [INFO] Configuration initialized
2017-03-19 16:36:34,187 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2017-03-19 16:36:34,187 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2017-03-19 16:36:34,190 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(27339) wsgi starting up on http://127.0.0.1:4000
[2017-03-19 16:36:34] [PokemonGoBot] [INFO] Setting start location.
[2017-03-19 16:36:34] [PokemonGoBot] [INFO] Location found: 9240 (36.6022443, -91.75687169999999, 0.0)
[2017-03-19 16:36:34] [PokemonGoBot] [INFO] Now at (36.6022443, -91.75687169999999, 0.0)
[2017-03-19 16:36:34] [PokemonGoBot] [INFO] Login procedure started.
[2017-03-19 16:36:34] [pgoapi.auth] [ERROR] PTC User Login Error - invalid JSON response: No JSON object could be decoded
[2017-03-19 16:36:34] [PokemonGoBot] [INFO] Login process failed: Invalid JSON response: No JSON object could be decoded
Sun 19 Mar 16:36:34 CET 2017 Pokebot  Stopped.

**Comment by MerlionRock** [comment] 2017-03-20 08:02
It's either a API issue or PTC account issue. All bots/maps during PTC has the same problem .

**Comment by pogarek** [comment] 2017-03-27 08:49
Yes. I'm affected too. This is outside botitself. Pgoapi will need to be fixed after root cause will be found. Closing.

**Closed by pogarek** 2017-03-27 08:49 UTC

**Comment by MerlionRock** [comment] 2017-03-28 09:31
In case anyone is using the bot unattended like me, you can modify init.py with the following, after def login(self) at the line that says try: self.api.login(.... change the whole try: Except: codes to

```
while True:
            try:
                self.api.login(
                        self.config.auth_service,
                        str(self.config.username),
                        str(self.config.password))
                break
            except AuthException as e:
                self.event_manager.emit(
                        'login_failed',
                        sender=self,
                        level='info',
                        formatted='Login process failed (sleep 10 sec): {}'.format(e)
                        )
                sleep(10) 
```

This will pause the bot for 10sec and then try to login again.
