### ISSUE TITLE
crash: TypeError: __init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#1184] opened 2016-07-27 11:43 UTC
### Expected Behavior
launch normally

### Actual Behavior
```
-> # ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
  File "/root/PokemonGo-Bot-myprettyusername/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot-myprettyusername/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/root/PokemonGo-Bot-myprettyusername/src/pgoapi/pgoapi/rpc_api.py", line 42, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/root/PokemonGo-Bot-myprettyusername/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/root/PokemonGo-Bot-myprettyusername/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

### Steps to Reproduce
a fresh clone, with install script then switch on dev branch
the stranger is, i've done this two time and the second bot run normally
### Other Information
OS: Debian x86_64
Git Commit: 18f232bffb8df487654e6c52ff3eea859a120925

**Comment by Snorflake** [comment] 2016-07-27 11:58
duplicate of #915 have you updated submodules and installed requirements etc?

**Comment by mehdi-S** [comment] 2016-07-27 11:59
yep, run install.sh and edit config.json and userdata.js

**Comment by mehdi-S** [comment] 2016-07-27 12:23
This comment is duplicate from https://github.com/PokemonGoF/PokemonGo-Bot/issues/915

i've make it work by using a **_screen_** session
[more information about screen and how to use screen here (rackaid.com)](https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/)

but for the basics : 
`screen -S mysessionname` to create a new screen session
Do your business (including clone the repo ,setup it, and launch it) and use CTRL-A-D to exit the screen session
Now from here do the same with a different name for all the bot you want to launch
If you want to get back you your session, use `screen -r mysessionname` or `screen -r` with no argument to show up a list of your active session

**Comment by Sculay** [comment] 2016-07-27 12:38
receiving the same response, but then again my pip is not responding correctly.

isaac@0xlx0:~/PokemonGo-Bot$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
isaac@0xlx0:~/PokemonGo-Bot$ pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by TheGoldenXY** [comment] 2016-07-27 18:11
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/915

/closed

**Closed by TheGoldenXY** 2016-07-27 18:11 UTC
Labels: duplicate
