### ISSUE TITLE
not using UltraBalls if normal pokeballs count=0 

### ISSUE THREAD

**Issue by wcrwcr** [PokemonGoF/PokemonGo-Bot#2097] opened 2016-07-31 16:33 UTC
### Expected Behavior
use avail pokeballs

### Actual Behavior
[18:24:22]  Items: 387/350
...
[18:24:22]  PokeBalls: 0 | GreatBalls: 0 | UltraBalls: 86
...
[18:25:11]  A Wild Staryu appeared! [CP 103] [Potential 0.27]
[18:25:11] IV [Stamina/Attack/Defense] = [0/9/3]
[18:25:13] Using Pokeball (chance: 68.91%)... (-1 left!)

### Steps to Reproduce
have zero normal pokeballs, then max out items

### Other Information
OS: win7
Git Commit: 3fe8eb07c098c45c87db0d643d579ac4f7464cf6

**Comment by wcrwcr** [comment] 2016-07-31 16:36
probably duplicate of #2075

**Comment by xc-mezcal** [comment] 2016-07-31 18:08
Check this PR
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2113

If you set VIP pokemons in the config file, this indicates, you want to use better strategy to capture VIP pokemons, means you want to save Ultra Balls.

If you delete VIP pokemons section in config file, it will use whatever balls to catch them all.

**Comment by wcrwcr** [comment] 2016-07-31 18:36
sounds like really unobvious behaviour, should be defined in configs imo.

**Comment by xorinzor** [comment] 2016-08-01 18:15
Duplicate of #2075

Please check for existing issues first

**Closed** 2016-08-05 08:33 UTC
