### ISSUE TITLE
code 404, message File not found (socket.io)

### ISSUE THREAD

**Issue by lnedry** [PokemonGoF/PokemonGo-Bot#2499] opened 2016-08-03 16:02 UTC
### Expected Behavior
Web pages seem to display properly 

### Actual Behavior
From web server log:
```
code 404, message File not found
"GET /socket.io/?EIO=3&transport=polling&t=LPH8CN7 HTTP/1.1" 404 -
```

### Steps to Reproduce
Install and run latest dev
cd PokemonGo-Bot/web/
python -m SimpleHTTPServer 8000

### Other Information
OS: CentOS 7
Git Commit: 6ba5609c6151507b5b832a74e471b6b7b1a182c9
Python Version: Python 2.7.5

**Comment by JSchwerberg** [comment] 2016-08-03 16:07
Duplicate of #2403

**Closed** 2016-08-03 16:14 UTC
