### ISSUE TITLE
Got 'ascii' codec can't decode byte 0x9c on login

### ISSUE THREAD

**Issue by nguyennp** [PokemonGoF/PokemonGo-Bot#5796] opened 2016-11-09 07:36 UTC
When login I got this error.

[2016-11-09 14:34:26] [PokemonGoBot] [INFO] Login procedure started.
_inventory was not initialized
_inventory was not initialized
[2016-11-09 14:34:28] [       cli] [INFO]
[2016-11-09 14:34:28] [       cli] [INFO] Ran for 0:00:01
[2016-11-09 14:34:28] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-11-09 14:34:28] [       cli] [INFO] Travelled 0.00km
[2016-11-09 14:34:28] [       cli] [INFO] Visited 0 stops
[2016-11-09 14:34:28] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-11-09 14:34:28] [       cli] [INFO] Threw 0 pokeballs
[2016-11-09 14:34:28] [       cli] [INFO] Earned 0 Stardust
[2016-11-09 14:34:28] [       cli] [INFO] Hatched eggs 0
[2016-11-09 14:34:28] [       cli] [INFO]
[2016-11-09 14:34:28] [       cli] [INFO] Highest CP Pokemon:
[2016-11-09 14:34:28] [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/home/nguyennp/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/home/nguyennp/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1037, in _setup_api
    self.login()
  File "/home/nguyennp/PokemonGo-Bot/pokemongo_bot/__init__.py", line 944, in login
    str(self.config.password))
  File "/home/nguyennp/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 103, in login
    response = PGoApi.app_simulation_login(self)
  File "/home/nguyennp/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 169, in app_simulation_login
    response = request.call()
  File "/home/nguyennp/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 255, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/nguyennp/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 138, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/home/nguyennp/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 292, in _build_main_request
    sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
  File "/home/nguyennp/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 309, in _generate_signature
    output_size = self._signature_lib.encrypt(signature_plain, len(signature_plain), iv, ctypes.byref(output))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: encrypt
[2016-11-09 14:34:28] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/nguyennp/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-11-09 14:34:28] [sentry.errors.uncaught] [ERROR] [u'AttributeError: python: undefined symbol: encrypt', u'  File "pokecli.py", line 843, in <module>', u'  File "pokecli.py", line 191, in main', u'  File "pokecli.py", line 145, in start_bot', u'  File "pokemongo_bot/__init__.py", line 147, in start', u'  File "pokemongo_bot/__init__.py", line 1037, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 944, in login', u'  File "pokemongo_bot/api_wrapper.py", line 103, in login', u'  File "pgoapi/pgoapi.py", line 169, in app_simulation_login', u'  File "pgoapi/pgoapi.py", line 255, in call', u'  File "pgoapi/rpc_api.py", line 138, in request', u'  File "pgoapi/rpc_api.py", line 292, in _build_main_request', u'  File "pgoapi/rpc_api.py", line 309, in _generate_signature', u'  File "ctypes/__init__.py", line 378, in __getattr__', u'  File "ctypes/__init__.py", line 383, in __getitem__']
Wed Nov 9 14:34:28 ICT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by paganoll** [comment] 2016-11-09 08:45
Same here. Yesterday works nice.
With IP changed (reset router) 0xc9 error disappear but AttributeError yet
======
[2016-11-09 09:40:04] [MainThread] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 147, in start
    self._setup_api()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 1037, in _setup_api
    self.login()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 944, in login
    str(self.config.password))
  File "/root/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 103, in login
    response = PGoApi.app_simulation_login(self)
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 169, in app_simulation_login
    response = request.call()
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 255, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 138, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 292, in _build_main_request
    sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 309, in _generate_signature
    output_size = self._signature_lib.encrypt(signature_plain, len(signature_plain), iv, ctypes.byref(output))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: encrypt
=======

**Comment by MZorzy** [comment] 2016-11-09 08:49
AttributeError: python: undefined symbol: encrypt
due to https://github.com/pogodevorg/pgoapi/commit/e8a798433c4934b62b3cb0084bd14bce4c75e3b3
so need to add these  https://github.com/pokecrypt/pokecrypt-pgoapi

**Comment by paganoll** [comment] 2016-11-09 08:57
Yesterday working with arm-32 libs from here...
https://github.com/pogodevorg/pgoapi/pull/148/commits/219cadf16c077d3ce71b7e7ef2758fdb1a45a78b#diff-5745a86df5940e354add7eb35c45d26f
Compiling...
https://github.com/pokecrypt/pokecrypt-pgoapi/blob/master/howto_compile.txt

**Comment by houkop** [comment] 2016-11-09 18:11
in requirements.txt changed api to https://github.com/sebastienvercammen/pgoapi.git
now it works.

**Comment by tunayuyar** [comment] 2016-11-09 19:20
confirming it works after @houkop 's suggestion.

**Comment by Gobberwart** [comment] 2016-11-09 21:23
Confirmed workaround. I don't think this will be implemented here, as it's not an official release, but should be ok to use for now.

**Comment by boscorelly** [comment] 2016-11-09 21:24
Not working for me.  Update don't do anything.

**Comment by Gobberwart** [comment] 2016-11-09 21:39
@boscorelly What exactly does "don't do anything" mean. Possibly you have a different issue.

**Comment by tunayuyar** [comment] 2016-11-09 21:45
@boscorelly first setup as usual then change the req file. Then do setup -u it will ask you what to do. Switch it. İt will be fixed.

**Comment by VBQL** [comment] 2016-11-09 21:51
Guys .45 API is enforced, botting now would only get you banned.

**Comment by arkachat** [comment] 2016-11-09 22:20
Mac users running EI Capitan and below needs to perform an additional step .

cd /src/pgoapi/pgoapi/lib/
ln -s libniantichash-macos-64.dylib libniantichash-osx-64.so

**Comment by Gobberwart** [comment] 2016-11-10 01:58
For now... PR coming which will fix that.

**Comment by arjanvanham** [comment] 2016-11-10 04:04
Bot stopped working yesterday, I can confirm that using https://github.com/sebastienvercammen/pgoapi.git in requirements.txt fixes it.

**Closed** 2016-11-11 03:44 UTC
