### ISSUE TITLE
Bot walks faster than max settings (unless the settings are in mph)

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5172] opened 2016-09-04 10:36 UTC
### Expected Behavior
Walking speed obeys the min-max settings in config file

### Actual Behavior
Max speed was set as 4.16 but the actual speed is > 5kmh and even higher, taking in to account of other delays and actions.
(Unless the config is in mph, while log is in kmh)

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
```
"walk_max": 4.16,
  "walk_min": 2.16,
  "alt_min": 500,
  "alt_max": 1000,
  "gps_default_altitude": 8.0,
  "replicate_gps_xy_noise": false,
  "replicate_gps_z_noise": false,
  "gps_xy_noise_range": 0.000125,
  "gps_z_noise_range": 12.5,
  "debug": false,
  "test": false,
  "walker_limit_output": false,
  "health_record": true,
  "location_cache": false,
  "distance_unit": "km",
```

### Output when issue occurred
```
[2016-09-04 17:29:22] [UpdateLiveStats] [log_stats] Uptime : 4:02:20 | 20.85km walked | Visited 148 stops | +27,900 XP | Encountered 122 pokemon, 116 caught, 92 released, 0 evolved, 1 never seen before | Most perfect pokemon : Goldeen [CP: 399] [IV: 12/12/15] Potential: 0.87 
```

### Steps to Reproduce
just run the bot

### Other Information
OS: 
Mac
Branch: 
Dev
Git Commit: 
83c154645da127e0d061f93a2d073ee1423e7e3d

**Comment by th3w4y** [comment] 2016-09-04 11:25
@lntn speed is in m/s

**Comment by kenkclam** [comment] 2016-09-04 17:29
@th3w4y Are you sure the walking speed is in m/s?
Human average walking speed is around 5km/hr, which is 80m/s
The default 4.16 sounds too off then, it makes more sense that the speed is in km/hr

**Comment by th3w4y** [comment] 2016-09-04 17:42
that is what the calculations are doing m/s

**Comment by jrjhealey** [comment] 2016-09-04 21:06
I too was under the assumption that the speed parameter was in km/h.

Its possible the discrepancy you see comes from inaccuracies in the GPS measurement maybe?

**Comment by th3w4y** [comment] 2016-09-04 21:13
@kenkclam well then the defaults are wrong... someone should change them

**Comment by jannickv** [comment] 2016-09-06 00:33
Speed is in m/s indeed. 4.16 = 15km/h which is max for hatching... Thats why it's the default #

**Comment by jrjhealey** [comment] 2016-09-06 10:21
I've changed the labels. This is evidently not a bug but as I was also under the wrong impression the documentation will need to be made to be more explicit (or a comment line added to the json file)

**Comment by th3w4y** [comment] 2016-09-07 19:42
@jrjhealey documentation was updated some time back

| `walk_max`             | 4.16    | Set the maximum walking speed in m/s (1 is about 3.6km/hr) 4.16m/s = 15km/h
| `walk_min`             | 2.16    | Set the minimum walking speed in m/s (1 is about 3.6km/hr) 2.16m/s = 7.8km/h

**Comment by th3w4y** [comment] 2016-09-07 19:44
@jrjhealey Do you think we need a comment in the son also?

**Comment by mmixx** [comment] 2016-09-08 11:33
Hmmm... This is kind of odd... If it's in reality, I might be a runner...

```
[2016-09-08 19:27:48] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.15km
[2016-09-08 19:27:53] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.05km
```

0.10km in just 5 seconds? 0.10km = 100 meters right?

**Comment by th3w4y** [comment] 2016-09-08 12:16
@mmixx  what min_max walk speed do you have configured?

**Comment by mmixx** [comment] 2016-09-08 12:42
@th3w4y I used the default min and max walk speed when that log occured
```
    "walk_max": 4.16,
    "walk_min": 2.16,
```
Right now, I lessen the max and min to get the bot walk slowly...
```
    "walk_max": 1.38,
    "walk_min": 1.00,
```

Current dev commit I'm at is: 6aea15f

Tasks I'm using is from config.json.example template.

Here is the lines before 19:27:48 and after 19:27:53 and it is before I lessen the `walk_max` and `walk_min`:
```
[2016-09-08 19:27:03] [MoveToFort] [INFO] Moving towards pokestop Boni Solar Powered LED Tunnel  - 0.10km
[2016-09-08 19:27:06] [  SpinFort] [INFO] Spun pokestop Boni Solar Powered LED Tunnel . Experience awarded: 50. Items awarded: 1x Potion, 3x Pokeball
[2016-09-08 19:27:12] [MoveToFort] [INFO] Moving towards pokestop Pioneer Woodlands Building Art - 0.14km
[2016-09-08 19:27:17] [  SpinFort] [INFO] Spun pokestop Pioneer Woodlands Building Art. Experience awarded: 100. Items awarded: 1x Razz Berry, 1x Potion, 4x Pokeball, 1x Greatball
[2016-09-08 19:27:21] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.15km
[2016-09-08 19:27:21] [RecycleItems] [INFO] Forcing item recycle based on schedule
[2016-09-08 19:27:21] [RecycleItems] [INFO] Next forced item recycle at 19:29:23
[2016-09-08 19:27:26] [ItemRecycler] [INFO] Discarded 14x Pokeball.
[2016-09-08 19:27:31] [ItemRecycler] [INFO] Discarded 2x Greatball.
[2016-09-08 19:27:35] [ItemRecycler] [INFO] Discarded 3x Potion.
[2016-09-08 19:27:40] [ItemRecycler] [INFO] Discarded 1x Super Potion.
[2016-09-08 19:27:44] [ItemRecycler] [INFO] Discarded 1x Hyper Potion.
[2016-09-08 19:27:48] [ItemRecycler] [INFO] Discarded 2x Razz Berry.
[2016-09-08 19:27:48] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.15km
[2016-09-08 19:27:53] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.05km
[2016-09-08 19:27:54] [  SpinFort] [INFO] Spun pokestop Globe Asiatic Wall Painting. Experience awarded: 50. Items awarded: 2x Potion, 1x Max Potion
[2016-09-08 19:27:59] [MoveToFort] [INFO] Moving towards pokestop Yellow Line MRT Boni Station - 0.10km
[2016-09-08 19:28:02] [PokemonCatchWorker] [INFO] Skip ignored Weedle! [CP 231] [Potential 0.4] [A/D/S 3/15/0]
[2016-09-08 19:28:03] [PokemonCatchWorker] [INFO] Skip ignored Pidgeotto! [CP 204] [Potential 0.29] [A/D/S 5/6/2]
[2016-09-08 19:28:05] [MoveToFort] [INFO] Moving towards pokestop Yellow Line MRT Boni Station - 0.05km
[2016-09-08 19:28:06] [  SpinFort] [INFO] Spun pokestop Yellow Line MRT Boni Station. Experience awarded: 50. Items awarded: 1x Potion, 2x Greatball
```

**Comment by th3w4y** [comment] 2016-09-08 13:06
I see 3 logs related to  Globe Asiatic Wall Painting !
first 19:27:21  last 19:27:53 = 32 seconds apart


```
[2016-09-08 19:27:21] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.15km
[2016-09-08 19:27:48] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.15km
[2016-09-08 19:27:53] [MoveToFort] [INFO] Moving towards pokestop Globe Asiatic Wall Painting - 0.05km

```

From your output you had a speed of 3.12m/s
```
In [16]: 53-21 # seconds
Out[16]: 32

In [17]: (0.15- 0.05 )*1000 # meters
Out[17]: 99.99999999999999

In [18]: 53-21 # seconds
Out[18]: 32

In [19]: 100.0/32.0 #m/s
Out[19]: 3.125

In [20]: (2.16+4.16)/2 #average min/max
Out[20]: 3.16

In [21]: 
```

**Comment by th3w4y** [comment] 2016-09-08 13:07
question is why you had the entry in the middle displayed with 0.15km.... ~~[could it be that the function to display in km does rounding..]~~

**Comment by mmixx** [comment] 2016-09-08 13:26
With my current walk_max of 1.38 and walk_min of 1.00... this is what I see:
```

**Comment by th3w4y** [comment] 2016-09-08 14:03
i can confirm  2 big jumps and will continue investigate

[2016-09-08 21:22:18] [MoveToFort] [INFO] Moving towards pokestop Citihomes Water Repository Tank - 0.33km
[2016-09-08 21:22:23] [MoveToFort] [INFO] Moving towards pokestop Citihomes Water Repository Tank - 0.20km
[2016-09-08 21:22:28] [MoveToFort] [INFO] Moving towards pokestop Citihomes Water Repository Tank - 0.08km

**Comment by th3w4y** [comment] 2016-09-08 14:24
@mmixx Can you confirm you see the issue only at the end of the walk?

**Comment by mmixx** [comment] 2016-09-08 14:37
@th3w4y After checking my logs... it seems it only occurs at the start of running the bot... then after a few minutes, it slows the bot's jump...

```
[2016-09-08 21:24:36] [MoveToFort] [INFO] Moving towards pokestop Banana Leaf Stone Painting - 0.26km
[2016-09-08 21:24:41] [MoveToFort] [INFO] Moving towards pokestop Banana Leaf Stone Painting - 0.12km
```
```
[2016-09-08 21:25:09] [MoveToFort] [INFO] Moving towards pokestop Tivoli Iris Wall Art - 0.14km
[2016-09-08 21:25:18] [MoveToFort] [INFO] Moving towards pokestop Tivoli Iris Wall Art - 0.13km
[2016-09-08 21:25:27] [MoveToFort] [INFO] Moving towards pokestop Tivoli Iris Wall Art - 0.13km
[2016-09-08 21:25:33] [MoveToFort] [INFO] Moving towards pokestop Tivoli Iris Wall Art - 0.13km
[2016-09-08 21:25:38] [MoveToFort] [INFO] Moving towards pokestop Tivoli Iris Wall Art - 0.12km
```

But on 2016-09-08 21:26:53 to 2016-09-08 21:26:58 below... it jumped 0.13km in just 5 seconds...
```
[2016-09-08 21:26:37] [MoveToFort] [INFO] Moving towards pokestop Makati-Mandaluyong Bridge - 0.16km
[2016-09-08 21:26:43] [MoveToFort] [INFO] Moving towards pokestop Makati-Mandaluyong Bridge - 0.15km
[2016-09-08 21:26:49] [  SpinFort] [INFO] Spun pokestop Makati-Mandaluyong Bridge. Experience awarded: 50. Items awarded: 2x Pokeball, 1x Greatball
[2016-09-08 21:26:53] [MoveToFort] [INFO] Moving towards pokestop Kapilya Ng Samahang Happy XII - 0.31km
[2016-09-08 21:26:58] [MoveToFort] [INFO] Moving towards pokestop Kapilya Ng Samahang Happy XII - 0.18km
[2016-09-08 21:27:03] [  SpinFort] [INFO] Spun pokestop Kapilya Ng Samahang Happy XII. Experience awarded: 100. Items awarded: 1x Potion, 5x Pokeball
[2016-09-08 21:27:06] [MoveToFort] [INFO] Moving towards pokestop Poblacion Baranggay Hall - 0.11km
[2016-09-08 21:27:09] [  SpinFort] [INFO] Spun pokestop Poblacion Baranggay Hall. Experience awarded: 50. Items awarded: 1x Potion, 2x Pokeball
```

At this moment, still haven't stopped the bot and just watching the logs... the jumps are now normal (again)...
```
[2016-09-08 22:33:18] [  SpinFort] [INFO] Spun pokestop Pup Laboratory High School. Experience awarded: 50. Items awarded: 3x Pokeball
[2016-09-08 22:33:23] [MoveToFort] [INFO] Moving towards pokestop PUP Tahanan ng Alumni Building - 0.11km
[2016-09-08 22:33:28] [MoveToFort] [INFO] Moving towards pokestop PUP Tahanan ng Alumni Building - 0.08km
[2016-09-08 22:33:33] [MoveToFort] [INFO] Moving towards pokestop PUP Tahanan ng Alumni Building - 0.04km
[2016-09-08 22:33:35] [  SpinFort] [INFO] Spun pokestop PUP Tahanan ng Alumni Building. Experience awarded: 50. Items awarded: 1x Potion, 2x Pokeball
[2016-09-08 22:33:40] [MoveToFort] [INFO] Moving towards pokestop PUP Swimming Pool - 0.11km
[2016-09-08 22:33:45] [MoveToFort] [INFO] Moving towards pokestop PUP Swimming Pool - 0.09km
[2016-09-08 22:33:50] [MoveToFort] [INFO] Moving towards pokestop PUP Swimming Pool - 0.06km
[2016-09-08 22:33:54] [  SpinFort] [INFO] Spun pokestop PUP Swimming Pool. Experience awarded: 50. Items awarded: 1x Ultraball, 2x Pokeball
[2016-09-08 22:33:59] [MoveToFort] [INFO] Moving towards pokestop PUP Tennis Court - 0.08km
[2016-09-08 22:34:04] [MoveToFort] [INFO] Moving towards pokestop PUP Tennis Court - 0.05km
[2016-09-08 22:34:08] [  SpinFort] [INFO] Spun pokestop PUP Tennis Court. Experience awarded: 50. Items awarded: 1x Potion, 1x Pokeball, 1x Revive
[2016-09-08 22:34:13] [MoveToFort] [INFO] Moving towards pokestop PUP Gymnasium - 0.08km
[2016-09-08 22:34:18] [MoveToFort] [INFO] Moving towards pokestop PUP Gymnasium - 0.05km
[2016-09-08 22:34:20] [  SpinFort] [INFO] Spun pokestop PUP Gymnasium. Experience awarded: 50. Items awarded: 3x Pokeball
```

**Comment by th3w4y** [comment] 2016-09-08 14:50
do i see a pattern here? or is it just me... is it after the spin?

**Comment by th3w4y** [comment] 2016-09-08 15:38
can you check if is fixed in latest dev

both @Anakin5  and me ended up finding the bug that caused it

**Comment by mmixx** [comment] 2016-09-08 15:45
@th3w4y With the same settings that I have used above...
```
    "walk_max": 1.38,
    "walk_min": 1.00,
```

below are the first `MoveToFort` logs...
```
[2016-09-08 23:40:58] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.12km
[2016-09-08 23:41:03] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.11km
[2016-09-08 23:41:08] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.11km
[2016-09-08 23:41:14] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.10km
[2016-09-08 23:41:20] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.09km
[2016-09-08 23:41:25] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.09km
[2016-09-08 23:41:30] [MoveToFort] [INFO] Moving towards pokestop Grotto sa Batis - 0.08km
```
I think it's fixed now... will check logs further more to see if it's running smoothly... Thanks...

**Comment by th3w4y** [comment] 2016-09-08 16:35
@mmixx I will close this as initially the bug regarding the unit of measurement regarding which the documentation was updated.

@mmixx If you still have issues regarding the incorrect distance lets continue the discussion on https://github.com/PokemonGoF/PokemonGo-Bot/issues/5291

**Closed by th3w4y** 2016-09-08 16:35 UTC
