### ISSUE TITLE
integer out of range for 'Q' format code

### ISSUE THREAD

**Issue by larssy1** [PokemonGoF/PokemonGo-Bot#1249] opened 2016-07-27 19:30 UTC
I'm getting the following error when trying to run 'pokecli.py'

```
[2016-07-28 05:26:44] [x] Starting PokemonGo Bot....
[2016-07-28 05:26:44] [#] Scanning area for objects (1 / 25)
Traceback (most recent call last):
  File "xxx\pokecli.py", line 220, in <module>
    main()
  File "xxx\pokecli.py", line 211, in main
    bot.take_step()
  File "xxx\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "xxx\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "xxx\pokemongo_bot\stepper.py", line 67, in _walk_to
    i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
  File "xxx\pokemongo_bot\cell_workers\utils.py", line 98, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code
```

This is the config i'm using:

```
{
	"auth_service": "ptc",
    "username": "xxx",
    "password": "xxx",
    "location": "-33.8657305, 151.20732999999998",
    "gmapkey": "xxx",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}
```

**Comment by toxuin** [comment] 2016-07-27 19:34
see #1094. Possible duplicate.

**Comment by AidanB1702** [comment] 2016-07-27 19:35
none of the solutions are working for me

**Comment by TheGoldenXY** [comment] 2016-07-27 19:40
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1042

/closed

**Closed by TheGoldenXY** 2016-07-27 19:40 UTC

**Comment by larssy1** [comment] 2016-07-27 19:52
Indeed a duplicate. Provided solution works. Sadly wasn't able to find any issue when searching for this exact title.
