### ISSUE TITLE
Web Map doesn't show any location (player, forts or gyms)

### ISSUE THREAD

**Issue by ugurbor** [PokemonGoF/PokemonGo-Bot#796] opened 2016-07-25 11:40 UTC
### Expected Behavior
It should write location-[username].json file under web/ folder. The code is located at pokemongo_bot/stepper.py (line 109)

### Actual Behavior
location-[username].json file is not written or even created. I can see catchable and inventory files are written. So it's not a permission issue imo.

### Other Information
OS: Debian 7 32bit

**Comment by heihachi** [comment] 2016-07-25 11:42
https://github.com/heihachi/PokemonGo-Bot/commit/3623106498f4f47190703c005a9dfa13093fc553
im currently working on this but getting stuck on coord not updating correctly and not getting accurate updates.

**Comment by surfaace** [comment] 2016-07-25 11:43
web folder is not included by this code. its a seperate git repo (https://github.com/OpenPoGo/OpenPoGoWeb by default)

also there is no stepper.py file in dev, so please comment which git commit you are using

**Comment by surfaace** [comment] 2016-07-25 11:54
duplicate of #778

**Closed by surfaace** 2016-07-25 11:54 UTC
Labels: duplicate
