### ISSUE TITLE
[Crash] KeyError: 'result'

### ISSUE THREAD

**Issue by iifuzz** [PokemonGoF/PokemonGo-Bot#866] opened 2016-07-25 20:25 UTC
### Expected Behavior
Works

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 96, in work_on_cell
    hack_chain = worker.work()
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 51, in work
    if spin_details['result'] == 1:
KeyError: 'result'

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by surfaace** [comment] 2016-07-25 20:35
please add git commit

**Comment by ckrmml** [comment] 2016-07-26 00:44
[02:42:19] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 199, in main
    config = init_config()
  File "pokecli.py", line 163, in init_config
    config.catch = load['catch']
KeyError: 'catch'
(PokemonGo-Bot) MacBook-Pro:PokemonGo-Bot christiankrummel$ python pokecli.py -cf configs/gmail_config.json
[02:42:58] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 199, in main
    config = init_config()
  File "pokecli.py", line 163, in init_config
    config.catch = load['catch']
KeyError: 'catch'

Git Commit: ff665d625c028d490fe9d2fd4e6b0b8c10a2d9c9

**Comment by ayozebarrera** [comment] 2016-07-26 09:39
I had the same issue. Bot was running and crashed.

```
[2016-07-26 10:36:19] [#] Finished walking
[2016-07-26 10:36:19] [#] Arrived at Pokestop
[2016-07-26 10:36:21] [#] Now at Pokestop: Unknown - Spinning...
Traceback (most recent call last):
  File "pokecli.py", line 222, in <module>
    main()
  File "pokecli.py", line 213, in main
    bot.take_step()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 37, in take_step
    self.stepper.take_step()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/__init__.py", line 98, in work_on_cell
    hack_chain = worker.work()
  File "/Users/ayozebarrera/Proyectos/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 51, in work
    if spin_details['result'] == 1:
KeyError: 'result'
```

Git commit: 4924c9f9c87e892374538e80523ada4b65924e90

**Comment by buettner123** [comment] 2016-07-26 22:12
this issue is duplicating #594

**Comment by surfaace** [comment] 2016-07-26 23:31
duplicate of #594

**Closed by surfaace** 2016-07-26 23:31 UTC
Labels: bug, duplicate
