### ISSUE TITLE
Last Location not working

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1099] opened 2016-07-27 01:55 UTC
### Expected Behavior
Last location should pull the location from data\last-location-username.json (this file exist for me and has the latest time stamp)

    "location": "",
    "gmapkey": "",
    "max_steps": 4,
    "mode": "all",
    "walk": 3.86,
    "debug": false,
    "test": false,
    "initial_transfer": false,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {},
    "evolve_all": "NONE",
    "use_lucky_egg": false,
    "evolve_captured": false,

### Actual Behavior
Running bot won't work, tells me to specify location

[21:51:49] PokemonGO Bot v1.0
[21:51:49] Configuration initialized
[21:51:49] [x] Parsing cached location...
No cached Location. Please specify initial location.

### Steps to Reproduce
Run the bot with a set coordinate for a bit, stop bot, remove coordinate and restart bot

### Other Information
Dev Branch
OS: Win10
Git Commit: 9d2535001b92772c6b797183b1cf4df768806af3

**Comment by TheGoldenXY** [comment] 2016-07-27 01:59
You need to add your location coordinates into the `"location"` parameter. Example shown below:

`"location": "37.787994, -122.407440",`

**Comment by ayiire** [comment] 2016-07-27 02:01
I thought last location would be used if I left that field blank?

**Comment by skorokithakis** [comment] 2016-07-27 02:02
This is a duplicate of #1031.

**Comment by TheGoldenXY** [comment] 2016-07-27 02:06
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1031

Please go to that thread for solution.

/closed

**Closed by TheGoldenXY** 2016-07-27 02:06 UTC
Labels: duplicate
