### ISSUE TITLE
Catch pokemon = false still catching pokemon

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1388] opened 2016-07-28 10:59 UTC
### Expected Behavior
Setting catch pokemon: false should not catch pokemon

### Actual Behavior
Pokemon is still caught when set to false.

```
    "max_steps": 4,
    **"catch_pokemon": false,**
    "spin_forts": true,
    "walk": 5.70,
    "debug": false,
    "test": false,
    "initial_transfer": false,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": {      
      "101": { "keep" : 1 },
      "102": { "keep" : 1 },
      "103": { "keep" : 25 },
      "201": { "keep" : 30 },
      "701": { "keep" : 35 }
	  },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

   

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
```
### Steps to Reproduce
Change catch_pokemon to false

### Other Information
Dev Branch
OS: Win10
Git Commit: 7e608c2ff5367be0e22cdf55228056aad5a0d718

**Comment by regzzz** [comment] 2016-07-28 11:02
Do you use lastest example config?

**Comment by ayiire** [comment] 2016-07-28 11:06
Didn't realize more lines changed, testing that now.

**Comment by ayiire** [comment] 2016-07-28 11:26
Checked out the latest dev in a new folder and it's still capturing pokemon. I used the config.json.example to rule out the pokemon rules

```
{
    "auth_service": "google",
    "username": "xxx",
    "password": "xxx",
    "location": "xxx",
    "gmapkey": "xxx",
    "max_steps": 5,
    "catch_pokemon": false,
    "spin_forts": true,
    "walk": 5.66,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": {      
      "101": { "keep" : 1 },
      "102": { "keep" : 1 },
      "103": { "keep" : 25 },
      "201": { "keep" : 30 },
      "701": { "keep" : 35 }
	  },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "release_pokemon": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": { "always_release" : true },
      "// Example of keeping stronger (based on CP) Pidgey:": {},
      "// Pidgey": { "keep_best_cp" : true },
      "// Example of keeping stronger (based on IV) Zubat:": {},
      "// Zubat": { "keep_best_iv" : true }
    }
}
```

**Comment by buettner123** [comment] 2016-07-28 12:03
probably a duplicate of #1374

**Comment by weknin** [comment] 2016-07-28 12:52
confirm for me too

**Comment by tonz134** [comment] 2016-07-28 13:22
Edit it inside the pokecli.py to disable.
not sure why it won't read from config.
```
    parser.add_argument("--catch_pokemon",help="Enable catching pokemon",type=bool,default=True)
    parser.add_argument("--spin_forts",help="Enable Spinning Pokestops",type=bool,default=False)
```

**Comment by TheGoldenXY** [comment] 2016-07-28 22:29
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1374

/closed

**Closed by TheGoldenXY** 2016-07-28 22:29 UTC
