### ISSUE TITLE
Crash after sync dev in move_to_map_pokemon.py

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4125] opened 2016-08-16 23:20 UTC
same as issue #4124 
### Actual Behavior
after start and catching Pokemon, a crash occurs in line:
/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 147, in get_pokemon_from_map
    if pokemon['dist'] > ((pokemon['expire'] - now) * mean_walk_speed) and not self.config['snipe']:
KeyError: 'expire'

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/JTUPEe98

### Output when issue occurred
http://pastebin.com/nQPhRc8V

### Steps to Reproduce
started run.sh

### Other Information
OS: OSX Maverick
Branch: dev
Git Commit: aaaa4807299fc7647a76fd3ba9829664b96f88a7
Python Version: Python 2.7.12

**Comment by Gurzeh** [comment] 2016-08-16 23:26
It seems that 'expire' is not defined.

**Comment by k4n30** [comment] 2016-08-17 03:33
#4115

**Comment by k4n30** [comment] 2016-08-17 03:38
Duplicate of #4113

**Closed by k4n30** 2016-08-17 03:38 UTC
Labels: Duplicate, Waiting on Merge
