### ISSUE TITLE
PokemonOptimizer stopped working

### ISSUE THREAD

**Issue by sffetlio** [PokemonGoF/PokemonGo-Bot#4252] opened 2016-08-19 07:01 UTC
### Expected Behavior
PokemonOptimizer should transfer and evolve pokemon when bag is getting full.

### Actual Behavior
No pokemon are being transferred or evolved.

### Additional info
It worked in 8eba07a. Maybe it's related to the new inventory commit.
One thing I noticed is that before it showed:
`[PokemonOptimizer] [INFO] Pokemon Bag: 192/250`
after every catch, but now it doesn't.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
```
      {
          "type": "PokemonOptimizer",
          "config": {
              "transfer": true,
              "transfer_wait_min": 1,
              "transfer_wait_max": 4,
              "evolve": true,
              "evolve_time": 20,
              "evolve_for_xp": true,
              "evolve_only_with_lucky_egg": true,
              "evolve_count_for_lucky_egg": 90,
              "may_use_lucky_egg": true,
              "keep": [
                  {
                      "top": 1,
                      "evolve": true,
                      "sort": ["dps","ncp","iv"]
                  },
                  {
                      "top": 1,
                      "evolve": true,
                      "sort": ["cp"]
                  }
              ]
          }
      },
```

### Output when issue occurred
```
[PokemonCatchWorker] [INFO] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!
```

### Other Information
OS: Ubuntu
Branch: dev
Git Commit: 198510b70388f7d70478db847e77bf12095d004a
Python Version: Python 2.7.6
Any other relevant files/configs (eg: path files)

**Comment by zx900930** [comment] 2016-08-19 08:06
+1 same here with commit 324b752 ("Configurable altitude range  (#4250)", 2016-08-19)

**Comment by balpoint** [comment] 2016-08-19 09:16
Same issue here getting the following message's in the log.

> 016-08-19 11:14:48,205 [PokemonCatchWorker] [INFO] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!
2016-08-19 11:14:48,217 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Together - 0.13km
2016-08-19 11:14:49,616 [PokemonCatchWorker] [INFO] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!
2016-08-19 11:14:49,630 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Together - 0.12km
2016-08-19 11:14:50,894 [PokemonCatchWorker] [INFO] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!

**Comment by Calcyfer** [comment] 2016-08-19 09:25
Duplicate : #4235

**Comment by p1n9** [comment] 2016-08-19 09:25
Same for me, Git Commit: 324b752f031cdb39d52c396ea50e14a59841535e

**Comment by Calcyfer** [comment] 2016-08-19 09:57
Something seems wrong with how a full bag is calculated.
In the app, I'm seeing 250/250, a full bag.
The bot however shows this : 

```
2016-08-19 11:46:17,322 [PokemonGoBot] [INFO] Pokemon Captured: 241 | Pokestops Visited: 94
2016-08-19 11:46:17,463 [PokemonGoBot] [INFO]
2016-08-19 11:46:17,463 [PokemonGoBot] [INFO] --- redacted ---
2016-08-19 11:46:18,640 [PokemonGoBot] [INFO] Pokemon Bag: 241/250
2016-08-19 11:46:18,641 [PokemonGoBot] [INFO] Items: 225/350
```

**Comment by Calcyfer** [comment] 2016-08-19 10:06
Seems to be related to the new inventory system not counting eggs. Are eggs considered as used space in a bag.. ?

**Comment by k4n30** [comment] 2016-08-19 11:16
@Calcyfer I don't think this is a duplicate of #4235 as it works in there for awhile and then stops

**Comment by k4n30** [comment] 2016-08-19 11:32
Fixed by either #4258 or #4254

**Comment by Calcyfer** [comment] 2016-08-19 11:34
Indeed not a duplicate, removing the reference.

**Comment by mjmadsen** [comment] 2016-08-19 20:35
Think we can close this now. Is it working for you guys?

**Comment by Anakin5** [comment] 2016-08-20 03:54
This issue has been fixed

**Closed** 2016-08-20 04:09 UTC
Labels: Bug, Waiting on Merge
