### ISSUE TITLE
[DEV] Not evolving any Pokemon

### ISSUE THREAD

**Issue by TheOssi** [PokemonGoF/PokemonGo-Bot#1151] opened 2016-07-27 08:16 UTC
### Expected Behavior
Bot should evolve Pokémon on startup.

### Actual Behavior
He basically skips the evolution(no console log)
[10:04:56] Pokemon Captured: 1309 | Pokestops Visited: 547
[10:04:57] Pokemon Bag: 227/250
[10:04:57] Items: 321/350
[10:04:57] Stardust: 146604 | Pokecoins: 0
[10:04:57] PokeBalls: 48 | GreatBalls: 0 | UltraBalls: 32
[10:04:57] Razz Berries: 74
[10:04:57]
[10:04:57]
[10:04:59] Starting PokemonGo Bot....
[10:04:59] Scanning area for objects....
[10:04:59] Walking from (49.303157, 8.642888) to [49.303157, 8.642888] 0.00km
[========================================] 100%
[10:05:05] Cleaning up Pokemon Bag using the release config
[10:05:05] Pokemon Bag has been cleaned up!
[10:05:05] Using lucky egg ... you have 2
[10:05:06] Found fort 142f22cda073459ab55132cdc45190f0.16 at distance 0.02km
[10:05:06] Need to move closer to Pokestop

### Steps to Reproduce
config:
"evolve_all": "all", not working
"evolve_all": "Pidgey,Zubat,Weedle" , does not work either

### Other Information
OS:  Ubuntu 16.10
Git Commit: 97658283f37db827af940f5d74146346ccfcdf06

**Comment by Anyrainel** [comment] 2016-07-27 08:39
Same problem here

**Comment by StarForser** [comment] 2016-07-27 09:52
The same problem there is a solution?

**Comment by sn0opy** [comment] 2016-07-27 12:38
There seems to be a bug in the _should_run() function. You can comment out the following two lines as a workaround

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/evolve_all_worker.py#L16#L17

**Comment by codybaldwin** [comment] 2016-07-27 14:15
This issue was caused by PR #1159 by the following addition to evolve_all_worker: 'skip_evolves = False

        if self.config.evolve_all:
            return skip_evolves'
this logic will return false every time the use_lucky_egg config is true. Causing the evolve to be skipped when a lucky egg is used.

**Comment by ShapeShifter499** [comment] 2016-07-27 15:04
@codybaldwin @sn0opy If I want to have a temporary work around which edit do I use?

**Comment by codybaldwin** [comment] 2016-07-27 15:07
as @sn0opy  said:  in pokemongo_bot\cell_workers\evolve_all_worker.py comment out line 16 and 17 by placing a # in front of them like so 
'
 def work(self):
        #if not self._should_run():
            #return

        self.api.get_inventory()
        response_dict = self.api.call()
        cache = {}
'

**Comment by ShapeShifter499** [comment] 2016-07-27 15:38
@codybaldwin @sn0opy Workaround is working for me it appears in latest DEV branch. Thank you for the help. Let me know if this ever gets fixed upstream.

**Comment by apyapy** [comment] 2016-07-27 17:26
will the workaround work for master?

**Comment by ShapeShifter499** [comment] 2016-07-27 19:01
Newest `git pull`   on the DEV branch and still experiencing the above bug.   Does the work around still apply?


**Other Information**

OS: Arch Linux 64bit
Git Commit: 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3

**Comment by ShapeShifter499** [comment] 2016-07-27 19:16
Workaround mentioned above still works.

**Other Information**

OS: Arch Linux 64bit
Git Commit: 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3

**Comment by theadriann** [comment] 2016-07-27 20:20
Submitted a PR here to fix this bug.
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1256

**Comment by TheGoldenXY** [comment] 2016-07-28 22:39
PR has been opened to fix this issue. When you see this PR has been merged #1256 , update to latest `dev` branch. Closing this for now.

/closed

**Closed by TheGoldenXY** 2016-07-28 22:39 UTC
Labels: bug, help wanted
