### ISSUE TITLE
No pokestops - bot is only walking and catching pokemons occasionally

### ISSUE THREAD

**Issue by Yanush7** [PokemonGoF/PokemonGo-Bot#1974] opened 2016-07-31 02:29 UTC
### Expected Behavior
Using pokestops

### Actual Behavior
Just walking around

### Steps to Reproduce
Running bot.

### Other Information

Bot stopped to use pokestops, it is just walking around and catching pokemons.
Problem occured without any ingerention in configs or files.
Then i made pull to update bot, but it did not help.

current config:
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "IncubateEggs"
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll"
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "max_steps": 5,
    "forts": {
      "spin": true,
      "move_to_spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },

OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by em202020** [comment] 2016-07-31 02:42
I believe this is to do with the new "navigator" feature that was added with very little explanation of how it works.  In config.json.path.example, you can see a little snippet of code relating to the type, and path_mode, but have very little meaning behind them, and im not too sure how they work out.  I got the same problem as you are having where it just wanders around aimlessly.

I personally liked it better where it just hit every pokestop.

**Comment by skorokithakis** [comment] 2016-07-31 02:53
Looks like a duplicate of #1885.

**Comment by k4n30** [comment] 2016-07-31 02:54
I thought the same too for the last few days, but realised it's linked to your item count. If it's close to the limit, it will go into Pokemon catching mode and not hit pokestops (as ur bag is / or approaching full) I changed my config and dumped 100 pokeballs and functionality returned

**Comment by skorokithakis** [comment] 2016-07-31 02:56
Ah, can you close this then?

**Comment by em202020** [comment] 2016-07-31 03:03
For my problem personally, it is not affected by my bag being full, not sure if this is OPs problem, but it still exists with my bag half empty.

**Comment by Yanush7** [comment] 2016-07-31 03:41
Just did clean install of bot and now it is ALMOST working - it goes to 2 or 3 pokestops and after that he is stuck going "there and back" between pokestops, never reaching them.

**Comment by em202020** [comment] 2016-07-31 04:00
Im on the latest commit, and I removed the lines:
      {
        "type": "FollowSpiral"
      }
from the config file, and it started hitting pokestops for me again.
http://i.imgur.com/396POjI.png

**Comment by leoi11** [comment] 2016-07-31 05:07
The solution in https://github.com/PokemonGoF/PokemonGo-Bot/issues/1974#issuecomment-236408059 works for me.

**Comment by gregtampa** [comment] 2016-07-31 06:44
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG

**Closed by gregtampa** 2016-07-31 06:44 UTC
