### ISSUE TITLE
keep best cp

### ISSUE THREAD

**Issue by yehan77** [PokemonGoF/PokemonGo-Bot#1402] opened 2016-07-28 13:17 UTC
### Expected Behavior
keep best cp, transfer low 
### Actual Behavior
transfers everything
{
    "auth_service": "google",
    "username": "xxxx@gmail.com",
    "password": "xxxxx",
    "location": "1 Rider Blvd, Rhodes NSW 2138",
    "gmapkey": "xxxx", 
    "max_steps": 15,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104,201",
    "evolve_all": "NONE",
    "any": {"keep_best_cp": 2}
}

### Other Information
OS: osx yosemite,
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
how do i fix it?

**Comment by ironbishop** [comment] 2016-07-28 13:22
duplicate of #953 

work in progress #1395

**Comment by yehan77** [comment] 2016-07-28 13:42
still confused

**Comment by ironbishop** [comment] 2016-07-28 13:50
The developers are already working on this, and you need to wait for them to finish that feature.
Tou can also help them providing code and/or coffe for them.

**Comment by yehan77** [comment] 2016-07-28 13:55
ok, is there a way like if i get a good pokemon it keeps?

**Comment by xorinzor** [comment] 2016-07-28 17:17
@yehan77 they are working on that, as previously stated by @ironbishop.

Please close this issue.

**Comment by TheGoldenXY** [comment] 2016-07-28 22:29
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/pull/953

/closed

**Closed by TheGoldenXY** 2016-07-28 22:29 UTC
