### ISSUE TITLE
Bot start fails on fresh accounts if "UpdateLiveStats" is set to "true"

### ISSUE THREAD

**Issue by einszA** [PokemonGoF/PokemonGo-Bot#4036] opened 2016-08-15 22:30 UTC
Bot start fails on fresh ptc accounts if "UpdateLiveStats" is set to "true" in config.json. (master)

  {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": false,
          "terminal_title": true
        }

### output:
2016-08-16 00:19:49,068 [PokemonGoBot] [INFO]
2016-08-16 00:19:49,979 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-16 22:36:56.979000
2016-08-16 00:19:50,230 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-16 00:19:51,819 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-16 00:19:52,325 [       cli] [INFO]
2016-08-16 00:19:52,325 [       cli] [INFO] Ran for 0:00:07
Traceback (most recent call last):
  File "C:\Python27\PokemonGo-Bot\pokecli.py", line 595, in <module>
    main()
  File "C:\Python27\PokemonGo-Bot\pokecli.py", line 162, in main
    report_summary(bot)
  File "C:\Python27\PokemonGo-Bot\pokecli.py", line 200, in report_summary
    logger.info('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

Running the bot once with "UpdateLiveStats" set to "false" and than changing teh value back to true resolves this issue.

### Steps to Reproduce
- create new ptc account
- use config with UpdateLiveStats set to true
- start bot with PokemonGo-Bot-Start.bat

### Other Information
OS: win10
Git Commit: d90a203194bbf97d06c66f1f6325c4576c8f8dde
Python Version: 2.7.10

**Comment by keugnu** [comment] 2016-08-16 00:33
Brand new account right?

**Comment by k4n30** [comment] 2016-08-16 01:23
Duplicate of #3968

**Closed by k4n30** 2016-08-16 01:23 UTC
Labels: Duplicate
