### ISSUE TITLE
Progress seems slow

### ISSUE THREAD

**Issue by jrjhealey** [PokemonGoF/PokemonGo-Bot#3062] opened 2016-08-08 13:02 UTC
### Expected Behavior
The bot runs fine, walks, catches, hatches - all that good stuff. However, compared to the old master commit I was running before the API change, the bot's progress just seems a bit sluggish to me. In particular the bot only manages to walk a couple of km in several hours.

### Actual Behavior
However, compared to the old master commit I was running before the API change, the bot's progress just seems a bit sluggish to me. In particular the bot only manages to walk a couple of km in several hours.

The config file is set at 10km an hour and yet, the bot only managed 2km in almost 5 hours - see my termination summary below. I ran the bot overnight last night, almost 9 hours and I think it only moved a total of 5 km

`2016-08-08 12:55:48,409 [       cli] [INFO]
2016-08-08 12:55:48,410 [       cli] [INFO] Ran for 4:50:25
2016-08-08 12:55:48,411 [       cli] [INFO] Total XP Earned: 9675  Average: 1998.87/h
2016-08-08 12:55:48,411 [       cli] [INFO] Travelled 2.09km
2016-08-08 12:55:48,412 [       cli] [INFO] Visited 25 stops
2016-08-08 12:55:48,412 [       cli] [INFO] Encountered 31 pokemon, 30 caught, 0 released, 0 evolved, 1 never seen before
2016-08-08 12:55:48,412 [       cli] [INFO] Threw 34 pokeballs
2016-08-08 12:55:48,413 [       cli] [INFO] Earned 5870 Stardust
2016-08-08 12:55:48,413 [       cli] [INFO]
2016-08-08 12:55:48,413 [       cli] [INFO] Highest CP Pokemon: Parasect [CP: 1002] [IV: 14/15/5] Potential: 0.76
2016-08-08 12:55:48,414 [       cli] [INFO] Most Perfect Pokemon: Oddish [CP: 375] [IV: 12/7/15] Potential: 0.76`

### Steps to Reproduce
Running fermuch's branch of the bot - see #2808 

### Other Information
OS: Ubuntu 14.04
Git Commit: 153ea212999e337b54e09761f6defbabb0de4e8c
Python Version: Python 2.7.6

**Comment by PraeceptorXS** [comment] 2016-08-08 13:04
Where are you located? Try setting the bot in a location with a lot of pokemon. I use Santa Monica Pier and get 25k xp/hour. Don't worry, you won't get banned.

**Comment by DiegoRBaquero** [comment] 2016-08-08 13:09
What's your config like? Maybe increase your speed?

**Comment by jrjhealey** [comment] 2016-08-08 13:16
Well the location I'm currently using is one that was previously performing much better (it's wondering around my uni campus primarily). On the old master branch I would easily gain a level in a matter of hours, now I'm only generating a couple of thousand XP. I'll give a geolocation change a go since thats an obvious solution.

@DiegoRBaquero my config file speed is configured at 10 or 11 km an hour walking speed.

**Comment by PraeceptorXS** [comment] 2016-08-08 13:19
Here is my config
{
	"auth_service": "google",
	"username": "Your Username",
	"password": "Your Password 1234",
	"location": "34.009340, -118.496973",
	"gmapkey": "Your Key",
	"tasks": [{
		"type": "HandleSoftBan"
	}, {
		"type": "CollectLevelUpReward"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		}
	}, {
		"type": "TransferPokemon"
	}, {
		"type": "RecycleItems",
		"config": {
			"item_filter": {
				"Pokeball": {
					"keep": 80
				},
				"Potion": {
					"keep": 10
				},
				"Super Potion": {
					"keep": 10
				},
				"Greatball": {
					"keep": 80
				},
				"Ultraball": {
					"keep": 80
				},
				"Hyper Potion": {
					"keep": 10
				},
				"Max Potion": {
					"keep": 40
				},
				"Revive": {
					"keep": 0
				},
				"Max Revive": {
					"keep": 50
				},
				"Razz Berry": {
					"keep": 50
				}
			}
		}
	}, {
		"type": "CatchVisiblePokemon"
	}, {
		"type": "CatchLuredPokemon"
	}, {
		"type": "SpinFort"
	}, {
		"type": "MoveToFort",
		"config": {
			"lure_attraction": true,
			"lure_max_distance": 2000
		}
	}, {
		"type": "FollowSpiral",
		"config": {
			"diameter": 4,
			"step_size": 70
		}
	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": false,
		"max_circle_size": 50
	},
	"websocket_server": true,
	"walk": 20,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": true,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"catch": {
		"any": {
			"catch_above_cp": 400,
			"catch_above_iv": 0.5,
			"logic": "or"
		},
		"// Example of always catching Rattata:": {},
		"// Rattata": {
			"always_catch": true
		}
	},
	"release": {
		"any": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"vips": {
			"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
			"any": {
				"catch_above_cp": 1500,
				"catch_above_iv": 0.9,
				"logic": "or"
			},
			"Lapras": {},
			"Moltres": {},
			"Zapdos": {},
			"Articuno": {},
			"Snorlax": {},
			"Dragonite": {},

			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
			"Mewtwo": {},
			"Dragonite": {},
			"Snorlax": {},
			"// Mew evolves to Mewtwo": {},
			"Mew": {},
			"Arcanine": {},
			"Vaporeon": {},
			"Gyarados": {},
			"Exeggutor": {},
			"Muk": {},
			"Weezing": {},
			"Flareon": {}

		}
	}
}

**Comment by BriceSD** [comment] 2016-08-08 13:24
@jrjhealey The bot is fine, your config file isn't.
Mine is at 60k-70k/h.

**Comment by hew-xavier** [comment] 2016-08-08 13:24
This is duplicate of other issue.
#3056 

See other issue for possible cause and local fix (if you don't require map integration).

**Comment by Krewedk0** [comment] 2016-08-08 13:27
@BriceSD can you post your config please?

**Comment by BriceSD** [comment] 2016-08-08 13:37
hew-xavier is right, i forgot about the map issue. But appart from that it works fine
@Krewedk0 #2491

**Comment by jrjhealey** [comment] 2016-08-08 13:52
Yeah you may all be right, might be a case of optimising my config. Switching to Santa Monica pier has, of course, softbanned me haha..

**Closed** 2016-08-09 07:45 UTC
