### ISSUE TITLE
KeyError: 'GET_INVENTORY'

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#1491] opened 2016-07-28 21:23 UTC
### Actual Behavior
````
Traceback (most recent call last):
  File "./pokecli.py", line 357, in <module>
    main()
  File "./pokecli.py", line 68, in main
    bot.tick()
  File "/home/lunik/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/lunik/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items_worker.py", line 14, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/home/lunik/PokemonGo-Bot/pokemongo_bot/__init__.py", line 361, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'
```
### Steps to Reproduce
run `./run.sh` in `dev` branch

### Other Information
OS: Ubuntu
Git Commit: c11af09b64df4be77257207dfd147649489c776e

**Comment by banksymate** [comment] 2016-07-28 21:25
I'm getting the same.
`Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/root/pgo/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/root/pgo/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items_worker.py", line 14, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/root/pgo/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 361, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'
`

**Comment by d0t1q** [comment] 2016-07-28 21:25
I can confirm and replicate this issue

./pokecli.py -cf conf.json 
[21:24:04] PokemonGO Bot v1.0
[21:24:04] Configuration initialized
[21:24:04] [x] Coordinates found in passed in location, not geocoding.
[21:24:04]
[21:24:04] Location Found: **
[21:24:04] GeoPosition: (**)
[21:24:04]
[21:24:04] Attempting login to Pokemon Go.
[21:24:05] Login to Pokemon Go successful.
Traceback (most recent call last):
  File "./pokecli.py", line 357, in <module>
    main()
  File "./pokecli.py", line 62, in main
    bot.start()
  File "/var/www/PokemonGo-Bot/pokemongo_bot/__init__.py", line 44, in start
    self._setup_api()
  File "/var/www/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in _setup_api
    self._print_character_info()
  File "/var/www/PokemonGo-Bot/pokemongo_bot/__init__.py", line 265, in _print_character_info
    items_stock = self.current_inventory()
  File "/var/www/PokemonGo-Bot/pokemongo_bot/__init__.py", line 335, in current_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'

**Comment by banksymate** [comment] 2016-07-28 21:25
May be an issue with Pokemon GO servers.

**Comment by randypfohl** [comment] 2016-07-28 21:26
Yes this issue was hit and miss, as the servers went up and down. 

Lets wait until they are stable before we start investigating too much.

**Comment by ramponee** [comment] 2016-07-28 21:27
Can confirm, running bot exits wirh map_cells, and after restart GET_INVENTORY. Oh well, servers were really unstable today ;)

**Comment by ayiire** [comment] 2016-07-28 21:30
Servers have been going up and down all day so the API can't return any info.

**Comment by pickerflicker** [comment] 2016-07-28 21:34
I was able to login with the actual app though... I hope they didn't change the inventory API

**Comment by d0t1q** [comment] 2016-07-28 21:35
Not sure about that, this only happened after I ran a pull request, and another account of mine running via the main branch is running fine.  

And this commit did have a change to the __init__.py file 

https://github.com/PokemonGoF/PokemonGo-Bot/commit/c11af09b64df4be77257207dfd147649489c776e

**Comment by A7F** [comment] 2016-07-28 21:35
same issue here, I think the problem is server related, too but maybe they changed something... so the bot cn't parse correctly inventory infos.
btw i'm just guessing....

**Comment by banksymate** [comment] 2016-07-28 21:36
Maybe they're starting to block API requests that aren't using the "random bytes"
https://www.reddit.com/r/pokemongodev/comments/4tzgbw/anyone_knowing_more_about_the_infamous_unknown/

**Comment by incizzle** [comment] 2016-07-28 21:38
Severs are unstable rn thats it dont worry guys

**Comment by banksymate** [comment] 2016-07-28 21:41
Seems that swapping line #234 and #237 gets it a little further for me.
I now get this
`Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/root/pgo/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/root/pgo/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items_worker.py", line 14, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/root/pgo/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 361, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'
`

**Comment by aTadTasty** [comment] 2016-07-28 21:44
it's a server instability issue. this has been happening on both google accounts and ptc accounts

**Comment by skartoffel** [comment] 2016-07-28 21:46
Well since I can get my inventory when I am logged in in the actual application I wonder why the bot has this errors :(

**Comment by Dunduro** [comment] 2016-07-28 21:48
ya same here @skartoffel works on iphone just fine aswel ass on bluestacks android emulator

**Comment by Marco208** [comment] 2016-07-28 21:48
[23:48:24] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/web/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/web/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_transfer_worker.py", line 18, in work
    pokemon_groups = self._release_pokemon_get_groups()
  File "/web/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_transfer_worker.py", line 73, in _release_pokemon_get_groups
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'

My log

**Comment by Kujawadl** [comment] 2016-07-28 21:50
Not sure if this is related, maybe someone can confirm:

My inventory was full. I opened the app, cleared some things out, set stricter limits in config.json, and then removed data/cells-[username].json before restarting.

It works for me now, though that could be coincidence. Need someone to confirm.

**Comment by skartoffel** [comment] 2016-07-28 21:53
Inventory was not full, deleting cells-username.json did nothing :(

**Comment by pickerflicker** [comment] 2016-07-28 21:53
my inventory is NOT full.  Still encountering this problem with the bot. Able to login to the game on my phone.

**Comment by Kujawadl** [comment] 2016-07-28 21:56
Also, not only did it work on my phone while the bot was failing, but I have a second bot for my brother's account that is working just fine, so I think it's unlikely to be a server problem.

**Comment by A7F** [comment] 2016-07-28 21:58
@Kujawadl are the same bots? I mean, same bots with same commits?

**Comment by Dunduro** [comment] 2016-07-28 21:59
@A7F i was running 2 bots aswel and 1 failed a good 20-30 minutes before the other one, running on same install just different screen sessions

**Comment by Kujawadl** [comment] 2016-07-28 21:59
@A7F Yes, same commits. His has been running several hours now without problems, mine crashes immediately after login. 

Running on different screen sessions like @Dunduro

**Comment by A7F** [comment] 2016-07-28 22:02
just tried to revert my pull using
`git reset HEAD@{1} `
result: same crash but displays me my player infos (those printed in light blue)

**Comment by iceycake** [comment] 2016-07-28 22:03
master branch works fine while dev branch has this issue.

**Comment by DL0dz** [comment] 2016-07-28 22:03
I'm running the code since many days on the old 6e99169 (dev branch). For the first time today I encountered the Inventory Error.

**Comment by klingan** [comment] 2016-07-28 22:05
crashes now and then with this error, correct behavior would be to catch the exception and retry the login procedure

**Comment by Kassadd** [comment] 2016-07-28 22:15
Maybe the bug is the API itself and not in the bot:

```
2016-07-28 18:11:12,352 [   rpc_api] [DEBUG] Execution of RPC
2016-07-28 18:11:12,353 [connectionpool] [ INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-28 18:11:12,505 [connectionpool] [DEBUG] "POST /plfe/263/rpc HTTP/1.1" 200 2
2016-07-28 18:11:12,506 [   rpc_api] [DEBUG] Parsing main RPC response...
2016-07-28 18:11:12,506 [   rpc_api] [DEBUG] Protobuf structure of rpc response:
status_code: 52

2016-07-28 18:11:12,512 [   rpc_api] [DEBUG] Decode raw over protoc (protoc has to be in your PATH):
1: 52

2016-07-28 18:11:12,512 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-07-28 18:11:12,512 [    pgoapi] [ INFO] Cleanup of request!
code raw over protoc (protoc has to be in your PATH):
1: 52

2016-07-28 18:11:12,512 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-07-28 18:11:12,512 [    pgoapi] [ INFO] Cleanup of request!

```

**Comment by SethCalkins** [comment] 2016-07-28 22:16
# First Error

```sh
[18:09:20] Attempting login to Pokemon Go.
[18:09:20] Login to Pokemon Go successful.
[18:09:21]
[18:09:21] --- MYUSERNAME ---
[18:09:21] Level: 21 (Next Level: 48290 XP) (Total: 286710 XP)
[18:09:21] Pokemon Captured: 915 | Pokestops Visited: 504
[18:09:21] Pokemon Bag: 177/250
[18:09:21] Items: 204/350
[18:09:21] Stardust: 2011 | Pokecoins: 0
[18:09:21] PokeBalls: 46 | GreatBalls: 50 | UltraBalls: 10
[18:09:21] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
[18:09:21] LuckyEgg: 0 | Incubator: 2 | TroyDisk: 5
[18:09:21] Potion: 10 | SuperPotion: 25 | HyperPotion: 25
[18:09:21] Incense: 4 | IncenseSpicy: 0 | IncenseCool: 0
[18:09:21] Revive: 25 | MaxRevive: 0
[18:09:21]
[18:09:21]
[18:09:21] Starting PokemonGo Bot....
[18:09:22] Releasing Oddish with CP 236 and IV 0.62. Matching release rule: CP < 400 AND IV < 0.8.
[18:09:22] Exchanging Oddish [CP 236] [Potential 0.62] for candy!
[18:09:24] Scanning area for objects....
[18:09:24] Walking from (51.990094618072625, -89.93739658544594) to [51.990094618072625, -89.93739658544594] 0.00km

[18:09:24] Releasing Oddish with CP 236 and IV 0.62. Matching release rule: CP < 400 AND IV < 0.8.
[18:09:24] Exchanging Oddish [CP 236] [Potential 0.62] for candy!
[18:09:27] [x] Found fort 3769a62d5ffa43ad88cd2954d628cdba.16 at distance 0.36km
[18:09:27] [x] Need to move closer to Pokestop
[18:09:29] [x] Found fort 3769a62d5ffa43ad88cd2954d628cdba.16 at distance 0.36km
[18:09:29] [x] Need to move closer to Pokestop
[18:09:31] [x] Found fort 3769a62d5ffa43ad88cd2954d628cdba.16 at distance 0.36km
[18:09:31] [x] Need to move closer to Pokestop
[18:09:33] [x] Found fort 3769a62d5ffa43ad88cd2954d628cdba.16 at distance 0.35km
[18:09:33] [x] Need to move closer to Pokestop
[18:09:36] [x] Found fort 3769a62d5ffa43ad88cd2954d628cdba.16 at distance 0.35km
[18:09:36] [x] Need to move closer to Pokestop
[18:09:38] [x] Found fort 3769a62d5ffa43ad88cd2954d628cdba.16 at distance 0.34km
[18:09:38] [x] Need to move closer to Pokestop
````
 ```python
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/spin_nearest_fort_worker.py", line 24, in work
    if MoveToFortWorker(nearest_fort, self.bot).work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "/root/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 466, in heartbeat
    self.update_web_location() # updates every tick
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 112, in update_web_location
    cells = map_objects['map_cells']
KeyError: 'map_cells'
```

# Second Error

```sh
[18:08:14] --- MYUSERNAME ---
[18:08:14] Level: 21 (Next Level: 48290 XP) (Total: 286710 XP)
[18:08:14] Pokemon Captured: 915 | Pokestops Visited: 504
[18:08:14] Pokemon Bag: 193/250
[18:08:14] Items: 272/350
[18:08:14] Stardust: 2011 | Pokecoins: 0
[18:08:14] PokeBalls: 46 | GreatBalls: 101 | UltraBalls: 10
[18:08:14] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
[18:08:14] LuckyEgg: 0 | Incubator: 2 | TroyDisk: 5
[18:08:14] Potion: 12 | SuperPotion: 30 | HyperPotion: 30
[18:08:14] Incense: 4 | IncenseSpicy: 0 | IncenseCool: 0
[18:08:14] Revive: 30 | MaxRevive: 0
[18:08:14]
[18:08:14]
[18:08:14] Starting PokemonGo Bot....
[18:08:15] Releasing Oddish with CP 236 and IV 0.62. Matching release rule: CP < 400 AND IV < 0.8.
[18:08:15] Exchanging Oddish [CP 236] [Potential 0.62] for candy!
[18:08:18] Releasing Pidgey with CP 227 and IV 0.4. Matching release rule: CP < 237 AND IV < 0.8.
[18:08:18] Exchanging Pidgey [CP 227] [Potential 0.4] for candy!
[18:08:21] Releasing Pidgey with CP 213 and IV 0.76. Matching release rule: CP < 237 AND IV < 0.8.
[18:08:21] Exchanging Pidgey [CP 213] [Potential 0.76] for candy!
[18:08:25] Releasing Pidgey with CP 206 and IV 0.38. Matching release rule: CP < 237 AND IV < 0.8.
[18:08:25] Exchanging Pidgey [CP 206] [Potential 0.38] for candy!
[18:08:27] Releasing Pidgeotto with CP 405 and IV 0.51. Matching release rule: CP < 427 AND IV < 0.8.
[18:08:27] Exchanging Pidgeotto [CP 405] [Potential 0.51] for candy!
[18:08:29] Releasing Pidgeotto with CP 348 and IV 0.58. Matching release rule: CP < 427 AND IV < 0.8.
[18:08:29] Exchanging Pidgeotto [CP 348] [Potential 0.58] for candy!
[18:08:33] Releasing Pidgeot with CP 590 and IV 0.38. Matching release rule: CP < 729 AND IV < 0.8.
[18:08:33] Exchanging Pidgeot [CP 590] [Potential 0.38] for candy!
[18:08:36] Releasing Pidgeot with CP 309 and IV 0.31. Matching release rule: CP < 729 AND IV < 0.8.
[18:08:36] Exchanging Pidgeot [CP 309] [Potential 0.31] for candy!
[18:08:38] Releasing Rattata with CP 70 and IV 0.73. Matching release rule: CP < 204 AND IV < 0.8.
[18:08:38] Exchanging Rattata [CP 70] [Potential 0.73] for candy!
[18:08:41] Releasing Zubat with CP 221 and IV 0.42. Matching release rule: CP < 225 AND IV < 0.8.
[18:08:41] Exchanging Zubat [CP 221] [Potential 0.42] for candy!
[18:08:44] Releasing Venonat with CP 250 and IV 0.76. Matching release rule: CP < 360 AND IV < 0.8.
[18:08:44] Exchanging Venonat [CP 250] [Potential 0.76] for candy!
[18:08:47] Releasing Venonat with CP 244 and IV 0.64. Matching release rule: CP < 360 AND IV < 0.8.
[18:08:47] Exchanging Venonat [CP 244] [Potential 0.64] for candy!
[18:08:50] Releasing Venonat with CP 218 and IV 0.69. Matching release rule: CP < 360 AND IV < 0.8.
[18:08:50] Exchanging Venonat [CP 218] [Potential 0.69] for candy!
[18:08:52] Releasing Venomoth with CP 290 and IV 0.53. Matching release rule: CP < 660 AND IV < 0.8.
[18:08:52] Exchanging Venomoth [CP 290] [Potential 0.53] for candy!
[18:08:53] Releasing Bellsprout with CP 359 and IV 0.71. Matching release rule: CP < 391 AND IV < 0.8.
[18:08:53] Exchanging Bellsprout [CP 359] [Potential 0.71] for candy!
[18:08:57] Releasing Drowzee with CP 249 and IV 0.42. Matching release rule: CP < 374 AND IV < 0.8.
[18:08:57] Exchanging Drowzee [CP 249] [Potential 0.42] for candy!
[18:09:01] Releasing Exeggcute with CP 207 and IV 0.78. Matching release rule: CP < 384 AND IV < 0.8.
[18:09:01] Exchanging Exeggcute [CP 207] [Potential 0.78] for candy!
[18:09:05] -- Recycled 51x Greatball (keeps only 50 maximum)
[18:09:06] -- Recycled 5x Hyper Potion (keeps only 25 maximum)
[18:09:06] -- Recycled 5x Revive (keeps only 25 maximum)
[18:09:06] -- Recycled 5x Super Potion (keeps only 25 maximum)
[18:09:07] -- Recycled 2x Potion (keeps only 10 maximum)
[18:09:07] Scanning area for objects....
[18:09:07] Walking from (51.990094618072625, -89.93739658544594) to [51.990094618072625, -89.93739658544594] 0.00km
```
```python
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_transfer_worker.py", line 18, in work
    pokemon_groups = self._release_pokemon_get_groups()
  File "/root/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_transfer_worker.py", line 73, in _release_pokemon_get_groups
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'
```

**Comment by Sekunde** [comment] 2016-07-28 22:23
In master branch, it has the same error, but recover soon. 

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'
[2016-07-28 22:22:14] [x] PokemonGO Bot v1.0
[2016-07-28 22:22:14] [x] Configuration initialized
[2016-07-28 22:22:14]
[2016-07-28 22:22:14] [x] Address found:
[2016-07-28 22:22:14] [x] Position in-

**Comment by SethCalkins** [comment] 2016-07-28 22:31
perhaps this is it...
    UnboundLocalError: local variable 'player' referenced before assignment

**Comment by Ced4** [comment] 2016-07-28 22:32
the newest commit ec2b7add95da6bc580035d8d4c472c1d41e439a6 fixes it.. somehow xD

> [18:30:59] Server seems to be busy or offline - try again - 1/5
> [18:31:03] [x] Found fort xxx.11 at distance 0.07km
> [18:31:03] [x] Need to move closer to Pokestop
> [18:31:04] Server seems to be busy or offline - try again - 1/5
> [18:31:08] [x] Found fort xxx.11 at distance 0.07km
> [18:31:08] [x] Need to move closer to Pokestop
> [18:31:09] Server seems to be busy or offline - try again - 1/5
> [18:31:12] [x] Found fort xxx.11 at distance 0.06km
> [18:31:12] [x] Need to move closer to Pokestop
> [18:31:13] Server seems to be busy or offline - try again - 1/5
> [18:31:17] [x] Found fort xxx.11 at distance 0.06km
> [18:31:17] [x] Need to move closer to Pokestop

but the bot is walking and catching pokemon!

**Comment by iceycake** [comment] 2016-07-28 22:32
Just pull the latest dev branch, with the retry this problem is better.

**Comment by SethCalkins** [comment] 2016-07-28 22:35
[18:35:16] Level: 21 (Next Level: 48290 XP) (Total: 286710 XP)
	[18:35:16] Pokemon Captured: 915 | Pokestops Visited: 504
	[18:35:16] Pokemon Bag: 176/250
	[18:35:16] Items: 204/350
	[18:35:16] Stardust: 2011 | Pokecoins: 0
	[18:35:16] PokeBalls: 46 | GreatBalls: 50 | UltraBalls: 10
	[18:35:16] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
	[18:35:16] LuckyEgg: 0 | Incubator: 2 | TroyDisk: 5
	[18:35:16] Potion: 10 | SuperPotion: 25 | HyperPotion: 25
	[18:35:16] Incense: 4 | IncenseSpicy: 0 | IncenseCool: 0
	[18:35:16] Revive: 25 | MaxRevive: 0
	[18:35:16]
	[18:35:16]
	[18:35:17] Server seems to be busy or offline - try again - 1/5
	[18:35:18] Starting PokemonGo Bot....
	[18:35:18] [x] Found fort 3763a62d5ffa43ad88cd2954d628cdba.16 at distance 0.32km
	[18:35:18] [x] Need to move closer to Pokestop
	[18:35:19] Server seems to be busy or offline - try again - 1/5
	[18:35:22] [x] Found fort 3763a62d5ffa43ad88cd2954d628cdba.16 at distance 0.32km
	[18:35:22] [x] Need to move closer to Pokestop
	[18:35:22] Server seems to be busy or offline - try again - 1/5

**Comment by Dunduro** [comment] 2016-07-28 22:36
after the pulling commit 47cf9db seems to be working fine now

**Comment by snorlaxrazzi** [comment] 2016-07-28 23:08
Same issue as original poster

**Comment by ddrght12345** [comment] 2016-07-28 23:12
Will confirm. 47cf9db53d986f78cf0cce8a2c6aa5863c29a7c8 is a quick bandaid for this issue

**Comment by d0t1q** [comment] 2016-07-28 23:16
Yup https://github.com/PokemonGoF/PokemonGo-Bot/commit/47cf9db53d986f78cf0cce8a2c6aa5863c29a7c8 fixes this, deffintly something with the newly added api_wrapper(since it was the only change)
Totally a server issue right?/s

**Comment by th3w4y** [comment] 2016-07-28 23:20
I also get same issue


In [5]: bot.get_inventory()
Out[5]: {'responses': {}, 'status_code': 52}

In [6]:

**Comment by inexion** [comment] 2016-07-29 04:36
pretty sure this error only occurs because people have:

- started an account
- let the bot roam in a specific location
- shut down the bot
- changed the config in an attempt to spoof a location nowhere near the first location

**Comment by javiermar** [comment] 2016-07-29 06:13
I can confirm inexion's theory. New account worked on head of master branch. 

There should be a distance check in the algorithm to prevent teleporting. I'd help, but I can't python.

**Comment by asiletto** [comment] 2016-07-29 08:32
I tested with a new account and I get the same error.

I tested it from an aws server, maybe if inexion theory is correct there is also an ip range block?

**Comment by tstumm** [comment] 2016-07-29 10:30
Should be fixed in latest `dev`

**Closed by tstumm** 2016-07-29 10:30 UTC
Labels: bug, help wanted
