### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by otanriverdi** [PokemonGoF/PokemonGo-Bot#2743] opened 2016-08-07 10:12 UTC
Hey guys,

Does anyone have a solution to this ?

### Expected Behavior

bot to work

### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 3: ordinal not in range(128)

### Steps to Reproduce

python pokecli.py

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Jojo1910** [comment] 2016-08-07 10:22
Same here

OS: linux debian
Git Commit: e93431c3492e3c44414a540a746e6ba570865564
Python Version: 2.7

**Comment by elhanarinc** [comment] 2016-08-07 10:28
Same here

**Comment by Corecrafts** [comment] 2016-08-07 10:32
aye, same

**Comment by Philipp59** [comment] 2016-08-07 10:37
duplicate of  #2718
maybe fixed with #2720

**Comment by Corecrafts** [comment] 2016-08-07 10:42
merged, same issue @Philipp59

**Comment by jelix99** [comment] 2016-08-07 10:48
did a pull on the merged code, but still got the same (or kinda the same) error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 05:46:32,325 [sentry.errors.uncaught] [ERROR] [u'OSError: dlopen(encrypt.so, 6): image not found', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 443, in LoadLibrary', u'  File "ctypes/__init__.py", line 365, in __init__']

Any help ?

**Comment by brumie** [comment] 2016-08-07 10:48
confirm same error

**Comment by Sijmenjeromkok** [comment] 2016-08-07 10:48
+ Same error

**Comment by cliffalbert** [comment] 2016-08-07 10:54
The decryption library is not present in your install. It has to be hand-installed. It's not part of the git repository.

**Comment by jelix99** [comment] 2016-08-07 10:58
Thanks for the info, Any link on where i can get the decryption library?

**Comment by brumie** [comment] 2016-08-07 11:25
thanks @cliffalbert forgot to move from src to pogobot folder

**Comment by brumie** [comment] 2016-08-07 11:26
@jelix99 https://github.com/PokemonGoF/PokemonGo-Bot/issues/2642

**Comment by inzaghi89** [comment] 2016-08-07 11:31
@brumie tried this, downloaded encrypt.so, put it into main Pokemongo directory, still same issue...

  File "/home/inzaghi89/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 13:30:55,561 [sentry.errors.uncaught] [ERROR] [u'OSError: encrypt.so: cannot open shared object file: No such file or directory', u'  File "pokecli.py", line 501, in <module>', u'  File "pokecli.py", line 130, in main', u'  File "pokecli.py", line 139, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 435, in LoadLibrary', u'  File "ctypes/__init__.py", line 357, in __init__']

**Comment by inzaghi89** [comment] 2016-08-07 11:40
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2769#issuecomment-238077548 this solve my problem.

**Closed** 2016-08-11 04:16 UTC
