### ISSUE TITLE
Bot uses Razzberries excessively

### ISSUE THREAD

**Issue by wsmigielski** [PokemonGoF/PokemonGo-Bot#1845] opened 2016-07-30 13:02 UTC
### Expected Behavior
Only use Razzberries to capture Pokemon hard to catch, not the common types. 

### Actual Behavior
Uses Razzberries for all Pokemon even common types like Zubat, Pidgey. Which wastes it.

### Steps to Reproduce
Just let bot run and observe 

### Other Information
My suggestion is to add the possibility to configure when the bot uses raspberries and for what Pokemon. 

OS: Linux Ubuntu. Git Commit: 434cb3a38da9675d304f5b916b1a235be6cb7ed4

**Comment by Donwulff** [comment] 2016-07-30 22:11
Kinda duplicate of my #1755 though now it seems both of these were addressed in #1807

**Closed** 2016-07-31 07:29 UTC
