### ISSUE TITLE
Bot no staying around first coordinate

### ISSUE THREAD

**Issue by orchid666** [PokemonGoF/PokemonGo-Bot#3633] opened 2016-08-11 17:13 UTC
### Expected Behavior

Id like my bot to stay within let's say a circle of X km.

### Actual Behavior

Bot keeps roaming all over the city

### Your config.json (remove your credentials and any other private info)
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
		  "type": "FollowCluster",
		  "config": {
		  "radius": 0.6,
		  "lured": true
        }
      }

**Comment by joaodragao** [comment] 2016-08-11 17:38
@orchid666 I think you the `radius` value is too low. Try `20` or so.

**Comment by orchid666** [comment] 2016-08-11 17:42
I tried many radius values, including big ones and it wont change anything, I dont see why increasing the radius would make my bot stay within a certain area

**Comment by ripzery** [comment] 2016-08-11 17:44
What is the unit of radius value? km or metre?

**Comment by joaodragao** [comment] 2016-08-11 17:44
Because in the code, the default value is `50`. and it is checked with `find_biggest_cluster` function also.

**Comment by joaodragao** [comment] 2016-08-11 17:45
@rpzery I think it's `km`.

**Comment by ripzery** [comment] 2016-08-11 17:46
Is radius 1 km work?

**Comment by orchid666** [comment] 2016-08-11 17:48
Nope, I wonder if those values use the updated location as reference and not the very first coordinate.

**Comment by joaodragao** [comment] 2016-08-11 18:03
@ripzery I'll test it.

**Comment by orchid666** [comment] 2016-08-11 18:04
@joaodragao @ripzery That was my previous value before i tried 0.6. Same outcome.

**Comment by DiegoRBaquero** [comment] 2016-08-11 18:08
I'm just going to point out that the cluster example config does not have MoveToFort task. Maybe try removing it?

**Comment by joaodragao** [comment] 2016-08-11 18:29
@orchid666 What @DiegoRBaquero said may be correct.

**Comment by DiegoRBaquero** [comment] 2016-08-11 18:33
I tested the cluster config (no MoveToFort) and it stays in the same position. Also, it seems the radius is in meters. `[13:27:46] Arrived at cluster. 1 are in a range of 500m radius.` (I have the setting in 500)

**Comment by orchid666** [comment] 2016-08-11 18:36
That is some very useful information Diego. Thanks!

**Comment by orchid666** [comment] 2016-08-11 18:48
Well i dont think its possible to stay within the same area. Removing Movetofort logically prevent the bot to move to the next fort. Everything seems to be calculated according to current coordinates and not very first coordinates.

**Comment by DiegoRBaquero** [comment] 2016-08-11 19:30
@orchid666 It does move when required but it stays in the best possible cluster of lured forts. The radius is relative to current location, not initial coords.

**Comment by orchid666** [comment] 2016-08-11 19:38
Yes, thats what i said, there is currently no way to have the bot stay within a fixed area.

**Comment by DiegoRBaquero** [comment] 2016-08-11 19:55
You could use the path config

**Comment by orchid666** [comment] 2016-08-11 21:05
True, but that would make my bot go from point A to point B then get point B Fort and thats it.
Basically, I just want to make my bot stay in a park and explore all the  Forts there, because parks are usually very dense places. I could set a path config with every fort out there but that would take days to copy all coordinates...

**Comment by DiegoRBaquero** [comment] 2016-08-11 21:07
You can use Google maps

**Comment by orchid666** [comment] 2016-08-11 21:13
What do you mean i could use google maps? Im using google maps, im just saying that there are so many coordinates that it would take days to copy them all

**Comment by orchid666** [comment] 2016-08-11 21:14
Maybe i should make a pull request for that feature? :)

**Comment by RedViper9** [comment] 2016-08-11 22:37
You can do this to some extent if you use the MoveToMapPokemon option with "update_map": false,. Your bot's location won't get pushed to the map and you can drop the pin wherever you want the bot to go. It will still nab any pokemon on the way, and spin forts, but will stay in the general area of your pin. Area can be manipulated using the number of steps that the map searches.

**Comment by orchid666** [comment] 2016-08-12 01:37
@RedViper9  Thanks for the suggestion, but im kind of new, is there any doc available about that?

**Comment by k4n30** [comment] 2016-08-14 14:14
Duplicate of #3580

**Closed by k4n30** 2016-08-14 14:14 UTC
Labels: duplicate
