### ISSUE TITLE
Seems to be issues with the bot running over lengthy periods of time

### ISSUE THREAD

**Issue by vanZeben** [PokemonGoF/PokemonGo-Bot#643] opened 2016-07-24 10:39 UTC
I have the bot running on my VPS and decided to leave it on while I went to sleep. I woke up to the bot just scanning the area and then walking to the next area. No pokestops, no pokemon, just walking around. Judging from the level of my character and bag changes, this happened not very long after I left the bot alone (perhaps 20-30 minutes), so I would estimate that this kicks in around an hour or so of uptime total if not less. 

This is the second time this has happened, and while not a huge issue to just force restart the script after 30 minutes, perhaps this should be looked into further.

### Behaviour
http://pastebin.com/raw/vjZMDAFZ

**Comment by DanielVolz** [comment] 2016-07-24 10:46
Have the same problem.

**Comment by AnakTeka** [comment] 2016-07-24 10:49
Yeah, same here, I have to restart the process once in a while.

**Comment by Spettacolo83** [comment] 2016-07-24 10:53
Same problem here! I have to restart every 30-60 mins.

**Comment by LuyiTian** [comment] 2016-07-24 11:07
Have the similar problem. keep printout unknown pokestop and do nothing.

```
[2016-07-24 21:10:43] [#] Finished walking
[2016-07-24 21:10:43] [#] Arrived at Pokestop
2016-07-24 21:10:47 [#] Now at Pokestop: Unknown - Spinning...
[2016-07-24 21:10:57] [#] Found fort 14b615d60dee42bb9e1a83041adc232a.11 at distance 0.90km
```

**Comment by J102030** [comment] 2016-07-24 12:51
Yep, same here - can run the bot for ~2 hours before getting stuck

**Comment by bgrimm** [comment] 2016-07-24 13:17
Same issue, starts not finding just moving around about the 30-45 minute mark as well.

**Comment by hklcf** [comment] 2016-07-24 14:52
same here

**Comment by JohanJu** [comment] 2016-07-24 17:07
It seems to continue working for me if i press enter. Maybe it doesn't wake up from sleep. 
Can you say what OS you are on, maybe it's scheduler issue?

**Comment by vanZeben** [comment] 2016-07-24 17:22
@JohanJu OS seems to be irrelevant on this. I've run it on CentOS/OSX/Windows and all yield the same result..

Also note that some people are claiming duplicates of this, but I dont think they are quite the same. Alot of the "duplicates" are people actually finding the pokestops and it just walking between them without collecting anything. This one it doesnt even find the pokestops, it just searches cell blocks and finds nothing indefinitely

**Comment by JohanJu** [comment] 2016-07-24 17:25
@vanZeben You are right, I got another bug where the bot just stops and a enter press woke it up.

**Comment by surfaace** [comment] 2016-07-24 23:34
maybe fixed in #701 , please confirm

**Comment by hklcf** [comment] 2016-07-25 03:35
tested on my server 

![default](https://cloud.githubusercontent.com/assets/410302/17089704/ccfd202a-525b-11e6-823a-d851e7c77845.png)

55adefeeb580ed8bb51d097e56a506e2973377c9

**Comment by leadboots5** [comment] 2016-07-25 07:09
I get the same things as @hklcf after about a hour with google. Seems to go longer with PTC, but I need to verify that.

**Comment by SteffanLong** [comment] 2016-07-25 07:28
The issue is with the authentication token not getting refreshed. We're aware and it will be fixed. :)

**Comment by surfaace** [comment] 2016-07-25 07:31
#532

**Comment by L3nderSson** [comment] 2016-07-25 09:29
Is this problem fixed already? I got it three times the last 3 Hours :-(

**Comment by hklcf** [comment] 2016-07-25 09:50
@L3nderSson seem work fine for me.

**Comment by L3nderSson** [comment] 2016-07-25 09:54
You changed something? Or just an Update?

**Comment by hklcf** [comment] 2016-07-25 09:55
@L3nderSson im using fb2cca3b1f701653d58424f49a2ba7fae5cd97e9

**Comment by dmateusp** [comment] 2016-07-25 09:56
A change corrected a wrong behavior (teleporting to pokestops causing softban), that now should be fixed.

**Comment by hklcf** [comment] 2016-07-25 09:59
work fine on lastest master and dev branch

**Comment by L3nderSson** [comment] 2016-07-25 10:07
Hm okay I updated after this three times one hour ago, So normally It must work

**Comment by dmateusp** [comment] 2016-07-25 10:09
@L3nderSson the change that fixed it was made 20-30mins ago

**Comment by L3nderSson** [comment] 2016-07-25 10:11
Oh damn thanks! So I will update later when I'll come home. Thanks guys for your help, I'm absolutly new ✌🏾️

**Comment by dmateusp** [comment] 2016-07-25 10:13
Just comment here once you update so we know if it's fixed :) @L3nderSson

**Comment by L3nderSson** [comment] 2016-07-25 10:19
Yes I will! Ehm and by the way, the right way for Update ist git pull and then the Python install require or Is that the wrong way?

**Comment by L3nderSson** [comment] 2016-07-25 10:20
I ask cause my cmd said: " please commit your changes or stash them before you can merge. Aborting"

**Comment by dmateusp** [comment] 2016-07-25 11:42
@L3nderSson most of the times you won't have to install again, just commit your changes and then pull from the branch. Then it will list the merging issues

**Comment by guyz** [comment] 2016-07-25 12:59
Running latest dev branch. Problem persists. After 20-30 minutes this happens.

**Comment by jaerak** [comment] 2016-07-25 14:34
While we wait for a commit on this to come through, maybe a batch file (for windows at least) that closes/reruns the script every hour would work?

**Comment by L3nderSson** [comment] 2016-07-25 19:22
I didnt have it no more, now I have the problem with scanning area for objects :D

**Comment by surfaace** [comment] 2016-07-25 22:11
pullrequest #735

**Closed by surfaace** 2016-07-25 22:11 UTC
Labels: bug
