### ISSUE TITLE
move_to_map_pokemon.py was broken in the last 24 hrs 

### ISSUE THREAD

**Issue by MasterCATZ** [PokemonGoF/PokemonGo-Bot#4124] opened 2016-08-16 23:01 UTC
I just did a dev pull this morning and now I get this issue when using 
"type": "MoveToMapPokemon",

I have yet to switch to the new walk speed Min/Max settings,but doubt that is the issue 

also pulled latest  PokemonGo-Map after this error 

Traceback (most recent call last):
  File "pokecli.py", line 626, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "/DATA/PokemonGo-Bot/pokemongo_bot/__init__.py", line 498, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/DATA/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 248, in work
    pokemon_list = self.get_pokemon_from_map()
  File "/DATA/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 147, in get_pokemon_from_map
    if pokemon['dist'] > ((pokemon['expire'] - now) * mean_walk_speed) and not self.config['snipe']:
KeyError: 'expire'
2016-08-17 00:12:46,012 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-17 00:12:46,017 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'expire'", u'  File "pokecli.py", line 626, in <module>', u'  File "pokecli.py", line 104, in main', u'  File "pokemongo_bot/__init__.py", line 498, in tick', u'  File "pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 248, in work', u'  File "pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 147, in get_pokemon_from_map']

**Comment by Gurzeh** [comment] 2016-08-16 23:17
Same for me.
config is http://pastebin.com/JTUPEe98
call pile is http://pastebin.com/nQPhRc8V

**Comment by k4n30** [comment] 2016-08-17 03:33
#4115

**Comment by k4n30** [comment] 2016-08-17 03:38
Duplicate of #4113

**Closed by k4n30** 2016-08-17 03:38 UTC
Labels: Duplicate, Waiting on Merge
