### ISSUE TITLE
Bot Transferred my high level Pokemon when bags got full.... :( on master

### ISSUE THREAD

**Issue by josephmcox** [PokemonGoF/PokemonGo-Bot#1516] opened 2016-07-29 00:08 UTC
### Expected Behavior

Follow transfer rules. I had set it to not transfer anything above 0 cp.

Bot output:
[left out] [x] Pokemon Bag is full!
[left out] [x] Initial Transfer.
[left out] [x] Preparing to transfer all duplicate Pokemon, keeping the highest CP of each type.
[left out] [x] Will NOT transfer anything above CP 0
[x] Transferring Magikarp with CP 108
[x] Transferring Magikarp with CP 103
[x] Transferring Magikarp with CP 100
[x] Transferring Eevee with CP 669
[x] Transferring Eevee with CP 609
[x] Transferring Eevee with CP 576
[x] Transferring Eevee with CP 572
[x] Transferring Eevee with CP 567
[x] Transferring Eevee with CP 528
[x] Transferring Eevee with CP 490
[x] Transferring Eevee with CP 485
[x] Transferring Eevee with CP 473
[x] Transferring Eevee with CP 438
[x] Transferring Eevee with CP 358
[x] Transferring Eevee with CP 241
[x] Transferring Eevee with CP 78
[x] Transferring Eevee with CP 14
[x] Transferring Vaporeon with CP 1791
[x] Transferring Vaporeon with CP 1713
[x] Transferring Caterpie with CP 240
[x] Transferring Caterpie with CP 160
[x] Transferring Caterpie with CP 157
[x] Transferring Caterpie with CP 134
[x] Transferring Caterpie with CP 126
[x] Transferring Caterpie with CP 117
[x] Transferring Caterpie with CP 86
[x] Transferring Caterpie with CP 73
[x] Transferring Caterpie with CP 56
[x] Transferring Caterpie with CP 53
[x] Transferring Caterpie with CP 34
[x] Transferring Caterpie with CP 23
[x] Transferring Caterpie with CP 14
[x] Transferring Caterpie with CP 10
[x] Transferring Weedle with CP 179
[x] Transferring Weedle with CP 175
[x] Transferring Weedle with CP 169
[x] Transferring Weedle with CP 158
[x] Transferring Weedle with CP 142
[x] Transferring Weedle with CP 127
[x] Transferring Weedle with CP 123
[x] Transferring Weedle with CP 120
[x] Transferring Weedle with CP 110
[x] Transferring Weedle with CP 100
[x] Transferring Weedle with CP 97
[x] Transferring Weedle with CP 92
[x] Transferring Weedle with CP 78
[x] Transferring Weedle with CP 74
[x] Transferring Weedle with CP 58
[x] Transferring Weedle with CP 37
[x] Transferring Weedle with CP 25
[x] Transferring Weedle with CP 24
[x] Transferring Weedle with CP 10
[x] Transferring Pidgey with CP 389
[x] Transferring Pidgey with CP 388
[x] Transferring Pidgey with CP 385
[x] Transferring Pidgey with CP 372
[x] Transferring Pidgey with CP 366
[x] Transferring Pidgey with CP 362
[x] Transferring Pidgey with CP 357
[x] Transferring Pidgey with CP 349
[x] Transferring Pidgey with CP 345
[x] Transferring Pidgey with CP 337
[x] Transferring Pidgey with CP 313
[x] Transferring Pidgey with CP 311
[x] Transferring Pidgey with CP 297
[x] Transferring Pidgey with CP 290
[x] Transferring Pidgey with CP 264
[x] Transferring Pidgey with CP 261
[x] Transferring Pidgey with CP 254
[x] Transferring Pidgey with CP 227
[x] Transferring Pidgey with CP 225
[x] Transferring Pidgey with CP 215
[x] Transferring Pidgey with CP 194
[x] Transferring Pidgey with CP 191
[x] Transferring Pidgey with CP 190
[x] Transferring Pidgey with CP 184
[x] Transferring Pidgey with CP 175
[x] Transferring Pidgey with CP 171
[x] Transferring Pidgey with CP 169
[x] Transferring Pidgey with CP 160
[x] Transferring Pidgey with CP 158
[x] Transferring Pidgey with CP 142
[x] Transferring Pidgey with CP 140
[x] Transferring Pidgey with CP 125
[x] Transferring Pidgey with CP 111
[x] Transferring Pidgey with CP 110
[x] Transferring Pidgey with CP 95
[x] Transferring Pidgey with CP 94
[x] Transferring Pidgey with CP 78
[x] Transferring Pidgey with CP 76
[x] Transferring Pidgey with CP 71
[x] Transferring Pidgey with CP 57
[x] Transferring Pidgey with CP 54
[x] Transferring Pidgey with CP 43
[x] Transferring Pidgey with CP 42
[x] Transferring Pidgey with CP 41
[x] Transferring Pidgey with CP 40
[x] Transferring Pidgey with CP 39
[x] Transferring Pidgey with CP 26
[x] Transferring Pidgey with CP 23
[x] Transferring Pidgey with CP 10
[x] Transferring Pidgeotto with CP 701
[x] Transferring Spearow with CP 406
[x] Transferring Spearow with CP 107
[x] Transferring Fearow with CP 911
[x] Transferring Pikachu with CP 259
[x] Transferring Nidoran F with CP 370
[x] Transferring Nidoran M with CP 351
[x] Transferring Nidoran M with CP 320
[x] Transferring Clefairy with CP 676
[x] Transferring Clefairy with CP 659
[x] Transferring Clefairy with CP 651
[x] Transferring Clefairy with CP 466
[x] Transferring Bulbasaur with CP 507
[x] Transferring Jigglypuff with CP 350
[x] Transferring Zubat with CP 395
[x] Transferring Zubat with CP 342
[x] Transferring Zubat with CP 320
[x] Transferring Zubat with CP 268
[x] Transferring Zubat with CP 251
[x] Transferring Zubat with CP 238
[x] Transferring Zubat with CP 225
[x] Transferring Oddish with CP 511
[x] Transferring Oddish with CP 454
[x] Transferring Paras with CP 589
[x] Transferring Paras with CP 568
[x] Transferring Paras with CP 344
[x] Transferring Venonat with CP 588
[x] Transferring Venonat with CP 494
[x] Transferring Venonat with CP 489
[x] Transferring Venonat with CP 485
[x] Transferring Venonat with CP 426
[x] Transferring Venonat with CP 43
[x] Transferring Venomoth with CP 1059
[x] Transferring Psyduck with CP 577
[x] Transferring Poliwag with CP 483
[x] Transferring Poliwag with CP 412
[x] Transferring Poliwag with CP 383
[x] Transferring Poliwag with CP 352
[x] Transferring Abra with CP 301
[x] Transferring Abra with CP 277
[x] Transferring Bellsprout with CP 698
[x] Transferring Bellsprout with CP 583
[x] Transferring Bellsprout with CP 461
[x] Transferring Bellsprout with CP 440
[x] Transferring Krabby with CP 345
[x] Transferring Exeggcute with CP 565
[x] Transferring Rhyhorn with CP 188
[x] Transferring Horsea with CP 372
[x] Transferring Pinsir with CP 900
[x] Transferring Pinsir with CP 883
[x] Transferring Pinsir with CP 795
[x] Transferring Pinsir with CP 773
[x] Transferring Pinsir with CP 346

### Actual Behavior

It transferred a lot of pokemon that it shouldn't have.

### Steps to Reproduce
Run bot until bag full and watch it transfer the good stuff :(

### Other Information
OS: Ubuntu
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by VictorChen** [comment] 2016-07-29 00:10
duplicate https://github.com/PokemonGoF/PokemonGo-Bot/issues/1448

**Comment by TheGoldenXY** [comment] 2016-07-29 18:30
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1448

/closed

**Closed by TheGoldenXY** 2016-07-29 18:30 UTC
