### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Mentaa** [PokemonGoF/PokemonGo-Bot#211] opened 2016-07-22 14:57 UTC
Hi first one thanks for the script and ur works,

I try to install the script/bot but i have a problem and i dont find how fix !

when i install with:

`pip install -r ./requirements.txt`

I have a error on the end:

`
```
Generating google/protobuf/pyext/python_pb2.py...

protoc is not installed nor found in ../src.  Please compile it or install the binary package.

----------------------------------------
Cleaning up...
Command D:\Python\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\Menta\\appdata\\local\\temp\\pip_build_Menta\\protobuf\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\Menta\appdata\local\temp\pip-crxac9-record\install-record.txt --single-version-externally-managed --compile failed with error code -1 in c:\users\Menta\appdata\local\temp\pip_build_Menta\protobuf
Storing debug log for failure in C:\Users\Menta\pip\pip.log 
```
`

My pip.log => http://pastebin.com/FWvrJNZ4

I try to launch with pokecly.py and i have the error:

```
D:\Python\PokemonGo-Bot-dev>pokecli.py -a ptc "***" "****" -l "New York, Washington Square" -w 5 -s
Traceback (most recent call last):
  File "D:\Python\PokemonGo-Bot-dev\pokecli.py", line 30, in <module>
    import requests
ImportError: No module named requests

D:\Python\PokemonGo-Bot-dev>

```

thanks a lot and sorry for my bad english.

Menta.

**Comment by Mentaa** [comment] 2016-07-22 15:21
I have fixed my first problem with pip, just installed new python 3.5 but i have always the error:

`Traceback (most recent call last):
  File "D:\Python\PokemonGo-Bot-dev\pokecli.py", line 30, in <module>
    import requests
ImportError: No module named requests`

**Comment by DevPhreak** [comment] 2016-07-22 15:42
Use pythob 2.7 itll work

**Comment by vladlaptev** [comment] 2016-07-22 16:05
Have the same problem, but only on clear DO server.
On local machine there are no problems.

**Comment by Mentaa** [comment] 2016-07-22 16:10
Yep i try on my VM with linux and work perfectly... its weird !

**Comment by jtdroste** [comment] 2016-07-22 16:26
I think we might get to the point where we'd mainly support mac/linux.

Closing as the issue is resolved

**Closed by jtdroste** 2016-07-22 16:26 UTC
