### ISSUE TITLE
sniping

### ISSUE THREAD

**Issue by Harak3n** [PokemonGoF/PokemonGo-Bot#3741] opened 2016-08-12 14:43 UTC
Sniping function on the list for developing?

**Comment by umbreon222** [comment] 2016-08-12 14:51
Related PR [#1887](https://github.com/PokemonGoF/PokemonGo-Bot/pull/1887)

**Comment by k4n30** [comment] 2016-08-13 01:31
Duplicate of #3672

**Closed by k4n30** 2016-08-13 01:31 UTC
