### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by yidongw** [PokemonGoF/PokemonGo-Bot#1176] opened 2016-07-27 10:44 UTC
### Expected Behavior
Running

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/Yidong_Wang/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/Yidong_Wang/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'

### Other Information
OS: Mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by yidongw** [comment] 2016-07-27 10:49
I don't know why, but I have a copy and paste the the repo. It works now.

**Comment by TheOssi** [comment] 2016-07-27 10:49
Duplicate: https://github.com/PokemonGoF/PokemonGo-Bot/issues/915
Happens due to Server Problems

**Comment by yidongw** [comment] 2016-07-27 10:50
thx

**Comment by TheGoldenXY** [comment] 2016-07-27 18:19
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/915

/closed

**Closed by TheGoldenXY** 2016-07-27 18:19 UTC
