### ISSUE TITLE
[DEV] Bot ignores incubate eggs config

### ISSUE THREAD

**Issue by Bashin** [PokemonGoF/PokemonGo-Bot#4766] opened 2016-08-26 11:02 UTC
### Expected Behavior

Bot incubates only 10km eggs in breakable incubators with the following config and leaves them unused if no 10km is available:

"infinite": [2,5,10],
"breakable": [10]

### Actual Behavior

Eggs incubating: [0.71/5.0 km, 0.71/5.0 km]
-> 1 infinite, 1 breakable

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Unmodified config.example.js (just inserted login data and changed the egg hatching part as pasted above)

### Output when issue occurred

2016-08-26 12:40:04,582 [IncubateEggs] [INFO] [incubate] Incubating a 5.0 egg.
2016-08-26 12:40:04,769 [IncubateEggs] [INFO] [incubate] Incubating a 5.0 egg.

### Steps to Reproduce

Let the bot incubate eggs with above settings.

### Other Information
OS: WIN10 64bit
Branch: dev
Git Commit: Fix shelve key error (09403f5)
Python Version: 2.7.12

**Comment by Bashin** [comment] 2016-08-26 12:17
2016-08-26 14:15:55,105 [IncubateEggs] [INFO] [incubate] Incubating a 5.0 egg.
2016-08-26 14:15:55,308 [IncubateEggs] [INFO] [incubate] Incubating a 2.0 egg.

**Comment by alexyaoyang** [comment] 2016-08-26 22:41
I think that is the expected behavior. If you want to use the breakable incubator for other x km eggs, you have to include x into the breakable array.

**Comment by etiennebechara** [comment] 2016-08-27 01:52
This bug also happened to me, I'm using the same config:

`{
			"type": "IncubateEggs",
			"config": {
				"longer_eggs_first": true,
				"min_interval": 50,
				"infinite": [2, 5, 10],
				"breakable": [10]
			}
		},`

**Comment by alexyaoyang** [comment] 2016-08-27 03:00
@supercourgette

**Comment by supercourgette** [comment] 2016-08-27 03:11
From what I can tell there are no issues here. With the config "infinite": [2,5,10],
"breakable": [10] then you will incubate the 2 5 and 10 km egg. The 2 and 5km would go to the infinite incubator and the 10 km either to the infinite or to the breakable incubator. Please have a look at the docs to make sure it is OK. Still, there may be a bug since the timing in your log is a bit strange. Could you open your app and check by yourself to make sure the egg are indeed where they are supposed to be (according to the behavior I explained). Due to the rare occurrence if the event this function has not been tested a lot in real situation therefore every input is good to take. :)

**Comment by Bashin** [comment] 2016-08-27 06:22
Yes, the app displays the eggs in the same place as the log told me. I had a quick look at the code and as far as I unterstand the code it loops through all eggs and incubates only if the egg km appears to be in the array so even if the timing is as bad as in this case it should not happen anytime. I think we need action wait here too because hatching and incubating takes quite a long time in the app.

**Comment by mjmadsen** [comment] 2016-08-27 06:33
@supercourgette I have mine setup for 10k only in breakable as well and saw it with three 5ks going. Not sure why that's happening from the code I've looked at. I haven't checked in the app to see if it's an egg distance output error.

**Comment by mjmadsen** [comment] 2016-08-27 11:43
#4803 merged. Should be working in dev branch now. Thanks again @rawgni

**Closed by mjmadsen** 2016-08-27 11:43 UTC
Labels: Bug
