### ISSUE TITLE
Keep # Pokemon based on Candy on hand

### ISSUE THREAD

**Issue by k4n30** [PokemonGoF/PokemonGo-Bot#1973] opened 2016-07-31 02:05 UTC
#1395 brought the functionality of keeping Pokemon based on CP or IV
#1472 brought the ability to release based on BOTH

New feature requested:

Add an additional check based on candy amount (global on/off - configurable in config) that allows you to keep Pokemon based on the number of candy.

eg. 
1. Pidgey requires 12 candy to evolve and you currently have 118 pidgey candy, and 9 pidgey's in your Pokemon bag
2. You capture a new pidgey (taking candy to 121, and pidgeys in your bag to 10)
3. The release config has something like 
`"Pidgey": {"keep_best_cp": 2, "keep_best_iv": 3, "keep_candy_evolution_ratio" : true}`
4. The config would also have a "keep Pokemon for lucky egg mass evolve spree" true/false field set to true
5.  The new pidgey is NOT released due to keeping the candy to evolution ratio

This would be useful for when it came time to drop a lucky egg and do the mass evolving, but if you didn't actually have the right ratio of Pokemon to candy on hand, the lucky egg would be wasted (or run out before finding enough to evolve)

**Comment by k4n30** [comment] 2016-07-31 02:10
#1972 - Seems we both had the same idea at the same time :p

**Comment by HecticSeptic** [comment] 2016-07-31 02:13
Indeed, uncanny. It's the same suggestion.

**Comment by slatspie** [comment] 2016-07-31 03:19
This would be a handy feature. I mentioned it in #1528 a couple days ago too.

**Comment by TheSavior** [comment] 2016-07-31 08:39
I think this is a great feature. New workers are appreciated

**Comment by nanogirl21** [comment] 2016-07-31 09:40
I would love this

**Comment by k4n30** [comment] 2016-07-31 12:47
@MFizz - any chance?

**Comment by k4n30** [comment] 2016-08-01 10:24
#394 another issue with the same request.

All the issues need to be cleaned up and consolidated

**Comment by TheSavior** [comment] 2016-08-01 10:26
@k4n30 Thanks for pointing that out. Closing this as a duplicate of #394.

**Closed by TheSavior** 2016-08-01 10:26 UTC
Labels: duplicate
