### ISSUE TITLE
Game gets hung up on walking

### ISSUE THREAD

**Issue by xterraforcex** [PokemonGoF/PokemonGo-Bot#1957] opened 2016-07-31 01:09 UTC
[20:06:31] Now at Pokestop: Dinosaur Topiary
[20:06:31] Spinning ...
[20:06:32] Loot: 
[20:06:32] 50 xp
[20:06:32] - 2x Pokeball (Total: 3)
[20:06:32] - 1x Ultraball (Total: 87)
[20:06:32] PokeStop on cooldown. Time left: 5 minutes, 16 seconds
[20:06:38] -- Recycled 3x Pokeball (keeps only 0 maximum) 
[20:06:38] -- Recycled 1x Potion (keeps only 0 maximum) 
[20:06:44] [x] Next egg incubates in 1.00 km
[20:06:51] Something rustles nearby!
[20:06:52] A Wild Weedle appeared! [CP 122] [Potential 0.2]
[20:06:52] IV [Stamina/Attack/Defense] = [4/3/2]
[20:06:56] Using Greatball (chance: 55.28%)... (142 left!)
[20:06:56] Captured Weedle! [CP 122] [Potential 0.2] [4/3/2] [+110 exp]
[20:07:01] Moving towards fort f83cfce12d4a4654afa61cf99a35fba4.16, 0.05km left
[20:07:11] Moving towards fort f83cfce12d4a4654afa61cf99a35fba4.16, 0.04km left
[20:07:39] Now at Pokestop: Whooping Crane Mozaic
[20:07:39] Spinning ...
[20:07:39] Loot: 
[20:07:39] 50 xp
[20:07:40] - 1x Pokeball (Total: 1)
[20:07:40] - 1x Potion (Total: 1)
[20:07:40] - 1x Super Potion (Total: 4)
[20:07:40] PokeStop on cooldown. Time left: 5 minutes, 16 seconds
[20:07:42] Moving towards fort 792270782f08406ca6571a84200cd8dc.16, 0.05km left
[20:07:46] -- Recycled 1x Pokeball (keeps only 0 maximum) 
[20:07:46] -- Recycled 1x Potion (keeps only 0 maximum) 
[20:07:56] Now at Pokestop: Wetland Overlook
[20:07:56] Spinning ...
[20:07:56] Loot: 
[20:07:56] 50 xp
[20:07:57] - 3x Pokeball (Total: 3)
[20:07:57] PokeStop on cooldown. Time left: 5 minutes, 16 seconds
[20:07:59] Moving towards fort 5d6245e1af014456ad869c625ea842ec.16, 0.07km left
[20:08:02] -- Recycled 3x Pokeball (keeps only 0 maximum) 
[20:08:20] Moving towards fort 5d6245e1af014456ad869c625ea842ec.16, 0.08km left
[20:08:49] Moving towards fort 5d6245e1af014456ad869c625ea842ec.16, 0.10km left

**Comment by xterraforcex** [comment] 2016-07-31 01:10
is there anyway to start the app fresh like clearing the cache to start it stable again?

**Comment by xterraforcex** [comment] 2016-07-31 01:18
PokeStop on cooldown. Time left: 5 minutes, 15 seconds
[20:15:53] Moving towards fort a3edd5483a05455aaadf537b46404b22.16, 0.06km left
[20:15:57] -- Recycled 2x Pokeball (keeps only 0 maximum) 
[20:16:11] Moving towards fort a3edd5483a05455aaadf537b46404b22.16, 0.05km left
[20:16:31] Now at Pokestop: Gathering Place
[20:16:31] Spinning ...
[20:16:32] Loot: 
[20:16:32] 50 xp
[20:16:32] - 2x Pokeball (Total: 2)
[20:16:32] - 1x Greatball (Total: 140)
[20:16:32] PokeStop on cooldown. Time left: 5 minutes, 16 seconds
[20:16:34] Moving towards fort 31f1402009b64e30910c522603a0e66d.16, 0.11km left
[20:16:38] -- Recycled 2x Pokeball (keeps only 0 maximum) 
[20:16:51] Moving towards fort 31f1402009b64e30910c522603a0e66d.16, 0.12km left
[20:17:28] Moving towards fort 31f1402009b64e30910c522603a0e66d.16, 0.15km left

**Comment by skorokithakis** [comment] 2016-07-31 02:53
Looks like a duplicate of #1885.

**Closed** 2016-07-31 07:05 UTC
