### ISSUE TITLE
Detectability: Bot traverses water/buildings/impassable terrain

### ISSUE THREAD

**Issue by bstpierr** [PokemonGoF/PokemonGo-Bot#984] opened 2016-07-26 12:33 UTC
If a human were to look at the path taken by the bot, it would be obvious that location spoofing is being used.

We should consider using the gmaps Waypoint API https://developers.google.com/maps/documentation/directions/intro#Waypoints possibly using Polyline encoding (https://developers.google.com/maps/documentation/utilities/polylinealgorithm) to enable pathing of multiple targets.

**Comment by mehdi-S** [comment] 2016-07-26 12:34
duplicate of issue https://github.com/PokemonGoF/PokemonGo-Bot/issues/944

**Comment by bstpierr** [comment] 2016-07-26 12:37
I think this is more of a superset bug than #944 since I'm also concerned with walking through walls and off cliffs.

**Comment by tstumm** [comment] 2016-07-26 12:43
We already have the polyline algorithm down, it just needs implementation

**Comment by douglascamata** [comment] 2016-07-26 14:01
Please, guys, search a little before creating more issues, take a look at pull requests.... we already have the issue tracked WAY TOO SPAMMED. Help us to be able to read all the issues by not duplicating.

**Comment by TheGoldenXY** [comment] 2016-07-28 22:25
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/944

/closed

**Closed by TheGoldenXY** 2016-07-28 22:25 UTC
