### ISSUE TITLE
'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#2718] opened 2016-08-07 08:58 UTC
```
2016-08-07 10:51:36,268 [RecycleItems] [INFO] [item_discarded] Discarded 1x Razz Berry (maximum 20).
2016-08-07 10:51:36,875 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Charmander (CP 172/IV 0.18) based on rule: CP < 9 OR IV < 0.97
2016-08-07 10:51:37,437 [TransferPokemon] [INFO] [pokemon_release] Exchanged Charmander [CP 172] [IV 0.18] for candy.
2016-08-07 10:51:37,953 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Estátua Moore - 0.05km (attraction of lure 0.05km)
2016-08-07 10:51:37,953 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-07 10:51:39,679 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Magnemite appeared! [CP 422] [Potential 0.71] [S/A/D 10/11/11]
2016-08-07 10:51:42,526 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 35.29 (127 left)
2016-08-07 10:51:43,728 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Magnemite! [CP 422] [Potential 0.71] [10/11/11] [+210 exp]
2016-08-07 10:51:44,706 [PokemonCatchWorker] [INFO] [pokemon_evolve_fail] Failed to evolve Magnemite!
2016-08-07 10:51:50,245 [       cli] [INFO] 
2016-08-07 10:51:50,245 [       cli] [INFO] Ran for 0:01:58
2016-08-07 10:51:50,245 [       cli] [INFO] Total XP Earned: 1450  Average: 44164.12/h
2016-08-07 10:51:50,245 [       cli] [INFO] Travelled 0.00km
2016-08-07 10:51:50,246 [       cli] [INFO] Visited 8 stops
2016-08-07 10:51:50,246 [       cli] [INFO] Encountered 5 pokemon, 5 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 10:51:50,246 [       cli] [INFO] Threw 5 poke balls
2016-08-07 10:51:50,246 [       cli] [INFO] Earned 500 Stardust
2016-08-07 10:51:50,246 [       cli] [INFO] 
2016-08-07 10:51:50,246 [       cli] [INFO] Highest CP Pokemon: Machop [CP: 645] [IV: 9/15/11] Potential: 0.78 
2016-08-07 10:51:50,246 [       cli] [INFO] Most Perfect Pokemon: Machop [CP: 645] [IV: 9/15/11] Potential: 0.78 
Traceback (most recent call last):
  File "pokecli.py", line 499, in <module>
    main()
  File "pokecli.py", line 130, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

error appears only with movetofort
with path config no error appears

**Comment by Misha023** [comment] 2016-08-07 09:15
Same error, but I'm getting this error when I start the bot. Following.

Tried the path.config, but wouldn't budge. I must be doing something very simple wrong

**Comment by Philipp59** [comment] 2016-08-07 09:19
With evolve all in task i get also this error (my path config don't have moved fort or evolve all task (read EvolvePokemon task)

```
2016-08-07 11:17:21,503 [PokemonGoBot] [INFO] 
2016-08-07 11:17:35,162 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-07 11:17:36,837 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-07 11:17:36,838 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.51 km
2016-08-07 11:17:37,894 [       cli] [INFO] 
2016-08-07 11:17:37,894 [       cli] [INFO] Ran for 0:00:23
2016-08-07 11:17:37,895 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-07 11:17:37,895 [       cli] [INFO] Travelled 0.00km
2016-08-07 11:17:37,895 [       cli] [INFO] Visited 0 stops
2016-08-07 11:17:37,895 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 11:17:37,895 [       cli] [INFO] Threw 0 poke balls
2016-08-07 11:17:37,895 [       cli] [INFO] Earned 0 Stardust
2016-08-07 11:17:37,895 [       cli] [INFO] 
2016-08-07 11:17:37,896 [       cli] [INFO] Highest CP Pokemon: 
2016-08-07 11:17:37,896 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 499, in <module>
    main()
  File "pokecli.py", line 130, in main
    raise e
TypeError: emit_event() got an unexpected keyword argument 'formatted'
```

**Comment by nivong** [comment] 2016-08-07 13:04
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2776

**Comment by Philipp59** [comment] 2016-08-09 18:09
close

**Comment by GitPupper** [comment] 2016-08-11 02:34
Assuming this was fixed. Also duplicate of other closed issues. 👍

**Closed by GitPupper** 2016-08-11 02:34 UTC
