### ISSUE TITLE
KeyError : GET_GYM_DETAILS

### ISSUE THREAD

**Issue by sayasemut** [PokemonGoF/PokemonGo-Bot#1531] opened 2016-07-29 02:14 UTC
i got this error multiple times...
any ideas why ?

File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.tick()
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 65, in tick
    self.navigator.take_step()
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 76, in take_step
    if step_walker.step():
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 466, in heartbeat
    self.update_web_location() # updates every tick
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 123, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
KeyError: 'GET_GYM_DETAILS'

and this too

 File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 257, in main
    bot.tick()
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 62, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items_worker.py", line 14, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/Users/fanabarkah/Documents/work/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 361, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'

OS: mac os 
Git Commit: 7e608c2ff5367be0e22cdf55228056aad5a0d718

**Comment by banksymate** [comment] 2016-07-29 02:18
Duplicate of #1517 
Please follow the instructions in the comment I posted in #1517

**Comment by sayasemut** [comment] 2016-07-29 02:30
ok thankyou

**Closed** 2016-07-29 02:30 UTC
