### ISSUE TITLE
Stuck when evolving

### ISSUE THREAD

**Issue by obi343** [PokemonGoF/PokemonGo-Bot#815] opened 2016-07-25 13:29 UTC
### Actual Behavior

When i'm setting evolve_all to all bot after start hangs on `[#] Attempting to evolve all pokemons ...`
CTRL + C don't work, i've to pkill python.

### Other Information
OS:  Debian Sid
Git Commit: a035304b0c9a36b10e5f11fa101136adf8302ca3

**Comment by guyz** [comment] 2016-07-25 13:52
It's not likely stuck. The problem is that if you have many different types of pokemons, and you set the filter to 'all', but none/most of the pokemons cannot be evolved, then it will take a long time as after each failed attempt it sleeps for a few seconds.

In the latest PR (not yet merged as of writing this) I've improved this - it will wait less after a failed attempt. I also reduced the sleep duration after a successful attempt.

The reason CTRL + C doesn't work here is because it's spending most of it's time sleeping. The reason you want it to sleep is because evolving in-game takes a long time - and while the script is still way faster than the game UI, I believe we shouldn't make it too fast.

**Closed** 2016-07-25 14:26 UTC

**Comment by AlexBailey** [comment] 2016-07-26 23:37
@guyz I've actually set the filter to "NONE" as per example, yet still am greeted with:

```
[2016-07-27 00:34:10] [#] Walking from () to () for approx. 1369583.00 seconds
[#] Attempting to evolve all pokemons ...
```

This happens on my MacBook but is literally just a command that hits the screen for a split second before the bot starts to literally move about, however on my imac it's pretty static and hasn't moved from this position for the last half an hour with 60 pokemon in the inventory. Judging by your maths of 'a few seconds' it surely wouldve budged by now? Also given that the distance time estimate is in the 1000's of seconds rather than minutes, I'm presuming something is wrong there too?
