### ISSUE TITLE
 Why the bot not chooses the nearest pokestop ?

### ISSUE THREAD

**Issue by vincentbeutin** [PokemonGoF/PokemonGo-Bot#95] opened 2016-07-21 23:29 UTC
I start in a location with a pokestop at 50 meters, why it chooses a pokestop far from here ?

`python pokecli.py -a google -u *** -p *** --location "Pont Boieldieu, 76000 Rouen" -w 2.5 --spinstop`

-> Found fort 69d333ccf5574064a350752d4ef74706.16 at distance 605.598593412m

An other thing, egg hatching seems not working... Meters aren't counted.

**Comment by douglascamata** [comment] 2016-07-21 23:35
@vincentbeutin because right now there's not a lot of work on how we choose PokeStops. If you look at bot.py:40 you will see that we just get a list for the server and than literally walk from stop to stop in this list. Feel welcome to improve it to walk to the nearest pokestop, it's a bit late for me and I gotta get some sleep. Maybe I'll work on it tomorrow.

**Comment by vincentbeutin** [comment] 2016-07-21 23:36
@douglascamata That's what I thought. I'll try to do something.

Do you have any idea for the second problem ? (egg hatching)

**Comment by douglascamata** [comment] 2016-07-21 23:45
No idea for egg hatching, I'm sorry. I just started playing this afternoon.

**Comment by ironbishop** [comment] 2016-07-25 13:47
the stop issue is a duplicate of #141 , while the egg hatching is not implemented yet at current time.

**Comment by TheGoldenXY** [comment] 2016-07-28 22:20
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/141

/closed

**Closed by TheGoldenXY** 2016-07-28 22:20 UTC
Labels: enhancement, needs clarification
