### ISSUE TITLE
Avoid transferring certain Pokemons

### ISSUE THREAD

**Issue by VietAnhh** [PokemonGoF/PokemonGo-Bot#1080] opened 2016-07-26 23:51 UTC
[x] Transferring Aerodactyl with CP 405
[x] Transferring Aerodactyl with CP 355
[x] Transferring Aerodactyl with CP 219
[x] Transferring Aerodactyl with CP 218
[x] Transferring Snorlax with CP 398
[x] Transferring Snorlax with CP 316
[x] Transferring Snorlax with CP 315

I set the initial transfer to 500.

But as you can see my lovely Snorlaxes are getting transferred =[

What can I do to add snorlax to a list of "don't transfer me"

**Comment by CadeBrown** [comment] 2016-07-26 23:55
Are you on the dev branch? If so, that is in the config, under "release",
just set the release_below_cp to 0, and the log to and

**Comment by xc-mezcal** [comment] 2016-07-26 23:56
In release_config, set relase_below_cp : 0

**Comment by VietAnhh** [comment] 2016-07-26 23:57
Thank you guys. I was wondering what release meant. I thought it was for capturing pokemons. To run away if the pokemon cp is low.

**Comment by CadeBrown** [comment] 2016-07-26 23:57
@VietAnhh @xc-mezcal , you need to also set the logic to and

**Comment by RiberoD07** [comment] 2016-07-26 23:59
@CadeBrown unless you set release_under_iv to 0 then 'or' is fine but otherwise and with given context you're right.

**Comment by xc-mezcal** [comment] 2016-07-27 00:00
@CadeBrown @RiberoD07 I was curious what is the logic or means there.

I have set "Golbat": { "release_below_cp": 800, "release_below_iv": 0.75, "logic": "or" },

and 2 Golbat remains.

1:CP 913 with IV 0.46
2:CP 844 with IV 0.76

Why?

**Comment by VietAnhh** [comment] 2016-07-27 01:06
@CadeBrown 

    "Snorlax":      { "release_under_cp": 0, "release_under_iv": 0, "cp_iv_logic": "and" ,"logic": "and"},

my snorlax is still getting transferred. Is there anything I'm missing?

**Comment by TheGoldenXY** [comment] 2016-07-27 01:09
@xc-mezcal The `"logic"` parameter has two values; `or` - `and`. 
If you set the parameter to `or` value, then the bot will check if the pokemon is below `"release_below_cp": 800` **## OR** `"release_below_iv": 0.75`.

However, if parameter is set to `and` value, it means that the bot will check if the pokemon is below `"release_below_cp": 800` **## AND** `"release_below_iv": 0.75`.

If the pokemon is below those values, release the pokemon.

**Comment by xc-mezcal** [comment] 2016-07-27 01:51
@TheGoldenXY I think that's what I believed. :D  But, why the first Golbat remains un-transfered? It satisfies release_below_iv0.75 and it's an "or" logic.

weird

**Comment by TheGoldenXY** [comment] 2016-07-27 02:10
@xc-mezcal Because both of your golbats have CP over 800. 

If IV is below 0.75, then check if CP is below 800 as well.

**Comment by xc-mezcal** [comment] 2016-07-27 02:19
@TheGoldenXY  Wait, Is it Transfer( CP<800 or IV<0.75) ? If so, first golbat should be exchanged for candy.

Cause I have a feel for "and" logic --> Transfer(CP<800 and IV<0.75) --> only transfer the real "trash", keep anything even it's only has one good side.

Am I right?

BTW, where can I find such a function(s) in dev project? 

Many thanks!

**Comment by TheGoldenXY** [comment] 2016-07-27 02:30
@xc-mezcal Right, let me explain this for you.

You have two golbats. Your `"logic"` parameter is set to `or`, your `"release_below_cp"` parameter is set to `800` and your `"release_below_iv"` parameter is set to `0.75`.

Golbat 1: `CP: 913`, `IV: 0.46`
Golbat 2: `CP: 844`, `IV: 0.76`

The reason why 2 golbats are remaining and not transfered, is mainly because both of the golbats has 800+ CP. For instance, if Golbat 1 had CP below 800, then that one would be transfered.

Instead of setting your ``"logic"`` parameter to `or`, you could instead set it to `and`. That means the bot won't transfer ANY of your golbats, unless CP is above 800 **AND** IV is above 0.75.

I hope you understood :)

**Comment by xc-mezcal** [comment] 2016-07-27 02:41
@TheGoldenXY 

I have tested by using 

"release_below_cp": 800 AND "release_below_iv": 0.75.
initial_transfer : true

run the script for two times.

But Golbat 1 are still there. Sad :(

********first try**********
`[22:36:33] Cleaning up Pokemon Bag using the release config
[22:36:34] Exchanging Pidgey [CP 213] [Potential 0.53]
[22:36:37] Pokemon Bag has been cleaned up!
[22:36:37]
[22:36:38] Starting PokemonGo Bot....
[22:36:38] Scanning area for objects....`

*******second try************
`[22:37:35] Cleaning up Pokemon Bag using the release config
[22:37:35] Pokemon Bag has been cleaned up!
[22:37:35]
[22:37:37] Starting PokemonGo Bot....
[22:37:37] Scanning area for objects....`

**Comment by johnw424** [comment] 2016-07-27 03:13
I have the same issue, I think this might be related some hardcoded logic of keeping at least 1 type of each Pokemon in your inventory. For example, if Zubat meets the transfer requirement, but you only have 1 Zubat in your inventory, it will NOT be transferred.

In my opinion, I don't think this should be hardcoded or even necessary. Release configs are there for a reason. Either take the hardcode out or put it as config option.

**Comment by xc-mezcal** [comment] 2016-07-27 03:21
@johnw424 Thanks man! But as i stated, I have 2 Golbats. 

The first one should be transferred, even with 1 type of each mechanism.

**Comment by xc-mezcal** [comment] 2016-07-27 03:32
@TheGoldenXY 

I have confirmed that logic "or" "and" works in the way I described.

Transfer(cp<800 or iv<0.75) 
Transfer(cp<800 and iv<0.75) 

There must be something else that made the problem happens

**Comment by iDervy** [comment] 2016-07-27 18:29
It makes no sense that the OR logic should work like that. 

If have a filter to discard any pokemon which has a CP below 800, OR an IV of below 0.8, then regardless if a Pokemon with 0.6 IV is 2000CP or 100cp, it fulfils the OR of below 0.8 IV and should be discarded.

**Comment by TheGoldenXY** [comment] 2016-07-29 19:07
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed

**Closed by TheGoldenXY** 2016-07-29 19:07 UTC
