### ISSUE TITLE
WARNING: release logic issue. 5 Snorlax and 2 Lapras  are released

### ISSUE THREAD

**Issue by seehuily** [PokemonGoF/PokemonGo-Bot#5587] opened 2016-09-21 07:38 UTC
dev: 
I just did a git pull (last pull is 3 days ago), 
OMG!!! some how the new release logic released my 5 Snorlax and 2 Lapras 

[2016-09-21 00:25:42] *Releasing Lapras* CP: 2153, IV: 0.53, IVCP: 0.66 | based on rule: CP < 0 AND IV < 0 IVCP < 0
[2016-09-21 00:25:43] Released Lapras (CP: 2153, IV: 0.53, IVCP: 0.66) You now have 2 Lapras candies
[2016-09-21 00:25:47] *Releasing Lapras* CP: 1687, IV: 0.73, IVCP: 0.75 | based on rule: CP < 0 AND IV < 0 IVCP < 0

[2016-09-21 00:26:01] *Releasing Snorlax* CP: 1590, IV: 0.84, IVCP: 0.75 | based on rule: CP < 0 AND IV < 0 IVCP < 0
[2016-09-21 00:26:02] Released Snorlax (CP: 1590, IV: 0.84, IVCP: 0.75) You now have 8 Snorlax candies
[2016-09-21 00:26:06] *Releasing Snorlax* CP: 1393, IV: 0.82, IVCP: 0.84 | based on rule: CP < 0 AND IV < 0 IVCP < 0
[2016-09-21 00:26:07] Released Snorlax (CP: 1393, IV: 0.82, IVCP: 0.84) You now have 9 Snorlax candies
[2016-09-21 00:26:11] *Releasing Snorlax* CP: 323, IV: 0.93, IVCP: 0.95 | based on rule: CP < 0 AND IV < 0 IVCP < 0
[2016-09-21 00:26:11] Released Snorlax (CP: 323, IV: 0.93, IVCP: 0.95) You now have 10 Snorlax candies
[2016-09-21 00:26:14] *Releasing Snorlax* CP: 225, IV: 0.67, IVCP: 0.78 | based on rule: CP < 0 AND IV < 0 IVCP < 0
[2016-09-21 00:26:15] Released Snorlax (CP: 225, IV: 0.67, IVCP: 0.78) You now have 11 Snorlax candies
[2016-09-21 00:26:18] *Releasing Snorlax* CP: 42, IV: 0.69, IVCP: 0.73 | based on rule: CP < 0 AND IV < 0 IVCP < 0
[2016-09-21 00:26:19] Released Snorlax (CP: 42, IV: 0.69, IVCP: 0.73) You now have 12 Snorlax candies

**Comment by seehuily** [comment] 2016-09-21 07:42
"release": {
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_release": false },
      "Moltres": { "always_release": false },
      "Zapdos": { "always_release": false },
      "Articuno": { "always_release": false },
      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_release": false },
      "Dragonite": { "always_release": false },
      "Snorlax": { "always_release": false },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_release": false },

**Comment by camnomis** [comment] 2016-09-21 09:52
I know its a bit late now, but key ones I have favorited which means release does not touch them

**Comment by Gobberwart** [comment] 2016-09-21 21:43
Oh hell, I'm on it.

**Comment by Gobberwart** [comment] 2016-09-21 21:47
In the meantime, stick an "any" rule in there... eg.

     ` "any": {"release_below_cp": 0, "logic": "or"},`

**Comment by Gobberwart** [comment] 2016-09-21 21:55
Looks like the correction of the release logic has exposed another issue wherein pokemon without any matching rule are still sent for release processing, which shouldn't happen. Working on a fix now.

**Comment by Gobberwart** [comment] 2016-09-21 22:01
Oh... ok this is working as intended... ish. Your config should be "never_release": true, not "always_release": false.

**Comment by Gobberwart** [comment] 2016-09-21 22:07
Also add an "any" rule in there to provide rules for anything you haven't specified... At the moment, it just assumes you want to release everything if you don't specify otherwise. Again, this is wrong, but until its fixed...

**Comment by Gobberwart** [comment] 2016-09-21 22:25
PR #5596 has been merged to dev. Should fix. Let me know if any issues remaining.

**Closed by Gobberwart** 2016-09-21 22:25 UTC

**Comment by seehuily** [comment] 2016-09-22 01:30
Thanks I changed to never_release
