### ISSUE TITLE
ImportError: No module named item list

### ISSUE THREAD

**Issue by HeIix** [PokemonGoF/PokemonGo-Bot#1119] opened 2016-07-27 04:07 UTC
> Traceback (most recent call last):
>   File "pokecli.py", line 40, in <module>
>     from pokemongo_bot import PokemonGoBot
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 17, in <module>
>     from cell_workers import PokemonCatchWorker, SeenFortWorker, MoveToFortWorker, InitialTransferWorker, EvolveAllWorker
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 7, in <module>
>     from evolve_all_worker import EvolveAllWorker
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/cell_workers/evolve_all_worker.py", line 5, in <module>
>     from item_list import Item
> ImportError: No module named item_list

**Config.json:**
```
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": false,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "use_lucky_egg": false,
    "evolve_captured": false,
```

### Steps to Reproduce
Starting the bot

### Other Information
OS: Debian
Git Commit: fb8585214754e5634c6f24a23f0c5170c01c3048.

**Comment by fizzxed** [comment] 2016-07-27 04:14
in evolve_all_worker.py change 
`from item_list import Item`
to
`from ..item_list import Item`

**Comment by VictorChen** [comment] 2016-07-27 04:18
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1120

**Comment by TheGoldenXY** [comment] 2016-07-27 18:46
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/pull/1120

/closed

**Closed by TheGoldenXY** 2016-07-27 18:46 UTC
Labels: duplicate
