### ISSUE TITLE
Bot not creating location-username in web directory

### ISSUE THREAD

**Issue by mushi8** [PokemonGoF/PokemonGo-Bot#1037] opened 2016-07-26 19:33 UTC
### Expected Behavior
Should create web/location-%s.json but no such file.
web dir does contains catchable and Inventory files.

### Actual Behavior
No such file, maps isn't showing current user location.

### Steps to Reproduce
run with config.json file...

### Other Information
OS: 
Ubuntu 14.04

**Comment by mushi8** [comment] 2016-07-26 20:35
Simple solution...
remove the line sttepr.py lines 110 and 119 "if os.path.isfile..."
or, simply create the files,
1. in web directory "location-%useremail%.json"
2. in data directory create "last-location-%useremail%.json"
![untitled](https://cloud.githubusercontent.com/assets/12785464/17154424/aae3f69c-5389-11e6-8269-22496511e746.png)

**Comment by rwohleb** [comment] 2016-07-26 23:21
Confirmed the issue on OSX with the master branch. As suggested by mushi8, just touching those files gets things working correctly.

**Comment by ironbishop** [comment] 2016-07-27 06:40
duplicate of #905 , fixed in dev

**Comment by TheGoldenXY** [comment] 2016-07-28 22:26
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/905

This has also been fixed in latest `dev` branch.

/closed

**Closed by TheGoldenXY** 2016-07-28 22:26 UTC
