### ISSUE TITLE
help issue please

### ISSUE THREAD

**Issue by wrenchmonkey87** [PokemonGoF/PokemonGo-Bot#1462] opened 2016-07-28 18:02 UTC
### Actual Behavior

[18:57:07] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "./pokecli.py", line 357, in <module>
    main()
  File "./pokecli.py", line 68, in main
    bot.tick()
  File "/home/sskssl2015/Scott/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/sskssl2015/PokemonGo-Bot-dev/pokemongo_bot/cell_workers/incubate_eggs_worker.py", line 34, in work
    incubators.append({"id":incubator.get("id", -1), "used":False})
AttributeError: 'str' object has no attribute 'get'

as you can see this is the error i login okthen its starts the app. im sure i have seen an incubator issue but can not find it. can someone help many thanks

**Comment by mathandsciencechannel** [comment] 2016-07-28 18:13
getting same error with most recent dev version

**Comment by aTadTasty** [comment] 2016-07-28 18:17
duplicate of this: https://github.com/PokemonGoF/PokemonGo-Bot/issues/1444

but if you are too lazy to read it in there, just do:

`sudo pip install -r requirements.txt`

**Comment by mathandsciencechannel** [comment] 2016-07-28 18:20
yea this works, i forgot to do it again when i installed the dev branch lol :)

**Comment by wrenchmonkey87** [comment] 2016-07-28 18:27
excellent i knew there was an issue i saw lol.  im in a walking glitch now shame cause i like the dev versions

**Comment by TheGoldenXY** [comment] 2016-07-28 22:04
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1444.

Issue has been resolved, closing this.

/closed

**Closed by TheGoldenXY** 2016-07-28 22:04 UTC
