### ISSUE TITLE
Follow spiral use deprecated walk setting

### ISSUE THREAD

**Issue by BoGnY** [PokemonGoF/PokemonGo-Bot#4037] opened 2016-08-15 22:34 UTC
### Expected Behavior
Working bot

### Actual Behavior

> 2016-08-16 00:20:00,045 [       cli] [INFO] Most Perfect Pokemon: Rattata [CP: 398] [IV: 7/15/9] Potential: 0.69
> 
> Python: Traceback (most recent call last):
>   File "./pokecli.py", line 609, in <module>
> 
> Python:     main()
>   File "./pokecli.py", line 104, in main
> 
> Python:     bot.tick()
>   File "C:\Luca\PokemonGO\bot_desktop_dev\gofbot\pokemongo_bot\__init__.py", line 483, in tick
>     if worker.work() == WorkerResult.RUNNING:
>   File "C:\Luca\PokemonGO\bot_desktop_dev\gofbot\pokemongo_bot\cell_workers\follow_spiral.py", line 117, in work
> 
> **Python:     if dist <= 1 or (self.bot.config.walk > 0 and step_walker == None):
> AttributeError: 'Namespace' object has no attribute 'walk'**
> 
> Python: 2016-08-16 00:20:00,130 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
> Traceback (most recent call last):
>   File "C:\Python\Python2.7\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
>     super(ThreadedHTTPTransport, self).send(data, headers)
>   File "C:\Python\Python2.7\lib\site-packages\raven\transport\http.py", line 47, in send
>     ca_certs=self.ca_certs,
>   File "C:\Python\Python2.7\lib\site-packages\raven\utils\http.py", line 66, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Python\Python2.7\lib\site-packages\future\backports\urllib\request.py", line 494, in open
>     response = self._open(req, data)
>   File "C:\Python\Python2.7\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
>     '_open', req)
>   File "C:\Python\Python2.7\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
>     result = func(*args)
>   File "C:\Python\Python2.7\lib\site-packages\raven\utils\http.py", line 46, in https_open
>     return self.do_open(ValidHTTPSConnection, req)
>   File "C:\Python\Python2.7\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers)
>   File "C:\Python\Python2.7\lib\httplib.py", line 1057, in request
>     self._send_request(method, url, body, headers)
>   File "C:\Python\Python2.7\lib\httplib.py", line 1097, in _send_request
>     self.endheaders(body)
>   File "C:\Python\Python2.7\lib\httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "C:\Python\Python2.7\lib\httplib.py", line 895, in _send_output
>     msg += message_body
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
> 

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "xxxxxxxxxxxx@gmail.com",
    "password": "",
    "location": "",
    "gmapkey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "encrypt_location": "",
    "libencrypt_location": "",
    "websocket_server": true,
    "tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "SleepSchedule",
            "config": {
                "enabled": false,
                "time": "22:54",
                "duration": "7:46",
                "time_random_offset": "00:24",
                "duration_random_offset": "00:43"
            }
        },
        {
            "type": "CollectLevelUpReward"
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": false
            }
        },
        {
            "type": "UpdateLiveStats",
            "config": {
                "enabled": true,
                "min_interval": 10,
                "stats": [
                    "username",
                    "uptime",
                    "stardust_earned",
                    "xp_earned",
                    "xp_per_hour",
                    "stops_visited"
                ],
                "terminal_log": true,
                "terminal_title": true
            }
        },
        {
            "type": "TransferPokemon"
        },
        {
            "type": "NicknamePokemon",
            "config": {
                "enabled": false,
                "nickname_template": "{iv_pct}_{iv_ads}"
            }
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "evolve_all": "none",
                "first_evolve_by": "cp",
                "evolve_above_cp": 300,
                "evolve_above_iv": 0.8,
                "logic": "or",
                "evolve_speed": 20,
                "use_lucky_egg": false
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "min_empty_space": 10,
                "max_balls_keep": 150,
                "max_potions_keep": 100,
                "max_berries_keep": 70,
                "max_revives_keep": 75,
                "item_filter": {
                    "Pokeball": {
                        "keep": 100
                    },
                    "Greatball": {
                        "keep": 90
                    },
                    "Ultraball": {
                        "keep": 80
                    },
                    "Potion": {
                        "keep": 80
                    },
                    "Super Potion": {
                        "keep": 40
                    },
                    "Hyper Potion": {
                        "keep": 30
                    },
                    "Max Potion": {
                        "keep": 25
                    },
                    "Revive": {
                        "keep": 60
                    },
                    "Razz Berry": {
                        "keep": 50
                    }
                }
            }
        },
        {
            "type": "CatchVisiblePokemon"
        },
        {
            "type": "CatchLuredPokemon"
        },
        {
            "type": "SpinFort"
        },
        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000,
                "ignore_item_count": false
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "diameter": 4,
                "step_size": 70
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 50,
        "cache_recent_forts": true
    },
    "walk_max": 16,
    "walk_min": 12,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 10,
    "catch_randomize_reticle_factor": 1,
    "catch_randomize_spin_factor": 1,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
        "any": {
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        },
        "// Pokemons with example": {
            "always_catch": true
        },
        "// Gets filtered with release parameters": {},
        "Aerodactyl": {
            "always_catch": true
        },
        "Arcanine": {
            "always_catch": true
        },
        "Articuno": {
            "always_catch": true
        },
        "Blastoise": {
            "always_catch": true
        },
        "Charizard": {
            "always_catch": true
        },
        "Clefable": {
            "always_catch": true
        },
        "Dewgong": {
            "always_catch": true
        },
        "Dragonair": {
            "always_catch": true
        },
        "Dragonite": {
            "always_catch": true
        },
        "Electabuzz": {
            "always_catch": true
        },
        "Exeggutor": {
            "always_catch": true
        },
        "Flareon": {
            "always_catch": true
        },
        "Gengar": {
            "always_catch": true
        },
        "Golduck": {
            "always_catch": true
        },
        "Golem": {
            "always_catch": true
        },
        "Grimer": {
            "always_catch": true
        },
        "Growlithe": {
            "always_catch": true
        },
        "Gyarados": {
            "always_catch": true
        },
        "Hypno": {
            "always_catch": true
        },
        "Jolteon": {
            "always_catch": true
        },
        "Kabutops": {
            "always_catch": true
        },
        "Kangaskhan": {
            "always_catch": true
        },
        "Lapras": {
            "always_catch": true
        },
        "Machamp": {
            "always_catch": true
        },
        "Magmar": {
            "always_catch": true
        },
        "Mew": {
            "always_catch": true
        },
        "Mewtwo": {
            "always_catch": true
        },
        "Moltres": {
            "always_catch": true
        },
        "Muk": {
            "always_catch": true
        },
        "Nidoking": {
            "always_catch": true
        },
        "Nidoqueen": {
            "always_catch": true
        },
        "Ninetales": {
            "always_catch": true
        },
        "Omastar": {
            "always_catch": true
        },
        "Pinsir": {
            "always_catch": true
        },
        "Poliwrath": {
            "always_catch": true
        },
        "Rapidash": {
            "always_catch": true
        },
        "Rhydon": {
            "always_catch": true
        },
        "Scyther": {
            "always_catch": true
        },
        "Seaking": {
            "always_catch": true
        },
        "Slowbro": {
            "always_catch": true
        },
        "Snorlax": {
            "always_catch": true
        },
        "Starmie": {
            "always_catch": true
        },
        "Tentacruel": {
            "always_catch": true
        },
        "Vaporeon": {
            "always_catch": true
        },
        "Venusaur": {
            "always_catch": true
        },
        "Victreebel": {
            "always_catch": true
        },
        "Vileplume": {
            "always_catch": true
        },
        "Weezing": {
            "always_catch": true
        },
        "Wigglytuff": {
            "always_catch": true
        },
        "Zapdos": {
            "always_catch": true
        }
    },
    "catch_throw_parameters": {
        "excellent_rate": 0.95,
        "great_rate": 0.02,
        "nice_rate": 0.02,
        "normal_rate": 0.01,
        "spin_success_rate": 2
    },
    "release": {
        "any": {
            "release_below_cp": 0,
            "release_below_iv": 0,
            "logic": "or"
        },
        "// Example of always releasing Rattata:": {},
        "// Rattata": {
            "always_release": true
        },
        "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
        "// Pidgey": {
            "keep_best_cp": 3
        },
        "// Example of keeping 2 stronger (based on IV) Zubat:": {},
        "// Zubat": {
            "keep_best_cp": 2,
            "keep_best_iv": 3
        },
        "// Also, it is working with any": {},
        "// any": {
            "keep_best_iv": 3
        },
        "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
        "Abra": {
            "keep_best_cp": 1
        },
        "Aerodactyl": {
            "keep_best_cp": 3
        },
        "Alakazam": {
            "keep_best_cp": 3
        },
        "Arbok": {
            "keep_best_cp": 2
        },
        "Arcanine": {
            "keep_best_cp": 2
        },
        "Articuno": {
            "keep_best_cp": 3
        },
        "Beedrill": {
            "keep_best_cp": 1
        },
        "Bellsprout": {
            "keep_best_cp": 1
        },
        "Blastoise": {
            "keep_best_cp": 2
        },
        "Bulbasaur": {
            "keep_best_cp": 1
        },
        "Butterfree": {
            "keep_best_cp": 1
        },
        "Caterpie": {
            "keep_best_cp": 1
        },
        "Chansey": {
            "keep_best_cp": 1
        },
        "Charizard": {
            "keep_best_cp": 3
        },
        "Charmander": {
            "keep_best_cp": 1
        },
        "Charmeleon": {
            "keep_best_cp": 2
        },
        "Clefable": {
            "keep_best_cp": 2
        },
        "Clefairy": {
            "keep_best_cp": 2
        },
        "Cloyster": {
            "keep_best_cp": 2
        },
        "Cubone": {
            "keep_best_cp": 1
        },
        "Dewgong": {
            "keep_best_cp": 1
        },
        "Diglett": {
            "keep_best_cp": 1
        },
        "Ditto": {
            "keep_best_cp": 2
        },
        "Dodrio": {
            "keep_best_cp": 2
        },
        "Doduo": {
            "keep_best_cp": 1
        },
        "Dragonair": {
            "keep_best_cp": 2
        },
        "Dragonite": {
            "keep_best_cp": 3
        },
        "Dratini": {
            "keep_best_cp": 1
        },
        "Drowzee": {
            "keep_best_cp": 2
        },
        "Dugtrio": {
            "keep_best_cp": 2
        },
        "Eevee": {
            "keep_best_cp": 3
        },
        "Ekans": {
            "keep_best_cp": 1
        },
        "Electabuzz": {
            "keep_best_cp": 1
        },
        "Electrode": {
            "keep_best_cp": 1
        },
        "Exeggcute": {
            "keep_best_cp": 1
        },
        "Exeggutor": {
            "keep_best_cp": 2
        },
        "Farfetch'd": {
            "keep_best_cp": 1
        },
        "Fearow": {
            "keep_best_cp": 2
        },
        "Flareon": {
            "keep_best_cp": 3
        },
        "Gastly": {
            "keep_best_cp": 1
        },
        "Gengar": {
            "keep_best_cp": 2
        },
        "Geodude": {
            "keep_best_cp": 1
        },
        "Gloom": {
            "keep_best_cp": 1
        },
        "Golbat": {
            "keep_best_cp": 1
        },
        "Goldeen": {
            "keep_best_cp": 1
        },
        "Golduck": {
            "keep_best_cp": 2
        },
        "Golem": {
            "keep_best_cp": 1
        },
        "Graveler": {
            "keep_best_cp": 2
        },
        "Grimer": {
            "keep_best_cp": 2
        },
        "Growlithe": {
            "keep_best_cp": 1
        },
        "Gyarados": {
            "keep_best_cp": 5
        },
        "Haunter": {
            "keep_best_cp": 1
        },
        "Hitmonchan": {
            "keep_best_cp": 2
        },
        "Hitmonlee": {
            "keep_best_cp": 1
        },
        "Horsea": {
            "keep_best_cp": 1
        },
        "Hypno": {
            "keep_best_cp": 1
        },
        "Ivysaur": {
            "keep_best_cp": 2
        },
        "Jigglypuff": {
            "keep_best_cp": 1
        },
        "Jolteon": {
            "keep_best_cp": 3
        },
        "Jynx": {
            "keep_best_cp": 1
        },
        "Kabuto": {
            "keep_best_cp": 1
        },
        "Kabutops": {
            "keep_best_cp": 2
        },
        "Kadabra": {
            "keep_best_cp": 2
        },
        "Kakuna": {
            "keep_best_cp": 1
        },
        "Kangaskhan": {
            "keep_best_cp": 2
        },
        "Kingler": {
            "keep_best_cp": 2
        },
        "Koffing": {
            "keep_best_cp": 1
        },
        "Krabby": {
            "keep_best_cp": 1
        },
        "Lapras": {
            "keep_best_cp": 2
        },
        "Lickitung": {
            "keep_best_cp": 1
        },
        "Machamp": {
            "keep_best_cp": 3
        },
        "Machoke": {
            "keep_best_cp": 2
        },
        "Machop": {
            "keep_best_cp": 1
        },
        "Magikarp": {
            "keep_best_cp": 5
        },
        "Magmar": {
            "keep_best_cp": 1
        },
        "Magnemite": {
            "keep_best_cp": 2
        },
        "Magneton": {
            "keep_best_cp": 3
        },
        "Mankey": {
            "keep_best_cp": 1
        },
        "Marowak": {
            "keep_best_cp": 2
        },
        "Meowth": {
            "keep_best_cp": 1
        },
        "Metapod": {
            "keep_best_cp": 1
        },
        "Mew": {
            "keep_best_cp": 2
        },
        "Mewtwo": {
            "keep_best_cp": 3
        },
        "Moltres": {
            "keep_best_cp": 2
        },
        "Mr. Mime": {
            "keep_best_cp": 1
        },
        "Muk": {
            "keep_best_cp": 1
        },
        "Nidoking": {
            "keep_best_cp": 3
        },
        "Nidoqueen": {
            "keep_best_cp": 3
        },
        "Nidoran F": {
            "keep_best_cp": 1
        },
        "Nidoran M": {
            "keep_best_cp": 1
        },
        "Nidorina": {
            "keep_best_cp": 2
        },
        "Nidorino": {
            "keep_best_cp": 2
        },
        "Ninetales": {
            "keep_best_cp": 1
        },
        "Oddish": {
            "keep_best_cp": 1
        },
        "Omanyte": {
            "keep_best_cp": 1
        },
        "Omastar": {
            "keep_best_cp": 2
        },
        "Onix": {
            "keep_best_cp": 1
        },
        "Paras": {
            "keep_best_cp": 1
        },
        "Parasect": {
            "keep_best_cp": 1
        },
        "Persian": {
            "keep_best_cp": 2
        },
        "Pidgeot": {
            "keep_best_cp": 2
        },
        "Pidgeotto": {
            "keep_best_cp": 1
        },
        "Pidgey": {
            "keep_best_cp": 1
        },
        "Pikachu": {
            "keep_best_cp": 1
        },
        "Pinsir": {
            "keep_best_cp": 2
        },
        "Poliwag": {
            "keep_best_cp": 1
        },
        "Poliwhirl": {
            "keep_best_cp": 2
        },
        "Poliwrath": {
            "keep_best_cp": 3
        },
        "Ponyta": {
            "keep_best_cp": 1
        },
        "Porygon": {
            "keep_best_cp": 2
        },
        "Primeape": {
            "keep_best_cp": 2
        },
        "Psyduck": {
            "keep_best_cp": 1
        },
        "Raichu": {
            "keep_best_cp": 2
        },
        "Rapidash": {
            "keep_best_cp": 2
        },
        "Raticate": {
            "keep_best_cp": 1
        },
        "Rattata": {
            "keep_best_cp": 1
        },
        "Rhydon": {
            "keep_best_cp": 2
        },
        "Rhyhorn": {
            "keep_best_cp": 2
        },
        "Sandshrew": {
            "keep_best_cp": 1
        },
        "Sandslash": {
            "keep_best_cp": 2
        },
        "Scyther": {
            "keep_best_cp": 2
        },
        "Seadra": {
            "keep_best_cp": 1
        },
        "Seaking": {
            "keep_best_cp": 2
        },
        "Seel": {
            "keep_best_cp": 1
        },
        "Shellder": {
            "keep_best_cp": 2
        },
        "Slowbro": {
            "keep_best_cp": 2
        },
        "Slowpoke": {
            "keep_best_cp": 1
        },
        "Snorlax": {
            "keep_best_cp": 5
        },
        "Spearow": {
            "keep_best_cp": 1
        },
        "Squirtle": {
            "keep_best_cp": 1
        },
        "Starmie": {
            "keep_best_cp": 2
        },
        "Staryu": {
            "keep_best_cp": 1
        },
        "Tangela": {
            "keep_best_cp": 1
        },
        "Tauros": {
            "keep_best_cp": 1
        },
        "Tentacool": {
            "keep_best_cp": 1
        },
        "Tentacruel": {
            "keep_best_cp": 2
        },
        "Vaporeon": {
            "keep_best_cp": 3
        },
        "Venomoth": {
            "keep_best_cp": 2
        },
        "Venonat": {
            "keep_best_cp": 1
        },
        "Venusaur": {
            "keep_best_cp": 3
        },
        "Victreebel": {
            "keep_best_cp": 1
        },
        "Vileplume": {
            "keep_best_cp": 1
        },
        "Voltorb": {
            "keep_best_cp": 2
        },
        "Vulpix": {
            "keep_best_cp": 1
        },
        "Wartortle": {
            "keep_best_cp": 2
        },
        "Weedle": {
            "keep_best_cp": 1
        },
        "Weepinbell": {
            "keep_best_cp": 1
        },
        "Weezing": {
            "keep_best_cp": 1
        },
        "Wigglytuff": {
            "keep_best_cp": 1
        },
        "Zapdos": {
            "keep_best_cp": 3
        },
        "Zubat": {
            "keep_best_cp": 1
        }
    },
    "vips": {
        "// Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "// any": {
            "catch_above_cp": 1000,
            "catch_above_iv": 0.5,
            "logic": "or"
        },
        "Arcanine": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Articuno": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Blastoise": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Charizard": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Charmeleon": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Dragonite": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Exeggutor": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Flareon": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Gyarados": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Ivysaur": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Lapras": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Mew": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Mewtwo": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Moltres": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Muk": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Snorlax": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Vaporeon": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Venusaur": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Wartortle": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Weezing": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        },
        "Zapdos": {
            "catch_above_cp": 500,
            "catch_above_iv": 0.2,
            "logic": "or"
        }
    }
}
```

### Steps to Reproduce
Launch bot with latest dev commit

### Other Information
OS: Windows 10 64bit
Git Commit: 603aca6a0f1aa900a5b9c356445b2ab363a88fc6
Python Version: 2.7.12

**Comment by Setsu-BHMT** [comment] 2016-08-15 22:37
Duplicate of #4021

**Closed** 2016-08-16 01:21 UTC
Labels: Duplicate
