### ISSUE TITLE
[Suggestion] Auto-restart and sleep mode

### ISSUE THREAD

**Issue by Pyrofer** [PokemonGoF/PokemonGo-Bot#1389] opened 2016-07-28 11:09 UTC
### Expected Behavior
After unhandled server output/crash restart by logging in again. Possible delay for login so as not to spam the servers

Sleep timer so it doesn't hunt 24/7 to avoid detection. Maybe only hunt for 8 hours of a day or always sleep during certain hours

### Actual Behavior
N/A

### Steps to Reproduce
N/A

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by proesd** [comment] 2016-07-28 11:20
did you read the [wiki](https://github.com/PokemonGoF/PokemonGo-Bot/wiki) in section restarting bot, and softban, I think it's already clear ?

**Comment by ironbishop** [comment] 2016-07-28 13:42
duplicate of #643, maybe fixed in #701

it's not the bot who need tweaking: the operator (you) is the one that needs to be clever enough to avoid botting for 8 hours at ludicrous speed...

**Comment by ferbeb** [comment] 2016-07-28 13:42
The script there is for Mac. I think the best setup would currently be a docker container that automatically restarts.  As for myself, I'll probably use a shell script that checks for running screen sessions. A prerequisite is that the bot needs to terminate. I have no idea wether the expiring login token is still a thing, the bot did not stop in this event, rendering my approach useless.  A health check would fix this, maybe that is already implemented, would be very interesting to know.

**Comment by ironbishop** [comment] 2016-07-28 13:45
you guys overthink. just write 
`pokecli.py ; sleep 10 ; pokecli.py ; sleep 10 ; pokecli.py ; sleep 10 ; pokecli.py ; sleep 10 ; pokecli.py ; sleep 10 ; ... `
^_^

**Comment by TheGoldenXY** [comment] 2016-07-28 22:29
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/643

/closed

**Closed by TheGoldenXY** 2016-07-28 22:29 UTC
