### ISSUE TITLE
pip install -r ./requirements.txt --> Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'

### ISSUE THREAD

**Issue by MettheRZ** [PokemonGoF/PokemonGo-Bot#261] opened 2016-07-22 18:48 UTC
pip install -r ./requirements.txt --> Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'

Please help me!

**Comment by VirtualSatai** [comment] 2016-07-22 18:52
Are you in the correct directory?

**Comment by MettheRZ** [comment] 2016-07-22 18:52
I dont know, I just downloaded it and placed it on my desktop

**Comment by MettheRZ** [comment] 2016-07-22 18:53
Im new to this. I have git, python and pip and this bot

**Comment by harsh1412** [comment] 2016-07-22 18:53
@MettheRZ set the paths to python and pip
Dont know how? google it :)

**Comment by MettheRZ** [comment] 2016-07-22 18:54
Yes I configured it

**Comment by MettheRZ** [comment] 2016-07-22 18:55
;C:\Python27;C:\Python27\Scripts;C:\Program Files\Git\cmd

**Comment by TheGoldenXY** [comment] 2016-07-22 18:55
Please navigate to the proper folder.

**Comment by MettheRZ** [comment] 2016-07-22 18:55
How to navigate to it?

**Comment by harsh1412** [comment] 2016-07-22 18:56
@MettheRZ read my edit :)

**Comment by MettheRZ** [comment] 2016-07-22 18:57
git clone -b master git@github.com:PokemonGoF/PokemonGo-Bot.git
I have error: 
Cloning into 'PokemonGo-Bot'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Calcyfer** [comment] 2016-07-22 18:58
On windows, ./ doesn't work. Use `pip install -r requirements.txt` instead when you are in the folder.

**Comment by MettheRZ** [comment] 2016-07-22 18:59
Okay it is working now, I didnt know about this trick with shift + empty place to open CMD. THX GUYS

**Comment by MettheRZ** [comment] 2016-07-22 19:12
Omg this bot is awesome, thank you guys!!!

**Comment by Calcyfer** [comment] 2016-07-22 19:16
It seems the issue is resolved, can you close it please? Thanks!

**Closed** 2016-07-22 20:05 UTC

**Comment by General-258** [comment] 2016-09-21 07:54
什么意思？怎么弄好的？没看明白

**Comment by General-258** [comment] 2016-09-22 01:54
说点中文看看

**Comment by General-258** [comment] 2016-09-22 02:05
This problem is how to solve the problem can not be detailed to me, I did not understand what the meaning of the above. Because I have encountered this problem. Thanks

**Comment by AbdulAj** [comment] 2017-01-23 14:50
i m facing this error while i run my program
ImportError: No module named Quartz
but when i try to install it using "sudo pip install Quarts" then following error comes,
IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-1GmHo8/Quartz/
..
how should i fix it. plz help

**Comment by gatsby97** [comment] 2017-10-11 17:07
root@gatsby:~# pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
i am just trying to install these dependencies to my scrapy working

**Comment by VirtualSatai** [comment] 2017-10-12 06:49
You're in the wrong folder,mate.

**Comment by KongChengHong** [comment] 2018-06-05 06:24
im using mac, which folder should i go

**Comment by hardik797** [comment] 2018-07-05 06:09
i am on the same folder:
folder location: 
~/myimage/

files inside this folder : 
app.py
docker-compose.yml
Dockerfile
requirement.txt

and my Dockerfile code is : 

` RUN apt-get update || apt-get update -y && \
	apt-get install nodejs npm curl python-pip -y
RUN pip install --upgrade pip
RUN npm install --save
RUN npm audit fix --force
RUN pip install -r requirement.txt `


i am getting this error: 

`Step 38/39 : RUN pip install -r requirement.txt
 ---> Running in 17e0f7e2f8b1
Could not open requirements file: [Errno 2] No such file or directory: 'requirement.txt'
The command '/bin/sh -c pip install -r requirement.txt' returned a non-zero code: 1
`

what should i do wrong ?
plz guide am new in this.

**Comment by nbhhcty** [comment] 2018-09-04 07:25
in your dockerfile add "ADD . /app"

**Comment by nbhhcty** [comment] 2018-09-04 07:28
maybe "ADD requirements.txt /code/"

**Comment by Teamate1703** [comment] 2018-10-20 21:24
Hi my friends, im sorry but i dont understand up problem. Now i have problem "pip install -r requirements.txt --> Could not open requirements file: [Errno 2] No such file or directory: requirements.txt".
Can you help me, please?

**Comment by Benyamin88** [comment] 2019-04-10 21:26
> Hi my friends, im sorry but i dont understand up problem. Now i have problem "pip install -r requirements.txt --> Could not open requirements file: [Errno 2] No such file or directory: requirements.txt".
> Can you help me, please?

Run : pip freeze > requirements.txt in your directory before running pip install -r requirements.txt

**Comment by InnoOmnia** [comment] 2019-10-17 17:01
This worked but what it is doing?
pip freeze > requirements.txt

**Comment by JohnSt99** [comment] 2020-05-01 11:26
the requirements.txt file is on YOUR COMPUTER not on the CONTAINER, you should add the following command before:
1. RUN mkdir /req
2. COPY requirements.txt /req
3. RUN pip install -r /req/requirements.txt

no1 - Creates a directory /req in the container
no2 -  Pastes requirements.txt into the directory
no3 -  Installs the requirements from the file requirements.txt inside /req

**Comment by andy-welch-nz** [comment] 2020-05-28 03:02
> > Hi my friends, im sorry but i dont understand up problem. Now i have problem "pip install -r requirements.txt --> Could not open requirements file: [Errno 2] No such file or directory: requirements.txt".
> > Can you help me, please?
> 
> Run : pip freeze > requirements.txt in your directory before running pip install -r requirements.txt

I think the issue here is 

a) creating requirements.txt where the app is being developed - ie., where the modules are installed
b) deploying requirements.txt to the app server - and passing it to "pip install -r"

just need to check that it is there (typically wwwroot folder) and readable by pip install

**Comment by delodcyber** [comment] 2020-06-25 19:09
![Screenshot_20200625-200018](https://user-images.githubusercontent.com/30188175/85783739-7f8c6d00-b71f-11ea-9732-bcd3472eeb55.png)

_**Pip3 install -r requirements.txt**_
It gives me same error message even when I'm in the right directory

**Comment by VirtualSatai** [comment] 2020-06-26 09:49
@delodcyber I doubt that pywin32 exists for the platform you're using, it's windows only.

**Comment by abbasabaei** [comment] 2021-06-08 07:52
I had the same problem and used this:

https://stackoverflow.com/a/67883521/13181871
