### ISSUE TITLE
Endless loop of skipping recycling of Items.

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#3635] opened 2016-08-11 18:32 UTC
I have an endless loop of skipping recycling of items followed by code such as

Skipping Recycling of Items. 59 space left in bag.
[14:27:37] Walking from () to () (70.2706450005 m)
[14:27:37] {'distance_unit': '', 'distance': '', 'current_position': (), 'last_position': ()}
[14:27:39] Skipping Recycling of Items. 59 space left in bag.
[14:27:39] {'distance_unit': '', 'distance': '', 'current_position': (), 'last_position': ()}

**Comment by robertpro** [comment] 2016-08-11 18:33
same issue :(

**Comment by doctordo0m** [comment] 2016-08-11 18:36
remove the `"min_empty_space": 15,` setting, it does only drop items when reaching the limit.
So you can close the bug.

**Comment by joaodragao** [comment] 2016-08-11 18:42
It should be like this:
```
if self.min_empty_space is not None and free_bag_space >= self.min_empty_space and items_in_bag < total_bag_space:
            return
```

**Comment by jimmywarting** [comment] 2016-08-11 18:43
@doctordo0m that is not the solution.
That min_empty_space is a good thing to have to reduce the number of request it has to make, it's also more what a human would do

**Comment by doctordo0m** [comment] 2016-08-11 18:45
I was speking about his config....

**Comment by DiegoRBaquero** [comment] 2016-08-11 19:32
Each loop will output that when the task if ran and it hasn't reached the threshold to drop items. That's the intended behaviour.

**Comment by GitPupper** [comment] 2016-08-11 20:02
Thanks @DiegoRBaquero for the explanation and @doctordo0m for the help. Closing this issue.

**Closed by GitPupper** 2016-08-11 20:02 UTC

**Comment by pacpac42** [comment] 2016-08-12 11:31
This is not intended behavior but a bug, since the bot does nothing except print out that message continuously. Removing ` "min_empty_space": 15` is a workaround but not a proper fix. Can you please look into the issue?

I noticed that when I added Max Revive to the list (possibly because of an increase in the # of items to keep) in my config.json, this issue can be reproduced. 

My config.json currently contains the following, and I have not upgraded my items inventory.
```
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 10 },
            "Greatball":      { "keep" : 30 },
            "Ultraball":      { "keep" : 140 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Max Potion":     { "keep" : 30 },
            "Revive":         { "keep" : 0 },
            "Max Revive":     { "keep" : 20 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },

```

Looks like removing ` "min_empty_space": 15`, running, stopping and adding back ` "min_empty_space": 15` fixes the issue. Seems to be a state bug.
