### ISSUE TITLE
Location not updated on Web

### ISSUE THREAD

**Issue by anziclone** [PokemonGoF/PokemonGo-Bot#3806] opened 2016-08-13 00:52 UTC
Location is on only update on /web/location-USERNAME.json only on initialization of the bot. It does not show the realtime bot batch and player icon does not move on the map.

### Expected Behavior
Player location updated on map

### Actual Behavior
The location file is written only on the initialization of the bot.

### Your config.json (remove your credentials and any other private info)
Pasting relevant config part:

"libencrypt_location": "encrypt.so",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 60 },
            "Potion":         { "keep" : 20 },
            "Super Potion":   { "keep" : 50 },
            "Hyper Potion":   { "keep" : 50 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
     "catch_throw_parameters": {
      "excellent_rate": 0.2,
      "great_rate": 0.4,
      "nice_rate": 0.2,
      "normal_rate": 0.2,
      "spin_success_rate" : 0.6
    },
    "websocket_server": false,
    "walk": 4.11,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,

### Steps to Reproduce
Start the bot. Observe behaviour on web page. Notice the date modified on the location-USERNAME.json file in web folder.

### Other Information
OS: Mac OSX
Branch: dev 
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f
Python Version: Python 2.7.11

**Comment by k4n30** [comment] 2016-08-13 01:01
Duplicate of #3546 which is awaiting testing of resolution

**Closed by k4n30** 2016-08-13 01:01 UTC
Labels: duplicate

**Comment by anziclone** [comment] 2016-08-13 01:05
Thank you so much. Tried searching but could not find it. My apologies, put up the wrong commit version by mistake. Cheers!
