### ISSUE TITLE
error trying to use new Buddy task

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#5572] opened 2016-09-20 18:52 UTC
### Expected Behavior

bot starts, assigns Buddy (currently have no buddy), bot runs

### Actual Behavior

bot crashes when starting

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/s8BMFJ0K

### Output when issue occurred

Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 145, in start_bot
    bot.start()
  File "C:\BUDDY\PokemonGo-Bot\pokemongo_bot\__init__.py", line 144, in start
    self._setup_api()
  File "C:\BUDDY\PokemonGo-Bot\pokemongo_bot\__init__.py", line 983, in _setup_api
    self.login()
  File "C:\BUDDY\PokemonGo-Bot\pokemongo_bot\__init__.py", line 917, in login
    str(self.config.password))
  File "C:\BUDDY\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 98, in login
    password=password
  File "c:\buddy\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 94, in set_authentication
    if not self._auth_provider.user_login(username, password):
  File "c:\buddy\pokemongo-bot\src\pgoapi\pgoapi\auth_google.py", line 58, in user_login
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID, proxy=self._proxy)
AttributeError: AuthGoogle instance has no attribute '_proxy'

### Steps to Reproduce

clean dev install, all i did was add my config with new Buddy task

### Other Information
OS: Windows 8.1 64bit
 
Branch: dev
 
Git Commit: f4c4b4f
 
Python Version: 2.7.12 64bit
 
Any other relevant files/configs (eg: path files) 

i have not upgraded Pokemon Go app and have never assigned a Buddy in-game

**Comment by DeXtroTip** [comment] 2016-09-20 18:56
The BuddyPokemon task is bugged (already submitted a PR with a fix), but the error you're getting is due to a bug in the api (there's already a PR in they're repo to fix it too) where you can't login with a Google account, I think.

**Comment by crvfts** [comment] 2016-09-20 18:57
would you like me to close this?

**Comment by DeXtroTip** [comment] 2016-09-20 19:01
I guess you can, since that error is a duplicate of #5561

**Closed** 2016-09-20 19:04 UTC
