### ISSUE TITLE
[suggestion] Option to rename caught pokemon to their iv values or potential 

### ISSUE THREAD

**Issue by reminde** [PokemonGoF/PokemonGo-Bot#897] opened 2016-07-26 01:49 UTC
Adding the option the rename pokemon to their IV values would greatly help pokemon inventory management. The catch and release thresholds are great but this would add another level of pokemon bag management.

**Comment by TheGoldenXY** [comment] 2016-07-29 18:39
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/452

/closed

**Closed by TheGoldenXY** 2016-07-29 18:39 UTC
