### ISSUE TITLE
Virtualenv does not exits

### ISSUE THREAD

**Issue by megaluck** [PokemonGoF/PokemonGo-Bot#5264] opened 2016-09-07 12:30 UTC
Since yesterday out of the blue this error started to show and the app dosent launch 

Im on Ubuntu  btw

./run.sh 
Virtualenv does not exits
Run: ./setup.sh -i

**Comment by rawgni** [comment] 2016-09-07 13:01
@megaluck can you try to 
```
virtualenv .
source bin/activate 2> /dev/null
echo $?
```

**Comment by megaluck** [comment] 2016-09-07 21:43
hi @rawgni  i tried 

gus@gus-HP-EliteBook-8560w-XXXXXX:~$ virtualenv .
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/gus/bin/python2
Also creating executable in /home/gus/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
gus@gus-HP-EliteBook-8560w-XXXXXX:~$ source bin/activate 2> /dev/null
(gus) gus@gus-HP-EliteBook-8560w-XXXXXX:~$ echo $?
0
(gus) gus@gus-HP-EliteBook-8560w-XXXXXX:~$ cd PokemonGo-Bot/
(gus) gus@gus-HP-EliteBook-8560w-XXXXXX:~/PokemonGo-Bot$ ./run.sh 
Virtualenv does not exits
Run: ./setup.sh -i
(gus) gus@gus-HP-EliteBook-8560w-XXXXXX:~/PokemonGo-Bot$

**Comment by emacalate** [comment] 2016-09-08 02:15
I didn't have virtualenv installed, I installed this manually and re-ran the pokemon go bot setup and it resolved the issue for me.

**Comment by Gobberwart** [comment] 2016-09-08 02:58
Duplicate of #5261

**Closed by Gobberwart** 2016-09-08 02:58 UTC

**Comment by rawgni** [comment] 2016-09-08 03:48
@megaluck 

can you try
```
cd PokemonGo-Bot
virtualenv .
./run.sh
```
