### ISSUE TITLE
Need a way to trigger "go home" command to return to original location

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4611] opened 2016-08-23 10:02 UTC
### Short Description
Need a way to trigger "go home" command to return to original location. This is useful in order to stop the bot for the day. Once it reached home (and automatically turned off) we can open the app on our phone immediately to enjoy the newly caught pokemons.

### Possible solution
One Ctrl+C will show options:
a) wait 20 secs
b) turn off immediately
c) return to original location

### How it would help others
"going home" says it all. It's like going back to pick up our car, or actually going home for the day.

**Comment by k4n30** [comment] 2016-08-23 12:50
Duplicate of #3773 - Considered functional in current code

**Closed by k4n30** 2016-08-23 12:50 UTC
Labels: Duplicate

**Comment by lntn** [comment] 2016-08-23 14:46
@k4n30 agreed that my request is identical to #3773 and I'm sorry about that.
However I can't see how wake_up_at_location can help on this request. What I need is actually "sleep at location" whereby the bot auto move to a certain location then stop.
