### ISSUE TITLE
Crashes after fort stop

### ISSUE THREAD

**Issue by jring314** [PokemonGoF/PokemonGo-Bot#1069] opened 2016-07-26 22:30 UTC
### Expected Behavior
Either check for lures or continue to next fort

### Actual Behavior
Crashes and exits script

### Steps to Reproduce
run dev version through to a fort

### Other Information
OS: Windows 10

[17:21:54] Loot:
[17:21:54] 50 xp
[17:21:55] - 3x Pokeball (Total: 186)
Traceback (most recent call last):
  File "pokecli.py", line 246, in <module>
    main()
  File "pokecli.py", line 237, in main
    bot.take_step()
  File "c:\PokemonGo-Bot\pokemongo_bot\__init__.py", line 46, in take_step
    self.work_on_cell(cell, location)
  File "c:\PokemonGo-Bot\pokemongo_bot\__init__.py", line 223, in work_on_cell
    hack_chain = worker.work()
  File "c:\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'unicode' object has no attribute 'get'

**Comment by TheGoldenXY** [comment] 2016-07-27 01:31
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1089

/closed

**Closed by TheGoldenXY** 2016-07-27 01:31 UTC
