### ISSUE TITLE
problems with error config files 

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#4225] opened 2016-08-18 19:33 UTC
hello ,

i have a problems with my bot , when i launch it i have a error configuration files 

i have this error .

http://prntscr.com/c7fqxw

I edited my config with json editor online and i have no error . String are good .

I haven't dupliacate keyx i don't understand .

this is my config

{
    "auth_service": "google",
    "username": "txxxxxxl.com",
    "password": "xxxxxx",
    "location": "-33.870034, 151.207964",
    "gmapkey": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
	  {
		"type": "RandomPause",
        "config": {
		  "enabled": false,
		  "min_duration": "00:00:10",
		  "max_duration": "00:10:00",
		  "min_interval": "00:10:00",
		  "max_interval": "02:00:00"
        }
	  },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
         "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 600,
          "evolve_above_iv": 0.9,
          "logic": "or",
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 200,
          "max_potions_keep": 50,
          "max_berries_keep": 40,
          "max_revives_keep": 40,
          "item_filter": {
            "Pokeball":                      { "keep" : 75 },
            "Greatball":                     { "keep" : 75 },
            "Ultraball":                     { "keep" : 75 },
            "Masterball":                    { "keep" : 75 },
            "Potion":                        { "keep" : 0 },
            "Super Potion":                  { "keep" : 0 },
            "Hyper Potion":                  { "keep" : 10 },
            "Max Potion":                    { "keep" : 0 },
            "Revive":                        { "keep" : 10 },
            "Max Revive":                    { "keep" : 0 },
            "Lucky Egg":                     { "keep" : 100 },
            "Incense":                       { "keep" : 100 },
            "Spicy Incense":                 { "keep" : 100 },
            "Cool Incense":                  { "keep" : 100 },
            "Floral Incense":                { "keep" : 100 },
            "Troy Disk":                     { "keep" : 90 },
            "X Attack":                      { "keep" : 90 },
            "X Defense":                     { "keep" : 90 },
            "X Miracle":                     { "keep" : 90 },
            "Razz Berry":                    { "keep" : 50 },
            "Bluk Berry":                    { "keep" : 50 },
            "Nanab Berry":                   { "keep" : 50 },
            "Wepar Berry":                   { "keep" : 50 },
            "Pinap Berry":                   { "keep" : 50 },
            "Special Camera":                { "keep" : 100 },
            "Incubator (Unlimited)":         { "keep" : 100 },
            "Incubator":                     { "keep" : 100 },
            "Pokemon Storage Upgrade":       { "keep" : 100 },
            "Item Storage Upgrade":          { "keep" : 100 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 2,
            "catch_wait_max": 6,
            "berry_wait_min": 2,
            "berry_wait_max": 3,
            "changeball_wait_min": 2,
            "changeball_wait_max": 3
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 3
        }
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://1xxxxxxxxxxxxx0/",
          "max_distance": 500,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,

            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,

            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,

            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,

            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,

            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,

            "Pikachu": 600,
            "Raichu": 1000,

            "==========Semi Rare==========": 0,
            "Porygon": 200,
            "Scyther": 200,
            "Jynx": 200,

            "==========Uncommon==========": 0,

            "Omanyte": 150,
            "Omastar": 500,

            "Seel": 300,
            "Dewgong": 500,

            "Grimer": 200,
            "Muk": 500,

            "Shellder": 200,
            "Cloyster": 500,

            "Gastly": 200,
            "Haunter": 500,
            "Gengar": 1000,

            "Onix": 600,

            "Drowzee": 600,

            "Hypno": 600,

            "Vulpix": 200,
            "Ninetales": 600,

            "Paras": 100,
            "Parasect": 500,

            "Growlithe": 200,
            "Arcanine": 700,

            "Tentacool": 200,
            "Tentacruel": 500,

            "Mankey": 150,
            "Primeape": 500,

            "Clefairy": 150,
            "Clefable": 500,

            "Jigglypuff": 150,
            "Wigglytuff": 500,

            "Venonat": 100,
            "Venomoth": 500,

            "Diglett": 200,
            "Dugtrio": 500,

            "Meowth": 250,
            "Persian": 500,

            "Psyduck": 150,
            "Golduck": 500,

            "Geodude": 100,
            "Graveler": 500,
            "Golem": 800,

            "Eevee": 200,
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,

            "Kabuto": 150,
            "Kabutops": 500,

            "Magikarp": 150,
            "Gyarados": 800,

            "Pinsir": 150,

            "Ponyta": 200,
            "Rapidash": 500,

            "Slowpoke": 200,
            "Slowbro": 500,

            "Magnemite": 250,
            "Magneton": 500,

            "Krabby": 100,
            "Kingler": 500,

            "Voltorb": 200,
            "Electrode": 500,

            "Exeggcute": 250,
            "Exeggcutor": 500,

            "Cubone": 300,
            "Marowak": 800,

            "Hitmonlee": 400,

            "Hitmonchan": 400,

            "Lickitung": 500,

            "Koffing": 200,
            "Weezing": 500,

            "Rhyhorn": 200,
            "Rhydon": 500,

            "Chansey": 800,

            "Tangela": 300,

            "Horsea": 200,
            "Seadra": 600,

            "Goldeen": 150,
            "Seaking": 500,

            "Staryu": 200,
            "Starmie": 800,

            "==========T1 Evolvers==========": 0,
            "Caterpie": 10,
            "Metapod": 10,
            "Butterfree": 500,

            "Weedle": 10,
            "Kakuna": 10,
            "Beedrill": 500,

            "Pidgey": 10,
            "Pidgeotto": 10,
            "Pidgeot": 300,

            "==========T2 Evolvers==========": 0,
            "Nidoran F": 10,
            "Nidorina": 10,
            "Nidoqueen": 10,

            "Nidoran M": 10,
            "Nidorino": 10,
            "Nidoking": 10,

            "Oddish": 100,
            "Gloom": 200,
            "Vileplume": 600,

            "Poliwag": 200,
            "Poliwhirl": 400,
            "Poliwrath": 800,

            "Abra": 300,
            "Kadabra": 600,
            "Alakazam": 800,

            "Machop": 150,
            "Machoke": 400,
            "Machamp": 800,

            "Bellsprout": 100,
            "Weepinbell": 400,
            "Victreebel": 800,

            "==========Trash==========": 0,

            "Rattata": 10,
            "Raticate": 10,

            "Spearow": 10,
            "Fearow": 10,

            "Ekans": 10,
            "Arbok": 10,

            "Sandshrew": 10,
            "Sandslash": 10,

            "Zubat": 10,
            "Golbat": 10,

            "Doduo": 10,
            "Dodrio": 10
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 800,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0.9, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
	  "// Example of custom order of static criterion": {},
	  "// Zubat": {"keep_best_custom": "moveset.defense_perfection hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.95, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

have you got an idea please

 thanks

**Comment by cmezh** [comment] 2016-08-18 20:26
Provide complete log.

**Comment by Tagada22** [comment] 2016-08-18 20:47
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:387:70: Error: Line terminator characters must be escaped inside string literals: 'U+000A'
   |  At line 387, column 70, offset 11184
|  String started at line 387, column 6, offset 11120
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:389:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 389, column 6, offset 11218
|  Object started at line 376, column 15, offset 10642
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:391:64: Error: Line terminator characters must be escaped inside string literals: 'U+000A'
   |  At line 391, column 64, offset 11391
|  String started at line 391, column 36, offset 11363
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:391:3: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 391, column 3, offset 11330
|  Object started at line 376, column 15, offset 10642
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:395:73: Error: Line terminator characters must be escaped inside string literals: 'U+000A'
   |  At line 395, column 73, offset 11508
|  String started at line 395, column 8, offset 11443
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:403:71: Error: Line terminator characters must be escaped inside string literals: 'U+000A'
   |  At line 403, column 71, offset 11796
|  String started at line 403, column 8, offset 11733
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json: has errors
2016-08-18 21:27:45,340 [cli] [CRITICAL] Error with configuration file
(PokemonGo-Bot) root@vps302994:/home/PokemonGo-Bot# cd

**Comment by RedViper9** [comment] 2016-08-18 21:46
The JSON parses fine. 
Looks like python isn't reading your carriage return correctly.
I think this is an encoding error. We use UTF-8 if you are set up for something else, try fixing that.

**Comment by Tagada22** [comment] 2016-08-18 21:50
I am in utf-8

**Comment by RedViper9** [comment] 2016-08-18 21:52
I would try ASCII then, but it looks like you'll have to wait for someone with more experience to help you out.

**Comment by cmezh** [comment] 2016-08-18 21:56
@Tagada22 Please provide **complete** log. If it is long upload it to pastebin.com.
Also you could make a copy of your config.json, wipe all private data from it, zip it and attach it here.

**Comment by cmezh** [comment] 2016-08-18 21:58
Attaching original file could be important when inspecting it.

**Comment by Tagada22** [comment] 2016-08-18 21:58
All complète log and config are in the first message on issue

**Comment by Tagada22** [comment] 2016-08-18 21:59
Ok i do that

**Comment by cmezh** [comment] 2016-08-18 22:01
@Tagada22 Nope, it is not complete. I see there only about 10 lines.

**Comment by Tagada22** [comment] 2016-08-19 18:04
error log

http://pastebin.com/37ARc38L

config

http://pastebin.com/BXUHL0vB


I upload in attach files here and in first post .

thanks 

[config.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/427613/config.txt)

**Comment by cmezh** [comment] 2016-08-19 18:51
@Tagada22 It looks like this problem is caused by unexpected line breaks (lines 381-382 and 389-390 according to your log).
Change this (lines 381-382):
```
        "Any pokemon put here directly force to use Berry & Best Ball to
capture, to secure the capture rate!": {},
```
to this (join it to single line):
```
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
```
Same for lines 389-390.

**Comment by mjmadsen** [comment] 2016-08-19 20:38
Do what @cmezh said and it should work. Closing.

**Closed by mjmadsen** 2016-08-19 20:38 UTC
Labels: Needs More Information, Waiting on Changes
