### ISSUE TITLE
Problem catching pokemons

### ISSUE THREAD

**Issue by VietAnhh** [PokemonGoF/PokemonGo-Bot#1126] opened 2016-07-27 04:56 UTC
[                                        ] 0%[00:54:16] Something rustles nearby!
[                                        ] 1%[00:54:25] Something rustles nearby!
[====                                    ] 11%[00:54:34] Something rustles nearby!
[========                                ] 22%[00:54:43] Something rustles nearby!

mode is set to "all"

but it's not catching anything.

I cloned the newest dev branch and this happen.

Is there any other configuration I'm missing?

**Comment by VictorChen** [comment] 2016-07-27 05:02
duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1122

**Comment by bradhuffman** [comment] 2016-07-27 05:06
Did you have any issue setting your location on the dev branch?  I get messages regarding unable to parse the location when it tries to load.

`[00:05:32] [x] Coordinates found in passed in location, not geocoding.
[00:05:32] 
[00:05:32] Location Found: 30.394997, -88.900824
[00:05:32] [x] The location given using -l could not be parsed. Checking for a cached location.
[00:05:32] [x] Parsing cached location...
`

**Comment by VietAnhh** [comment] 2016-07-27 05:10
@bradhuffman 
No i didn't get that error

**Comment by louisgv** [comment] 2016-07-27 05:38
This issue is also happening to me. 

@bradhuffman The position bug is fixed on latest dev

**Comment by TheGoldenXY** [comment] 2016-07-27 18:45
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1122

/closed

**Closed by TheGoldenXY** 2016-07-27 18:45 UTC
