### ISSUE TITLE
No more colors

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#2547] opened 2016-08-03 21:15 UTC
### Expected Behavior
Logs should be in color

### Actual Behavior
Only white logs

### Steps to Reproduce
Commit: b2983f7100fb6f1b4c9db833bc09a7820fea634a

### Other Information
OS: Ubuntu
Git Commit: b2983f7100fb6f1b4c9db833bc09a7820fea634a
Python Version: Python 2.7.9

**Comment by Kujawadl** [comment] 2016-08-03 21:19
This is from #2173. I may be wrong, but I believe this is because the logs are changing to Sockets.IO, and you should be getting them in the web ui from now on.

That being said, I'm still not getting any logs in the web ui :/

**Comment by Lunik** [comment] 2016-08-03 21:31
I don't use webUI logs because they don't work `lol` >.>
But I miss the colors 😭

**Comment by Kafkamorph** [comment] 2016-08-03 21:41
w/e, it looks like shit now.

**Comment by Kujawadl** [comment] 2016-08-03 21:49
#2540 It looks like there are some problems with the bots anyway, so it may be that the webUI logs work, but the bot's just not doing anything. 

idk about anyone else, but for me it's just walking around, but none of the distance actually gets recorded (e.g. 10min running, close it out and it says 0.0km walked).

**Comment by SpencerCarstens** [comment] 2016-08-03 22:17
@Lunik Yea, I couldn't figure out the server either, but unsure if it's due to the API being borked or not.

**Comment by Vvkmnn** [comment] 2016-08-03 22:43
Same here on macOS 10.11.6 running commit b2983f7100fb6f1b4c9db833bc09a7820fea634a.

There's more information about how to setup the new bot config and websocket in #2173, but I can't figure it out at the moment. 

This seems like an unnecessary complication; I didn't even know we had a Web UI until a few days ago, and I loved the console log. Why forcibly merge the two?

Anyone interested in the old setup should run the following code to revert back to the commit right before this latest one. I intend on using this until things sort themselves out: 

 `git reset --hard 02d9102` 

Seems like we've got much bigger problems though, which might be affecting why the logs aren't populating: #2540

**Comment by Kujawadl** [comment] 2016-08-03 22:55
With the server config, I'm using nginx:

### config.json

```json
...
  "websocket": {
    "start_embedded_server": true,
    "server_url": "localhost:8080",
    "remote_control": true
  },
...
```

### /etc/nginx/sites-available/default

```
...
server {
  listen 80;

  root /[wherever]/PokemonGo-Bot/web;
  index index.html index.htm

  location / {
    try_files $uri $uri/ /index.html =404;
  }

  location /socket.io/ {
    proxy_pass http://localhost:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
...
```

I can confirm that the webUI successfully connects to sockets.io, but again, the bot isn't doing anything that would generate a log, so I can't confirm that the logs are being passed correctly.

The reason I'm excited for this to work is that it brings with it the ability to control the bot from the web. Transfer/evolve pokemon, set a destination, etc... So it may not be the best right now, but don't completely give up on it either. There's a lot of potential.

**Comment by TCB13** [comment] 2016-08-04 00:37
@Vvkmnn I agree with you, this Web UI should be optional. I really like the simplicity of just running the bot from a command line specifying a config file. The Web UI will bring more complexity over here / issues to reboot the bot etc...

**Comment by larssy1** [comment] 2016-08-06 08:54
I'm hoping they are bringing the colorized logging back :)

**Closed** 2016-08-06 20:50 UTC

**Comment by SpencerCarstens** [comment] 2016-08-07 07:03
Was this ever really flushed out or is it half baked still? I can't quite get everything to line up as it should.

**Comment by Vvkmnn** [comment] 2016-08-07 14:34
@Kujawadl I borrowed your config, but I'm still getting a 404 at that address. Am I missing a parameter?

**Comment by Kujawadl** [comment] 2016-08-07 16:35
Can you send me what commit you're on (both the bot and the web project), your `config.json`, `userdata.json`, and `/etc/nginx/sites-available/default`?

**Comment by serberus7** [comment] 2016-08-07 17:33
Use my cell workers if you want the colors back
https://github.com/PokemonGoF/PokemonGo-Bot/files/405611/cell_workers.zip
https://cloud.githubusercontent.com/assets/20890081/17463873/f8d6fb90-5c96-11e6-8d6f-e4dd8e20e337.png

**Comment by ph3l1x** [comment] 2016-08-07 18:40
How do we use this cell works file? Are there plans of returning the output back the way it was? I liked to just look at the return from the bot and see what it was doing etc.. Its way to hard to read now..
