### ISSUE TITLE
Error: Bot isn't moving

### ISSUE THREAD

**Issue by db-coder** [PokemonGoF/PokemonGo-Bot#4872] opened 2016-08-28 21:16 UTC
### Expected Behavior
Bot should make the character move.

### Actual Behavior
Character isn't moving. Maybe, can't see the map too.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
```
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": false,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "alert_catch": ["all"]
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "amount": 7,
          "order_by": "cp",
          "info_to_show": ["cp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 3,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
          "evolve_all": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 5,
          "item_filter": {
            "Pokeball":       { "keep" : 60 },
            "Greatball":      { "keep" : 80 },
            "Ultraball":      { "keep" : 100 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Max Potion":     { "keep" : 0 },
            "Revive":         { "keep" : 0 },
            "Max Revive":     { "keep" : 0 },
            "Razz Berry":     { "keep" : 70 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": false,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": false,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": false,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": false,
      "show_log_level": false
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2},
      "Pidgey": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Rattata": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Zubat": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Krabby": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Weedle": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Poliwag": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Magikarp": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Staryu": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Caterpie": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Spearow": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Clefairy": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Abra": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Psyduck": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Eevee": {"keep_best_cp": 3, "keep_best_iv": 1},
      "Voltorb": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Slowpoke": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Magnemite": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Venonat": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Pinsir": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Dratini": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Bulbasaur": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Squirtle": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Charmander": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Golbat": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Paras": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Geodude": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Nidoran M": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Nidoran F": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Sandshrew": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Oddish": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Machop": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Growlithe": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Horsea": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Ekans": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Meowth": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Bellsprout": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Rhyhorn": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Tauros": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Tangela": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Raticate": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Ponyta": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Goldeen": {"keep_best_cp": 2, "keep_best_iv": 1}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

```

### Output when issue occurred

```
[2016-08-29 02:29:29] [bot_start] Starting bot...
[2016-08-29 02:29:30] [level_up_reward] Received level up reward: []
[2016-08-29 02:29:30] [next_egg_incubates] Eggs incubating: [8.69/10.0 km, 3.58/5.0 km, 1.51/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-29 02:29:33] [log_stats] pikachuluffy1 | Uptime : 0:00:10 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:29:33] [show_inventory] Pokemon: 204/250 | Items: 261/350 | Pokeballs: 60 | GreatBalls: 80 | UltraBalls: 29 | RazzBerries: 70
[2016-08-29 02:29:33] [show_best_pokemon] [Snorlax, CP 1223] | [Pinsir, CP 925] | [Dodrio, CP 890] | [Scyther, CP 826] | [Golbat, CP 808] | [Rapidash, CP 725] | [Magmar, CP 720]
[2016-08-29 02:30:37] [log_stats] pikachuluffy1 | Uptime : 0:01:15 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:31:31] [next_egg_incubates] Eggs incubating: [8.69/10.0 km, 3.58/5.0 km, 1.51/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-29 02:31:34] [show_inventory] Pokemon: 204/250 | Items: 261/350 | Pokeballs: 60 | GreatBalls: 80 | UltraBalls: 29 | RazzBerries: 70
[2016-08-29 02:31:34] [show_best_pokemon] [Snorlax, CP 1223] | [Pinsir, CP 925] | [Dodrio, CP 890] | [Scyther, CP 826] | [Golbat, CP 808] | [Rapidash, CP 725] | [Magmar, CP 720]
[2016-08-29 02:31:39] [log_stats] pikachuluffy1 | Uptime : 0:02:18 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:32:42] [log_stats] pikachuluffy1 | Uptime : 0:03:19 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:33:32] [next_egg_incubates] Eggs incubating: [8.69/10.0 km, 3.58/5.0 km, 1.51/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-29 02:33:35] [show_inventory] Pokemon: 204/250 | Items: 261/350 | Pokeballs: 60 | GreatBalls: 80 | UltraBalls: 29 | RazzBerries: 70
[2016-08-29 02:33:35] [show_best_pokemon] [Snorlax, CP 1223] | [Pinsir, CP 925] | [Dodrio, CP 890] | [Scyther, CP 826] | [Golbat, CP 808] | [Rapidash, CP 725] | [Magmar, CP 720]
[2016-08-29 02:33:45] [log_stats] pikachuluffy1 | Uptime : 0:04:22 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:34:48] [log_stats] pikachuluffy1 | Uptime : 0:05:26 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:35:32] [next_egg_incubates] Eggs incubating: [8.69/10.0 km, 3.58/5.0 km, 1.51/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-29 02:35:35] [show_inventory] Pokemon: 204/250 | Items: 261/350 | Pokeballs: 60 | GreatBalls: 80 | UltraBalls: 29 | RazzBerries: 70
[2016-08-29 02:35:35] [show_best_pokemon] [Snorlax, CP 1223] | [Pinsir, CP 925] | [Dodrio, CP 890] | [Scyther, CP 826] | [Golbat, CP 808] | [Rapidash, CP 725] | [Magmar, CP 720]
[2016-08-29 02:35:52] [log_stats] pikachuluffy1 | Uptime : 0:06:30 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:36:55] [log_stats] pikachuluffy1 | Uptime : 0:07:33 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:37:33] [next_egg_incubates] Eggs incubating: [8.69/10.0 km, 3.58/5.0 km, 1.51/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-29 02:37:36] [show_inventory] Pokemon: 204/250 | Items: 261/350 | Pokeballs: 60 | GreatBalls: 80 | UltraBalls: 29 | RazzBerries: 70
[2016-08-29 02:37:36] [show_best_pokemon] [Snorlax, CP 1223] | [Pinsir, CP 925] | [Dodrio, CP 890] | [Scyther, CP 826] | [Golbat, CP 808] | [Rapidash, CP 725] | [Magmar, CP 720]
[2016-08-29 02:37:58] [log_stats] pikachuluffy1 | Uptime : 0:08:36 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:39:02] [log_stats] pikachuluffy1 | Uptime : 0:09:39 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-29 02:39:33] [next_egg_incubates] Eggs incubating: [8.69/10.0 km, 3.58/5.0 km, 1.51/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-29 02:39:36] [show_inventory] Pokemon: 204/250 | Items: 261/350 | Pokeballs: 60 | GreatBalls: 80 | UltraBalls: 29 | RazzBerries: 70
[2016-08-29 02:39:36] [show_best_pokemon] [Snorlax, CP 1223] | [Pinsir, CP 925] | [Dodrio, CP 890] | [Scyther, CP 826] | [Golbat, CP 808] | [Rapidash, CP 725] | [Magmar, CP 720]
[2016-08-29 02:40:06] [log_stats] pikachuluffy1 | Uptime : 0:10:44 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops

```
### Steps to Reproduce
Just ran the bot in the latest commit

### Other Information
OS: 
Ubuntu 15.04
Branch: 
dev
Git Commit: 
007f02a35726947b7378aada3fb0cf8d0b462b36
Python Version: 
Python 2.7.9

**Comment by db-coder** [comment] 2016-08-28 21:25
There was something wrong with the  userdata.js file. It's working now.

**Comment by db-coder** [comment] 2016-08-28 22:22
It stopped working after I restarted the bot :/

**Comment by mjmadsen** [comment] 2016-08-29 14:22
Are you starting and stopping the bot a lot? You seem to be having an above average amount of problems (esp for a linux user :P). Can you try the new commits - we added some protection against the json files we've been having problems with. It's not a solution, but it should reduce downtime.

**Comment by sediyama** [comment] 2016-08-29 23:19
I know what is your problem... you should ENABLE the followspiral, your bot is not seeing any Forts at the current position, if you enable the followspiral, it will move and start seeing after a while.
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": **true**,
          "diameter": 4,
          "step_size": 70
        }

**Comment by db-coder** [comment] 2016-08-30 01:46
@mjmadsen yes I had to start and stop the bot a lot, mainly because of the "Possibly searching too often" issue. That error doesn't let me catch Pokemon or spin forts.
Another bug that usually gives pains is the total count of Pokemon in case there's an egg hatch. The bot doesn't seem to account if there was an egg hatch and the count of Pokemon doesn't increase. Due to this, my Pokemon bag becomes full way before the bot realises that it should invoke the release task.

**Comment by db-coder** [comment] 2016-08-30 06:23
Some logs regarding this issue:

```
[2016-08-30 11:24:07] [spun_pokestop] Spun pokestop West 87th Garden and Park. Experience awarded: 50. Items awarded: {u'Potion': 1, u'Pokeball': 2}
[2016-08-30 11:24:11] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.14km
[2016-08-30 11:24:16] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.13km
[2016-08-30 11:24:20] [log_stats] pikachuluffy1 | Uptime : 3:56:15 | Earned 14,384 Stardust | +29,000 XP | 7,364 XP/h | Visited 173 stops
[2016-08-30 11:24:23] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.13km
[2016-08-30 11:24:31] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.12km
[2016-08-30 11:24:37] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.11km
[2016-08-30 11:24:43] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.11km
[2016-08-30 11:24:50] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.10km
[2016-08-30 11:24:56] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.09km
[2016-08-30 11:25:01] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.09km
[2016-08-30 11:25:08] [next_egg_incubates] Eggs incubating: [7.44/10.0 km, 7.44/10.0 km, 1.37/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-30 11:25:09] [show_inventory] Pokemon: 223/250 | Items: 318/350 | Pokeballs: 65 | GreatBalls: 66 | UltraBalls: 87 | RazzBerries: 70
[2016-08-30 11:25:09] [show_best_pokemon] [Lapras, CP 1559] | [Pinsir, CP 1256] | [Snorlax, CP 1223] | [Scyther, CP 1085] | [Tauros, CP 1030] | [Aerodactyl, CP 970] | [Dodrio, CP 890]
[2016-08-30 11:25:09] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.08km
[2016-08-30 11:25:14] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.07km
[2016-08-30 11:25:20] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.07km
[2016-08-30 11:25:24] [log_stats] pikachuluffy1 | Uptime : 3:57:18 | Earned 14,384 Stardust | +29,000 XP | 7,332 XP/h | Visited 173 stops
[2016-08-30 11:25:28] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.06km
[2016-08-30 11:25:33] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.06km
[2016-08-30 11:25:39] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.05km
[2016-08-30 11:25:44] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.05km
[2016-08-30 11:25:51] [moving_to_fort] Moving towards pokestop St. Dumitru Romanian Orthodox Church - 0.04km
[2016-08-30 11:25:57] [pokestop_out_of_range] Pokestop St. Dumitru Romanian Orthodox Church out of range.
[2016-08-30 11:25:57] [pokestop_searching_too_often] **Possibly searching too often, take a rest.**
[2016-08-30 11:25:59] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.14km
[2016-08-30 11:26:04] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.14km
[2016-08-30 11:26:10] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.13km
[2016-08-30 11:26:16] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.13km
[2016-08-30 11:26:21] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.12km
[2016-08-30 11:26:26] [log_stats] pikachuluffy1 | Uptime : 3:58:20 | Earned 14,384 Stardust | +29,000 XP | 7,300 XP/h | Visited 173 stops
[2016-08-30 11:26:26] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.12km
[2016-08-30 11:26:32] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.12km
[2016-08-30 11:26:37] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.11km
[2016-08-30 11:26:46] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.10km
[2016-08-30 11:26:51] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.09km
[2016-08-30 11:26:59] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.09km
[2016-08-30 11:27:04] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.08km
[2016-08-30 11:27:09] [next_egg_incubates] Eggs incubating: [7.44/10.0 km, 7.44/10.0 km, 1.37/5.0 km] (Eggs left: 6, Incubating: 3)
[2016-08-30 11:27:10] [show_inventory] Pokemon: 223/250 | Items: 318/350 | Pokeballs: 65 | GreatBalls: 66 | UltraBalls: 87 | RazzBerries: 70
[2016-08-30 11:27:10] [show_best_pokemon] [Lapras, CP 1559] | [Pinsir, CP 1256] | [Snorlax, CP 1223] | [Scyther, CP 1085] | [Tauros, CP 1030] | [Aerodactyl, CP 970] | [Dodrio, CP 890]
[2016-08-30 11:27:10] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.08km
[2016-08-30 11:27:16] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.07km
[2016-08-30 11:27:21] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.06km
[2016-08-30 11:27:27] [log_stats] pikachuluffy1 | Uptime : 3:59:22 | Earned 14,384 Stardust | +29,000 XP | 7,269 XP/h | Visited 173 stops
[2016-08-30 11:27:27] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.06km
[2016-08-30 11:27:34] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.06km
[2016-08-30 11:27:39] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.05km
[2016-08-30 11:27:45] [moving_to_fort] Moving towards pokestop Functional Sculptor Found on Columbus Avenue - 0.04km
[2016-08-30 11:27:48] [pokestop_out_of_range] Pokestop Functional Sculptor Found on Columbus Avenue out of range.
[2016-08-30 11:27:48] [pokestop_searching_too_often] **Possibly searching too often, take a rest.**
[2016-08-30 11:27:50] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.08km
[2016-08-30 11:27:56] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.08km
[2016-08-30 11:28:02] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.07km
[2016-08-30 11:28:07] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.07km
[2016-08-30 11:28:13] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.06km
[2016-08-30 11:28:18] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.05km
[2016-08-30 11:28:24] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.05km
[2016-08-30 11:28:28] [log_stats] pikachuluffy1 | Uptime : 4:00:23 | Earned 14,384 Stardust | +29,000 XP | 7,238 XP/h | Visited 173 stops
[2016-08-30 11:28:31] [moving_to_fort] Moving towards pokestop The Circle Widens - 0.04km
[2016-08-30 11:28:34] [pokestop_out_of_range] Pokestop The Circle Widens out of range.
[2016-08-30 11:28:34] [pokestop_searching_too_often] **Possibly searching too often, take a rest**.
[2016-08-30 11:28:39] [moving_to_fort] Moving towards pokestop Blue Whale - 0.06km
[2016-08-30 11:28:44] [moving_to_fort] Moving towards pokestop Blue Whale - 0.05km
^C[2016-08-30 11:28:45] [bot_interrupted] Bot caught SIGINT. Shutting down.
```

This happens after restarting the bot:
```
[2016-08-30 11:42:20] [position_update] Walking from (40.78267, -73.96525, 8.0) to (40.78267, -73.96525, 560.7110534214496) (0.0 m)
[2016-08-30 11:42:21] [position_update] Walking from (40.78266506618903, -73.96525196920315, 655.1328418797982) to (40.7833005298437, -73.96525, 783.0162065854668) (70.6604938486 m)
[2016-08-30 11:42:42] [position_update] Walking from (40.78330851674499, -73.96524276325015, 518.7896492729463) to (40.7833005298437, -73.96605942910058, 632.7472364480514) (68.7651118312 m)
[2016-08-30 11:43:04] [position_update] Walking from (40.783324260308376, -73.96606246889547, 753.1106158850844) to (40.78267, -73.96605942910058, 770.2967619899791) (72.7508863529 m)
[2016-08-30 11:43:21] [log_stats] pikachuluffy1 | Uptime : 0:01:50 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-30 11:43:30] [position_update] Walking from (40.78269384548656, -73.96605094893842, 945.8032331615791) to (40.782039470156306, -73.96605942910058, 613.7456239873013) (72.7667609149 m)
[2016-08-30 11:43:51] [position_update] Walking from (40.782025017351074, -73.96606875747501, 833.2701055696937) to (40.782039470156306, -73.96525, 936.1820523300662) (68.9554998387 m)
[2016-08-30 11:44:13] [position_update] Walking from (40.782051382839754, -73.96522720501703, 634.1397920824535) to (40.782039470156306, -73.96444057089941, 721.9418506187094) (66.2453247992 m)
[2016-08-30 11:44:20] [show_inventory] Pokemon: 223/250 | Items: 318/350 | Pokeballs: 65 | GreatBalls: 66 | UltraBalls: 87 | RazzBerries: 70
[2016-08-30 11:44:20] [show_best_pokemon] [Lapras, CP 1559] | [Pinsir, CP 1256] | [Snorlax, CP 1223] | [Scyther, CP 1085] | [Tauros, CP 1030] | [Aerodactyl, CP 970] | [Dodrio, CP 890]
[2016-08-30 11:44:22] [log_stats] pikachuluffy1 | Uptime : 0:02:51 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-30 11:44:33] [position_update] Walking from (40.78205701405668, -73.96445719946965, 590.8933086317061) to (40.78267, -73.96444057089941, 883.3105555776019) (68.1752642775 m)
[2016-08-30 11:44:55] [position_update] Walking from (40.78265847426584, -73.96444114092043, 632.4332722436036) to (40.7833005298437, -73.96444057089941, 650.0854915743383) (71.3933008221 m)
[2016-08-30 11:45:18] [position_update] Walking from (40.78331640413977, -73.96443365401724, 570.9288580226862) to (40.7839310596874, -73.96444057089941, 713.1583640554683) (68.3490526077 m)
[2016-08-30 11:45:24] [log_stats] pikachuluffy1 | Uptime : 0:03:53 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-30 11:45:40] [position_update] Walking from (40.78395216344504, -73.9644198676246, 558.6201012627909) to (40.7839310596874, -73.96525, 905.258290007793) (69.9318521556 m)
[2016-08-30 11:46:04] [position_update] Walking from (40.78392394300138, -73.96525309473232, 717.6412278570532) to (40.7839310596874, -73.96605942910058, 888.1715343660891) (67.8934117421 m)
[2016-08-30 11:46:21] [show_inventory] Pokemon: 223/250 | Items: 318/350 | Pokeballs: 65 | GreatBalls: 66 | UltraBalls: 87 | RazzBerries: 70
[2016-08-30 11:46:21] [show_best_pokemon] [Lapras, CP 1559] | [Pinsir, CP 1256] | [Snorlax, CP 1223] | [Scyther, CP 1085] | [Tauros, CP 1030] | [Aerodactyl, CP 970] | [Dodrio, CP 890]
[2016-08-30 11:46:25] [log_stats] pikachuluffy1 | Uptime : 0:04:54 | Earned 0 Stardust | +0 XP | 0 XP/h | Visited 0 stops
[2016-08-30 11:46:29] [position_update] Walking from (40.783944616412455, -73.96606037590502, 997.0066505226471) to (40.7839310596874, -73.96686885820115, 613.1043162109303) (68.0863318271 m)
[2016-08-30 11:46:51] [position_update] Walking from (40.78394054275162, -73.96688497035801, 739.6278307952847) to (40.7833005298437, -73.96686885820115, 813.1893114845864) (71.1791350783 m)
^C[2016-08-30 11:46:57] [bot_interrupted] Bot caught SIGINT. Shutting down.

```

**Comment by mjmadsen** [comment] 2016-08-30 06:32
Willing to bet you have an IP ban. You also didn't see any pokemon during the first part of the log. Especially since you're hatching so many eggs before catch_pokemon runs (from seeing a pokemon). 

I would not advise starting and stopping the bot every time you see a searching too often message. That's the server throttling you. Forcing a restart won't fix that.

**Comment by db-coder** [comment] 2016-08-30 06:53
One is usually IP banned when he runs multiple bots from a single IP right? I'm just running this one bot.

**Comment by mjmadsen** [comment] 2016-08-30 06:57
Caused by a variety of things on the server side.

**Comment by db-coder** [comment] 2016-08-30 09:38
did something happen to the incubate eggs task? The bot isn't showing any info regarding eggs after the latest commit.

**Comment by mjmadsen** [comment] 2016-08-30 09:47
Last merge for incubate was about 7 hours ago.

**Closed** 2016-08-31 06:32 UTC
Labels: Needs More Information
