### ISSUE TITLE
Bot crash ?

### ISSUE THREAD

**Issue by iphonitest** [PokemonGoF/PokemonGo-Bot#2776] opened 2016-08-07 11:36 UTC
### Expected Behavior

Bot run

### Actual Behavior

```
2016-08-07 13:14:40,079 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-07 13:14:42,323 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-07 13:14:42,323 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 3.40 km
2016-08-07 13:14:42,656 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Nidoran M, based on cp and iv
2016-08-07 13:14:43,061 [TransferPokemon] [INFO] [pokemon_release] Exchanged Nidoran M [CP 31] [IV 0.38] for candy.
2016-08-07 13:14:46,094 [       cli] [INFO] 
2016-08-07 13:14:46,094 [       cli] [INFO] Ran for 0:00:16
2016-08-07 13:14:46,094 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-07 13:14:46,094 [       cli] [INFO] Travelled 0.00km
2016-08-07 13:14:46,094 [       cli] [INFO] Visited 0 stops
2016-08-07 13:14:46,094 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 13:14:46,094 [       cli] [INFO] Threw 0 pokeballs
2016-08-07 13:14:46,094 [       cli] [INFO] Earned 0 Stardust
2016-08-07 13:14:46,094 [       cli] [INFO] 
2016-08-07 13:14:46,094 [       cli] [INFO] Highest CP Pokemon: 
2016-08-07 13:14:46,094 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
2016-08-07 13:14:46,102 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/iphonitest/Downloads/PokemonGO/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 13:14:46,106 [sentry.errors.uncaught] [ERROR] [u"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)", u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 129, in main']
```

### Steps to Reproduce

./run.sh

### Other Information
OS: Mac OS 10.11.6
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: Python 2.7.11

**Comment by Bramzor** [comment] 2016-08-07 11:36
Duplicate of #2769

**Comment by shycum** [comment] 2016-08-07 11:46
Not a duplicate, I was able to solve this by deleting the data/last-location* file

**Comment by michihu** [comment] 2016-08-07 12:51
this is no duplicate.

If you delete the last location it works until it ends again here:

2016-08-07 14:48:34,444 [       cli] [INFO] Highest CP Pokemon: Spearow [CP: 371] [IV: 13/0/7] Potential: 0.44 
2016-08-07 14:48:34,445 [       cli] [INFO] Most Perfect Pokemon: Rattata [CP: 245] [IV: 12/12/10] Potential: 0.76 
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
2016-08-07 14:48:34,460 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync

**Comment by nivong** [comment] 2016-08-07 12:54
This is a known issue I think i have seen it before, a pokestop includes an special character like åß∂ƒ or something move somewhere else will be an temp solution.

**Comment by michihu** [comment] 2016-08-07 13:03
it just worked with a special character so I guess the issue is different.

bots still runs after this spot:

2016-08-07 15:02:08,205 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Zum Schwarzen Bären. Experience awarded: 50. Items awarded: {u'Pokeball': 2, u'Super Potion': 1}

**Closed** 2016-08-11 02:38 UTC
