### ISSUE TITLE
How to make the bot stay in a certain area

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#1299] opened 2016-07-28 00:36 UTC
### Expected Behaviour
There is an area with multiple lured pokestops that I want the bot to stay at but it keeps wandering away.

**Comment by Calcyfer** [comment] 2016-07-28 00:43
There is a way to sort of do this, I used this method during testing.
Set your max steps in config to 1 and apply this patch :  
http://pastebin.com/raw/Vsr2FE6h

**Comment by OVO647** [comment] 2016-07-28 02:20
Does the dev branch differentiate between lure catches and wild pokemon?

**Comment by Antairez** [comment] 2016-07-28 02:48
@Calcyfer Applied your patch and set max steps to 1. The bot seemed to target a very far away pokestop after this modification. I'm on the latest dev.

**Comment by OVO647** [comment] 2016-07-28 02:53
Same I'm having the same problem.

**Comment by ironbishop** [comment] 2016-07-28 07:55
duplicate of #334

**Comment by TheGoldenXY** [comment] 2016-07-28 22:27
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/334

/closed

**Closed by TheGoldenXY** 2016-07-28 22:27 UTC
