### ISSUE TITLE
Error after successfully connected. Image Inside

### ISSUE THREAD

**Issue by AndreAbdel27** [PokemonGoF/PokemonGo-Bot#1113] opened 2016-07-27 03:39 UTC
### Expected Behavior
My config.json is properly filled. and im running on my window 10 cmd in the project folder python pokecli.py and after validading my user it crash.
### Steps to Reproduce
![error](https://cloud.githubusercontent.com/assets/13223242/17163135/09d88dde-5371-11e6-92ed-f6b477fb6afd.png)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by AndreAbdel27** [comment] 2016-07-27 03:50
Fixed with #1042  running smoothly on my Mac and Desktop.

Great job.

**Comment by TheGoldenXY** [comment] 2016-07-27 18:53
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1042

/closed

**Closed by TheGoldenXY** 2016-07-27 18:53 UTC
Labels: duplicate
