### ISSUE TITLE
[REQUEST] Show Userinfo every X minutes

### ISSUE THREAD

**Issue by c0rrre** [PokemonGoF/PokemonGo-Bot#1134] opened 2016-07-27 05:55 UTC
### Expected Behavior
Show the userinfo from the start every X minutes (with a paremeter in config).
So you can track which level ur trainer is and how many items he got.

like for example in this bot:

![image](https://cloud.githubusercontent.com/assets/5563418/17165250/63e47b72-53cf-11e6-8c05-892217c2b855.png)

### Actual Behavior
shows the userinfo once at startup

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ironbishop** [comment] 2016-07-27 06:28
duplicate of #70

**Closed** 2016-07-27 06:35 UTC
