### ISSUE TITLE
Stuck in an ignore/re-encounter pokemon loop

### ISSUE THREAD

**Issue by J102030** [PokemonGoF/PokemonGo-Bot#892] opened 2016-07-26 00:07 UTC
### Expected Behavior
Run away from a pokemon specified not to catch in config, and ignore it in the wild

### Actual Behavior
Runs away from pokemon and re-encounters it immediately, becoming stuck in the loop

[20:02:16] A Wild Pinsir appeared! [CP 26] [Potential 0.33]
[20:02:16] IV [Stamina/Attack/Defense] = [1/0/14]
[20:02:26] A Wild Pinsir appeared! [CP 26] [Potential 0.33]
[20:02:26] IV [Stamina/Attack/Defense] = [1/0/14]
[20:02:29] Scanning area for objects....
[20:02:29] Walking from (40.77358622693521, -73.97256994250726) to (40.7743, -73.973248) 0.10km
[20:02:33] Something rustles nearby!
[20:02:33] A Wild Pinsir appeared! [CP 26] [Potential 0.33]
[20:02:33] IV [Stamina/Attack/Defense] = [1/0/14]
[20:02:37] A Wild Pinsir appeared! [CP 26] [Potential 0.33]
[20:02:37] IV [Stamina/Attack/Defense] = [1/0/14]
[20:02:40] Scanning area for objects....
[20:02:40] Walking from (40.773598039606476, -73.97258686540222) to (40.7743, -73.973248) 0.10km
[20:02:43] Something rustles nearby!
[20:02:44] A Wild Pinsir appeared! [CP 26] [Potential 0.33]
[20:02:44] IV [Stamina/Attack/Defense] = [1/0/14]
[20:02:47] A Wild Pinsir appeared! [CP 26] [Potential 0.33]
[20:02:47] IV [Stamina/Attack/Defense] = [1/0/14]

### Steps to Reproduce
Specify a pokemon to never catch in config, and encounter it

**Comment by MikeDX** [comment] 2016-07-26 00:09
Duplicate of #878 ?

**Comment by J102030** [comment] 2016-07-26 00:12
Yes, my apologies. Please close and refer to #878

**Comment by MikeDX** [comment] 2016-07-26 00:19
No need to apologise :)

**Closed** 2016-07-26 00:22 UTC
