### ISSUE TITLE
RuntimeError: Stopped at Pokestop and did not find experience

### ISSUE THREAD

**Issue by brumie** [PokemonGoF/PokemonGo-Bot#758] opened 2016-07-25 05:16 UTC
as title says

"RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours."

my account just fine but keeps getting kicked out by bot after updating c5a7109 to 586a0dc

**Comment by malachi21** [comment] 2016-07-25 05:22
I can confirm this problem. It's happening on the latest Dev.

**Comment by J102030** [comment] 2016-07-25 05:25
Same problem experienced

**Comment by TheSavior** [comment] 2016-07-25 05:37
I would love to track down what this problem is. If anyone else has some insight, that would be very helpful.

This message is triggered from here: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/seen_fort_worker.py#L102

**Comment by fsegouin** [comment] 2016-07-25 06:00
The bot no longer walks. We get soft banned because it's teleporting itself too quickly.

**Comment by TheSavior** [comment] 2016-07-25 06:02
I don't think thats the problem because restarting the script immediately lets it start working again.

**Comment by TheSavior** [comment] 2016-07-25 06:06
Hmm. That may be the problem. Working on some math.

**Comment by malachi21** [comment] 2016-07-25 06:10
Let us know. I'll decrease my speed

**Comment by hklcf** [comment] 2016-07-25 06:14
same here

![default](https://cloud.githubusercontent.com/assets/410302/17092018/02bba162-5272-11e6-879a-df47e62c459c.png)

335a0aa9a6e57fef17d0865b2f404e0ca785124b

**Comment by TheSavior** [comment] 2016-07-25 06:14
Fix: https://github.com/PokemonGoF/PokemonGo-Bot/pull/762

**Comment by kaise123** [comment] 2016-07-25 06:23
I'm still having this issue even with the fix merged. It's not 'walking' anywhere, just teleporting from one PokeStop to the next. App works fine.

**Comment by malachi21** [comment] 2016-07-25 06:28
I can confirm kaise's problem. It is literally teleporting. That's gonna fuck us FAST.

**Comment by TheSegfault** [comment] 2016-07-25 06:46
#762 fix didn't worked here.

**Comment by malachi21** [comment] 2016-07-25 06:50
#721 doesn't work either.

**Comment by MikeDX** [comment] 2016-07-25 07:20
had to roll back to 97b01b4 to get the bot running again. Was this pull request tested before it was merged? I had the issue appear on the 2nd pokestop it visited

**Comment by SteffanLong** [comment] 2016-07-25 07:26
Please switch to master branch. We're still working on fixing this issue.

**Comment by dmateusp** [comment] 2016-07-25 09:06
@TheSavior I think your last merge solved that issue ? can you confirm ?

**Comment by TheSavior** [comment] 2016-07-25 09:08
I believe it should have fixed this

**Closed by TheSavior** 2016-07-25 09:08 UTC
