### ISSUE TITLE
MoveToMapPokemon / MoveToFort cycling

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4128] opened 2016-08-17 00:14 UTC
### Actual Behavior
move_to_map_pokemon is cycling again (last release seem to have solved it):
1)  [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter]
2) [MoveToFort] [INFO] [moving_to_fort]
3) [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards]
then 1) again...

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/JTUPEe98

### Output when issue occurred
http://pastebin.com/AfUcZhgw

### Other Information
OS: OSX Maverick
Branch: dev
Git Commit: aaaa4807299fc7647a76fd3ba9829664b96f88a7
Python Version: Python 2.7.12

**Comment by k4n30** [comment] 2016-08-17 00:24
@Gurzeh can you verify your commit please

**Comment by Gurzeh** [comment] 2016-08-17 00:31
you mean
git fetch upstream

**Comment by k4n30** [comment] 2016-08-17 03:20
All good mate, it just wasn't linking to a commit.  It will be fixed in #4115

**Comment by k4n30** [comment] 2016-08-17 03:38
Duplicate of #4113

**Closed by k4n30** 2016-08-17 03:38 UTC
Labels: Duplicate, Waiting on Merge
