### ISSUE TITLE
[MoveToMapPokemon] Sometimes pokemon is only encountered but not caught

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#4167] opened 2016-08-17 17:22 UTC
### Expected Behavior

All bots move to same pokemon and catch it.

### Actual Behavior

Sometimes some bots move to the pokemon but do not catch it. The log says only encountered pokemon and then it moves on to the next.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

All bots run the same config but only 3 out of 4 catch.

**Comment by avexus** [comment] 2016-08-17 18:12
how did you set your config?
did you set: always_catch: true?

**Comment by jane0815** [comment] 2016-08-17 18:20
Yes, config file can't be the problem as i use it with all my bots. When something rare appears i start them all, usually have only 1 running, then they all walk towards the same VIP pokemon but sometimes not all catch it. They go to the pokemon, encounter it and then walk to the next one. When i notice fast enough i restart the bot and it walks to the VIP again and usually catches it.

**Comment by supergithubo** [comment] 2016-08-17 18:45
Make sure the number of pokeballs is above the min_ball property of the MoveToMapPokemon task.

**Comment by jane0815** [comment] 2016-08-17 19:17
I set the limit to 1 so this can not be the problem:
  
`        "min_ball": 1,`

**Comment by Raiven66** [comment] 2016-08-17 19:19
Actually this happened to me too and I thought I fcked something up while fiddling with MoveToMap. No idea what the cause is though or how to replicate it. I'm thinking it might have something to do with randomness of pokemon encounters, that it just somehow happened that the pokemon did not appear for an encounter...

**Comment by keugnu** [comment] 2016-08-17 19:34
The pokemon was already caught within 400 meters or the pokemon actually despawned before the bot could get there.

**Comment by Raiven66** [comment] 2016-08-17 19:44
despawned no, the bot checks
400meters no, I checked

**Comment by jane0815** [comment] 2016-08-17 19:45
No. It was a Lapras, the only one on the whole map. 

The bot also caught it after it was restarted so despan is not possible too.

**Comment by keugnu** [comment] 2016-08-17 20:27
Could you edit the OP with a snippit of your log where this is happening as well as your config?

**Comment by k4n30** [comment] 2016-08-18 13:16
@jane0815 This is not the first time you have not followed the issue template. Please start using it properly and stop sending our users on wild goose chases to help you because you were too lazy to fill in a bit of extra detail. If you don't start using the template I'm going to start closing your issues without fail

**Closed by k4n30** 2016-08-18 13:16 UTC
