### ISSUE TITLE
Bot jumps between two locations (dev)

### ISSUE THREAD

**Issue by DanielVolz** [PokemonGoF/PokemonGo-Bot#816] opened 2016-07-25 13:53 UTC
### Expected Behavior
Normal walking.

### Actual Behavior

Jumps between the same two locations.
### Steps to Reproduce
Run bot from dev branch

### Other Information
OS: OSX

<img width="949" alt="screenshot 2016-07-25 15 51 27" src="https://cloud.githubusercontent.com/assets/3275994/17103693/dd603a5a-527f-11e6-8005-29f8717657f1.png">

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
5a195bfb2b3f01099f6db2851186a84d14767c4e

**Comment by Nihisil** [comment] 2016-07-25 13:54
I have same behaviour :(

**Comment by EjjE101** [comment] 2016-07-25 14:07
your bag is full see #804 #807

**Comment by Nihisil** [comment] 2016-07-25 14:11
@EjjE101 

`[21:28:32] [#] Bag Storage: 306/350`

and 

`"mode": "all"`

So, bag is not full and I'm in `all` mode.

**Comment by veynor** [comment] 2016-07-25 14:11
[16:03:46] [#] Bag Storage: 219/350
Doing the same thing as above.
and mode: "all"

**Comment by iggut** [comment] 2016-07-25 14:38
Same here.
One of two things happen:
1. Same as above. After running for 10min to an hour it just keep saying moving from point A to point B and keep repeating the same route from A to B in that order.
2. Runs fine and then after a couple min just stays at Walking to Pokestop and just hangs there until Ctrl + C is pressed then it catches a pokemon or arrives at stop and spins doing fine for a stop or two and back and hanging at a walking to.

Can't figure it out bag and pokemon are not full.

**Comment by maddo7** [comment] 2016-07-25 19:17
Could this be because of a session timeout so the pogo servers don't respond properly anymore? Maybe it's a fix to re-login if that happens.

**Comment by iggut** [comment] 2016-07-25 19:18
relogin fixes it right away, but the issue is still there so no overnight botting

**Comment by veynor** [comment] 2016-07-25 19:52
For me my bag was actually full, due to levelup items not showing in the item count

**Comment by iggut** [comment] 2016-07-25 19:57
not me, lvl up items show up fine and I am under the limit

**Comment by linanqiu** [comment] 2016-07-26 01:16
I tried expanding the cell size to 50 (instead of the original 5) and now it works. I got a feeling it's got to do with the step limit

**Comment by J102030** [comment] 2016-07-26 03:37
I get this error on mode=poke, but not on mode=all

**Comment by J102030** [comment] 2016-07-26 04:00
It seems that the destination point is fixed for each of these jumps.

May be coincidence, but the longitude value of the destination matches the longitude of my location in config file..

**Comment by BartKoppelmans** [comment] 2016-07-26 13:58
Having the same problem. The jumps always move the same distance up and down, independent of the set location. It only happens in mode 'poke'. Perhaps some problem with calculations?

**Comment by alvarogzp** [comment] 2016-07-26 19:36
this is fixed now

**Comment by TheGoldenXY** [comment] 2016-07-28 22:24
This issue has been fixed in latest `dev` branch.

/closed

**Closed by TheGoldenXY** 2016-07-28 22:24 UTC
Labels: bug
