### ISSUE TITLE
Completely and utterly lost.

### ISSUE THREAD

**Issue by Matthewill** [PokemonGoF/PokemonGo-Bot#1946] opened 2016-07-31 00:05 UTC
I'm sorry for this but i'm stuck at installing Pip and i'm lost on what to do after installing python

**Comment by ysholqamy** [comment] 2016-07-31 00:16
I can help. What's your OS?

**Comment by Matthewill** [comment] 2016-07-31 00:21
windows 10

**Comment by ysholqamy** [comment] 2016-07-31 00:32
Ok. go to [https://pip.pypa.io/en/stable/installing/](url) and download the file at get-pip.py. Then hit the start button and search for **command prompt**. Using the command prompt  type  `cd /path/to/the/downloaded/file ` then `python get-pip.py` . This will install pip, happy hunting!

**Comment by ysholqamy** [comment] 2016-07-31 00:32
the href of the above link is broken, copy and paste it into your url bar instead of clicking on it

**Comment by ysholqamy** [comment] 2016-07-31 00:34
you still have to install protobuf, let me know if you are still struggling with the bot.

**Comment by Orrielel** [comment] 2016-07-31 00:46
Shift and Right click in the folder where get-pip.py is located will open up the command prompt in that location, skipping the need to cd.

**Comment by Matthewill** [comment] 2016-07-31 00:50
Okay still getting nothing, I downloaded python and extracted everything into my portable Hard Drive. Which is E, into a folder named Pokemon GO into another folder named Python. The whole pip.py thing just isn't clicking to me.

**Comment by ysholqamy** [comment] 2016-07-31 00:53
Open a command prompt and type python. Paste here the results please

**Comment by Matthewill** [comment] 2016-07-31 00:55
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Melvin>Python
'Python' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Melvin>

**Comment by ysholqamy** [comment] 2016-07-31 00:59
small p python not Python.

**Comment by Matthewill** [comment] 2016-07-31 01:00
same thing

**Comment by ysholqamy** [comment] 2016-07-31 01:06
hit start button, search for power shell and paste the following `[Environment]::SetEnvironmentVariable("Path", "$env:Path;E:\Python\;E:\Python\Scripts\", "User")`
this assumes that the Python installation folder is located at E:\ and is named Python. Afterwards open a new command prompt and type python and paste the results here

**Comment by Matthewill** [comment] 2016-07-31 01:09
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Melvin>python
'python' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Melvin>

**Comment by ysholqamy** [comment] 2016-07-31 01:11
Where is your python installation folder located?

**Comment by ysholqamy** [comment] 2016-07-31 01:12
is E:\Python the installation folder or a folder which includes the installation folder? by installation folder I mean the one resulted from running the python installer

**Comment by Orrielel** [comment] 2016-07-31 01:12
Could check it manually by going to `Control Panel –> System Properties –> Environment Variables` and select PATH in the bottom list and click edit.
It should be `E:\Python;E:\Python\Scripts` at the end.

**Comment by ysholqamy** [comment] 2016-07-31 01:13
it should be called something like python27 or python35

**Comment by ysholqamy** [comment] 2016-07-31 01:19
Good job, it is working now! close this command prompt. as @Orrielel said, Shift right-click in the folder where you downloaded get-pip.py and the type `python get-pip.py`

**Comment by Matthewill** [comment] 2016-07-31 01:24
That was my whole issue I couldn't figure out how to download it. The link took me to this page with a whole bunch of data but I wasn't sure what to do with it

**Comment by ysholqamy** [comment] 2016-07-31 01:27
right-click save link as

**Comment by Matthewill** [comment] 2016-07-31 01:30
name it get-pip.py into the python folder?

**Comment by ysholqamy** [comment] 2016-07-31 01:31
save it to E:\

**Comment by Matthewill** [comment] 2016-07-31 01:35
Saved it to E. But shift right click just does a normal right click action

**Comment by Orrielel** [comment] 2016-07-31 01:37
It wont work if you have any folders or files selected.

**Comment by Matthewill** [comment] 2016-07-31 01:38
still not working

**Comment by ysholqamy** [comment] 2016-07-31 01:40
Ok, right click on the get-pip.py then click properties then copy the its path or location on disk then open a new command prompty and type `cd paste the path you just copied` and then type `python get-pip.py`

**Comment by ysholqamy** [comment] 2016-07-31 01:51
just type `cd E:\` and press enter then type `python get-pip.py`

**Comment by Matthewill** [comment] 2016-07-31 01:52
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Melvin>cd E:\python get-pip.py
The system cannot find the path specified.

C:\Users\Melvin>cd E:\

C:\Users\Melvin>python get-pip.py
python: can't open file 'get-pip.py': [Errno 2] No such file or directory

C:\Users\Melvin>

**Comment by Matthewill** [comment] 2016-07-31 01:54
okay, remember my python is in a folder could that be it?

**Comment by ysholqamy** [comment] 2016-07-31 01:54
just type `e:` and then type `python get-pip.py`

**Comment by Matthewill** [comment] 2016-07-31 01:55
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Melvin>cd E:\python get-pip.py
The system cannot find the path specified.

C:\Users\Melvin>cd E:\

C:\Users\Melvin>python get-pip.py
python: can't open file 'get-pip.py': [Errno 2] No such file or directory

C:\Users\Melvin>E:

E:\>python get-pip.py
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 673kB/s
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 1.4MB/s
Installing collected packages: pip, wheel
  Found existing installation: pip 7.0.1
    Uninstalling pip-7.0.1:
      Successfully uninstalled pip-7.0.1
Successfully installed pip-8.1.2 wheel-0.29.0

E:\>

**Comment by ysholqamy** [comment] 2016-07-31 01:55
horray!

**Comment by Matthewill** [comment] 2016-07-31 01:57
okay so, the installation instructions did NOT say it that simply. or maybe i'm bad at instructions. Either way thanks for not showing your frustration with my inability to breeze through this lol

**Comment by ysholqamy** [comment] 2016-07-31 01:58
lol no problem. next you have to install [protobuf](https://github.com/google/protobuf/releases/download/v3.0.0-beta-4/protoc-3.0.0-beta-4-win32.zip)

**Comment by Matthewill** [comment] 2016-07-31 01:59
is git not necessary?

**Comment by ysholqamy** [comment] 2016-07-31 02:03
it is necessary. but i think installing git is straightforward just google it and you will be ok.

**Comment by ysholqamy** [comment] 2016-07-31 02:06
follow the instructions [here](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation)

**Comment by Matthewill** [comment] 2016-07-31 02:13
installed everything, how do I change from master to dev?

**Comment by ysholqamy** [comment] 2016-07-31 02:20
Open the command prompt, cd to the location you cloned the project into and type `git checkout dev` press enter then type `git pull origin dev`

**Comment by ysholqamy** [comment] 2016-07-31 02:20
And are you sure you added protoc.exe to afolder in your PATH?

**Comment by Matthewill** [comment] 2016-07-31 02:22
no. is my path not E?

**Comment by ysholqamy** [comment] 2016-07-31 02:25
No it is probably not. For now, place protoc.exe in your python installation folder

**Comment by Matthewill** [comment] 2016-07-31 02:27
Okay did that.  Now for the Git. 
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Melvin>E
'E' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Melvin>E:

E:\>git checkout dev
fatal: Not a git repository (or any of the parent directories): .git

E:\>
my git things are in a folder named Git. so do I E:\Git\?

**Comment by ysholqamy** [comment] 2016-07-31 02:30
No. Did you run the git clone command?

**Comment by ysholqamy** [comment] 2016-07-31 02:31
In the instructions the last part

**Comment by Matthewill** [comment] 2016-07-31 02:34
Damnit I did but i accidentally put it in C. Is that okay?

**Comment by ysholqamy** [comment] 2016-07-31 02:37
Yea it is. Open new command prompt and type c: and then cd PokemonGoBot and then type the commands i mentioned above to change to dev

**Comment by Matthewill** [comment] 2016-07-31 02:42
but everything is in E and the go bot is within like 3 subfolders should I bring it up? also PyYAML isn't installing because it can't find Python

**Comment by ysholqamy** [comment] 2016-07-31 02:47
If you want to move it to E, you can. But you do not have to. I am not sure what is the problem with PyYAML, maybe it is looking for python in the c: but I am not sure

**Comment by Matthewill** [comment] 2016-07-31 02:54
all it says is Python version 2.7 required. which was not found in the registry

**Comment by Matthewill** [comment] 2016-07-31 02:57
fixed that never mind

**Comment by Matthewill** [comment] 2016-07-31 03:14
Okay. i think everything was done...now i don't know how to start it

**Comment by gregtampa** [comment] 2016-07-31 07:08
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG

**Closed by gregtampa** 2016-07-31 07:08 UTC
