### ISSUE TITLE
No creation location-username.json

### ISSUE THREAD

**Issue by Critically** [PokemonGoF/PokemonGo-Bot#778] opened 2016-07-25 09:13 UTC
So, bot not create "location-username.json" in web folder, another files  catchable-username.json and inventroy-username.json created successfully.

**Comment by Saturate** [comment] 2016-07-25 09:19
I can confirm this, If you make the file yourself it will update it with the location data correctly :-)

**Comment by Critically** [comment] 2016-07-25 09:21
Can u say, what need to do ?

**Comment by dmateusp** [comment] 2016-07-25 09:21
@Reaver01 maybe something for you ?

**Comment by Reaver01** [comment] 2016-07-25 09:25
I don't understand what the issue is. Can you please provide some more info and maybe the console log?  
Is the bot itself actually not creating the files? or is it just not reading them?  
Also please provide if you are running this through a webserver, or just opening the file.

**Comment by dmateusp** [comment] 2016-07-25 09:27
I think the problem comes from the fact that it does not create the "location-username.json" file but it DOES update it if it's there in the first place. Is it right @Saturate ?

**Comment by Critically** [comment] 2016-07-25 09:30
So, i'm creating this file myself, and it's working, loool. Thanks all.

**Comment by Saturate** [comment] 2016-07-25 10:06
@dmateusp Correct, it does not create the file, but if you manually create it, it updates it just fine. Should be easy to fix :)

**Comment by dmateusp** [comment] 2016-07-25 10:11
Still should not be closed until the file is created automatically !

**Comment by tpmodding** [comment] 2016-07-25 10:23
think i have the Same here, afte git pull today it doesnt work, following output:
Z:\Downloads\PokemonGo-Bot>python pokecli.py
[2016-07-25 12:20:52] [x] PokemonGO Bot v1.0
[2016-07-25 12:20:52] [x] Configuration initialized
[2016-07-25 12:20:52] [x] The location given using -l could not be parsed. Checking for a cached location.
[2016-07-25 12:20:52] [x] Parsing cached location...
No cached Location. Please specify initial location.

**Comment by kemko** [comment] 2016-07-25 10:30
Its https://github.com/PokemonGoF/PokemonGo-Bot/pokemongo_bot/stepper.py#L110 and  https://github.com/PokemonGoF/PokemonGo-Bot/pokemongo_bot/stepper.py#L120. location and last-location only if they already exists.

**Comment by zx900930** [comment] 2016-07-25 10:38
Does someone have this problem after add the location-username.json?

`VM101 main.js:145  Uncaught TypeError: Cannot read property 'length' of undefined`

```
main.js:145
 for (var i = 0; i < data.cells.length; i++)
```

**Comment by silelmot** [comment] 2016-07-25 10:52
i created the location-.json by myself, but there are no entrys in it.
also catchable-.json, created by the script , ony has {} in it

**Comment by Critically** [comment] 2016-07-25 10:53
It'a ok, Catchable empty too

**Comment by surfaace** [comment] 2016-07-25 11:46
sommeone need to create the code required which creates the files listed below if they are empty or not exists

web\location-%USERNAME%.json

**Comment by Sekhmet** [comment] 2016-07-25 11:56
Is anyone working on it atm? If not, I can do this.

**Comment by surfaace** [comment] 2016-07-25 11:57
@Sekhmet please do, and create a pull request once done

**Comment by heihachi** [comment] 2016-07-25 12:29
https://github.com/PokemonGoF/PokemonGo-Bot/pull/800

anyone want to test this?

**Comment by surfaace** [comment] 2016-07-25 13:51
fixed in #800

**Comment by Critically** [comment] 2016-07-25 13:51
So, when I create location-username.json myself it's working any time, then in BOT i get error:

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "c:\pokebot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "c:\pokebot\pokemongo_bot\stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "c:\pokebot\pokemongo_bot\stepper.py", line 88, in _walk_to
    alt, False)
  File "c:\pokebot\pokemongo_bot\stepper.py", line 111, in _work_at_position
    with open(user_web_location, 'w') as outfile:
IOError: [Errno 22] invalid mode ('w') or filename: u'web/location-username.com.json'

**Closed** 2016-07-25 13:50 UTC
Labels: bug, waiting on changes

**Comment by Saturate** [comment] 2016-07-25 13:56
@Critically it has to be ` location-Critically.json` for it to work :) if that is your username.

**Comment by Critically** [comment] 2016-07-25 14:07
I change my real username ))) In file user name correct
