### ISSUE TITLE
pokebal already 0 but still use it

### ISSUE THREAD

**Issue by fari-99** [PokemonGoF/PokemonGo-Bot#2243] opened 2016-08-01 15:42 UTC
### Expected Behavior
use another ball

### Actual Behavior
[22:38:26]  A Wild Rhyhorn appeared! [CP 49] [Potential 0.64]
[22:38:26] IV [Attack/Defense/Stamina] = [15/7/7]
[22:38:30] Using Pokeball (chance: 100.00%)... (0 left!)
[22:38:35] Lured pokemon at fort afee005c1ec94567b727a8f74202dec0.16

### Steps to Reproduce
run the bot

### Other Information
OS: Windows 10
Git Commit: 494bc055543c3cb674cca781ec545311d3c9bad1
Python Version: Python 2.7.12

**Comment by fari-99** [comment] 2016-08-01 16:53
Btw this is dev issue.

**Comment by xorinzor** [comment] 2016-08-01 18:13
Duplicate of #1755, #1893, #2043, #2097 and #2075

Please check for an existing issue next time

**Comment by fari-99** [comment] 2016-08-02 02:33
@xorinzor hey, i still got the problem after changing catch_rate, i think the problem is when pokeball and greatball is 0 and you have VIP pokemon it still using pokeball or greatball, because it's not VIP pokemon it's still using pokeball.

btw where is the mode for farm and catch? should i delete the catch task to farm? or create a function so after i have some amount of pokeball and greatball it became normal again?

**Closed** 2016-08-05 08:34 UTC
