### ISSUE TITLE
Problem with location with minus

### ISSUE THREAD

**Issue by olivierg13** [PokemonGoF/PokemonGo-Bot#1045] opened 2016-07-26 20:19 UTC
### Expected Behavior
Should work with location = "37.8059,-122.4289" for example

### Actual Behavior
Shows errors:
`Location Found: 37.8059,-122.4289
[13:15:39] [x] The location given using -l could not be parsed. Checking for a cached location.
[13:15:39] [x] Parsing cached location...
No cached Location. Please specify initial location.`

### Steps to Reproduce
Set up a normal location: "37.8059,122.4289"
It works.
Set up an inferior to zero location (US etc...): "37.8059,-122.4289"
It does not work

### Other Information
OS: MAC OS X 10.11.6
Git Commit: 3364aa39d50dbc7e34541007e66ed67ab4071c35

Thank you in advance :)

**Comment by jovobe** [comment] 2016-07-26 21:12
This is a problem caused by an update in the pgoapi from tejado. It can easily be fixed by pinning the pgoapi pip to the "v1.1.0" tag. Change the first line in the requirements.txt in this way:
`-e git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi`
and update your pip with
`pip install -r requirements.txt`

**Comment by olivierg13** [comment] 2016-07-26 21:24
Thanks @jovobe 
Unfortunately I got the following error after modification of the requirements.txt:
`Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-fRJQCR-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-inf`

**Comment by olivierg13** [comment] 2016-07-26 21:30
Actually running pip install with the flag `--ignore-installed six` fixed my problem.
Just in case for others.

**Comment by surfaace** [comment] 2016-07-26 23:51
Commit has been reverted, please repull. #1065

**Closed by surfaace** 2016-07-26 23:51 UTC
Labels: bug
