### ISSUE TITLE
Latest DEV doesn't find pokemons?

### ISSUE THREAD

**Issue by Roydeking52** [PokemonGoF/PokemonGo-Bot#2033] opened 2016-07-31 09:21 UTC
I have the latest DEV and it looks like that it doesn't find pokemon?

Here is the log:

[10:57:53]  Starting PokemonGo Bot.... 
[10:57:54]  [x] Next egg incubates in 1.58 km 
[10:57:54]  No lucky eggs... skipping evolve! 
[10:57:55]  -- Recycled 10x Hyper Potion (keeps only 30 maximum)  
[10:57:56]  -- Recycled 10x Revive (keeps only 30 maximum)  
[10:57:56] Walking from (52.21115700000001, 5.9699231) to [52.21115700000001, 5.9699231] 0.00km
[10:57:58] Walking from (52.21115700000001, 5.9699231) to [52.21295700000001, 5.9699231] 0.20km
[10:58:57]  [x] Next egg incubates in 1.52 km 
[10:59:35]  Server seems to be busy or offline - try again - 1/5 
[11:01:01] Walking from (52.21295700000001, 5.9699231) to [52.21295700000001, 5.9717231] 0.12km
[11:02:56] Walking from (52.21295700000001, 5.9717231) to [52.21115700000001, 5.9717231] 0.20km
[11:02:59]  [x] Next egg incubates in 1.32 km 
[11:06:12] Walking from (52.21115700000001, 5.9717231) to [52.209357000000004, 5.9717231] 0.20km
[11:07:04]  [x] Next egg incubates in 1.05 km 
[11:09:16] Walking from (52.209357000000004, 5.9717231) to [52.21115700000001, 5.9717231] 0.20km
[11:11:01]  [x] Next egg incubates in 0.81 km 
[11:12:17] Walking from (52.21115700000001, 5.9717231) to [52.21295700000001, 5.9717231] 0.20km
[11:15:10]  [x] Next egg incubates in 0.58 km 
[11:15:25] Walking from (52.21295700000001, 5.9717231) to [52.21295700000001, 5.9699231] 0.12km
[11:17:28] Walking from (52.21295700000001, 5.9699231) to [52.21115700000001, 5.9699231] 0.20km
[11:19:09]  [x] Next egg incubates in 0.33 km 

Can somebody explains to me what is going wrong?

**Comment by Mello-Yello** [comment] 2016-07-31 09:40
Did you set up the task to catch pokemons?
Share your config file

**Comment by Roydeking52** [comment] 2016-07-31 09:47
"catch_pokemon": true,
    "forts": {
      "spin": false,
      "move_to_spin": false,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": true,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": "all",
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0.8, "release_below_iv": 0.0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },    
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
        

Catch pokemon: true

**Comment by berong91** [comment] 2016-07-31 10:01
Please update your config up to the config.json.example, or try to put this script right after gmapkey:
````
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
````

**Comment by nallsnowblind** [comment] 2016-07-31 10:12
i have the same problem; exacly same log. 
Bot walks back and forth and does not catch anything even with newest config

**Comment by honnes** [comment] 2016-07-31 10:15
Your issue seems to be duplicate of #2031 .

For me, removing this from the config did the trick:

      {
        "type": "FollowSpiral"
      }

PS. Some other people said that changing Evolve_All to false did it for them, but that didn't work for me.

**Comment by nallsnowblind** [comment] 2016-07-31 10:21
without FollowSpiral it just does nothing for me

**Closed** 2016-08-05 08:32 UTC
