### ISSUE TITLE
TO DEVS

### ISSUE THREAD

**Issue by Jcolomar** [PokemonGoF/PokemonGo-Bot#5850] opened 2016-12-23 17:28 UTC
Hi. As u know, a new API model wil be soon ready. That means while pogodevs RE are still try crack the last API, pokefarmer RE's has done, and they'll rent hash service to others by supscription. My question is if this proyect will adapt to this new service, or not.

After few days testing pokefarmer desktop, only can say this proyect still is best ever bot made. More configurable, thousands of options and very easy to use.

Thx to all

**Comment by MerlionRock** [comment] 2016-12-24 02:29
That would depend how the API is implemented and how the subscription is done.

But don't expect it to be free anymore. Most likely would expect you to purchase the hashing key yourself and input into the config file. Something alone the line.

Forget it. PF is just trying to be monopoly the whole bot thing.

**Comment by MerlionRock** [comment] 2016-12-24 02:32
By the way, correction, pogodevs RE team are with PF. Basically they agree with their renting model.

This renting service will be the model they will be doing for now till end.

**Comment by Jcolomar** [comment] 2016-12-27 21:22
Pokemongo-map is ready. U can patch urself very easyly to work with last api 0.51 before. 

In requirements.txt:
(remove) git+https://github.com/pogodevorg/pgoapi.git#egg=pgoapi
(add) git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi

Add api.activate_hash_server on search.py line 498.

And it works.

Waiting changes here!!!

Greetings

**Comment by MerlionRock** [comment] 2016-12-28 09:55
Currently trying to get it work with the new api, if anyone know how to solve incompatible websocket issue, please let me know.

**Comment by Jcolomar** [comment] 2016-12-28 09:56
u mean bot or map?

**Comment by MerlionRock** [comment] 2016-12-28 10:06
bot

**Comment by Jcolomar** [comment] 2016-12-28 10:26
ohhh nice. I was looking for also. But my knowledge in pyhon is 0.

**Comment by camnomis** [comment] 2016-12-28 11:48
@pogarek that is a known issue, see #5830

**Comment by Jcolomar** [comment] 2016-12-28 12:28
C:\Juegos\PokemonGO\PokemonGo-Bot>pokecli.py
Traceback (most recent call last):
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokecli.py", line 51, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "C:\Juegos\PokemonGO\PokemonGo-Bot\pokemongo_bot\__init__.py", line 148
    self.api.activate_hash_server('XXXXXXXXXXXXXXX')
    ^
IndentationError: unexpected indent

**Comment by pogarek** [comment] 2016-12-28 13:20
@camnomis  thanks. commenting the line makes bot running, but not moving - as it is in the #5830  .

**Comment by Jcolomar** [comment] 2016-12-28 16:06
Now with fresh install only have errors if i add self.api.activate_hash_server('XXXXXXXX')

**Comment by pogarek** [comment] 2016-12-28 18:09
merging all my comments to share what I've done, to get bot running:

1. bought a key
2. changed -e git+https://github.com/pogodevorg/pgoapi.git#egg=pgoapi to git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi in requirements
3. changed "from pgoapi.protos.POGOProtos.Networking.Requests.RequestType_pb2 import RequestType" to "from pgoapi.protos.pogoprotos.networking.requests.request_type_pb2 import RequestType" in api_wrapper.py
4. changed "from pgoapi.protos.POGOProtos.Enums import BadgeType_pb2" to "from pgoapi.protos.pogoprotos.enums import badge_type_pb2" in init.py
5. added PGoApi.activate_hash_server(self,'mykey')  in api_wrapper.py after line 41 (PGoApi.__init__(self, device_info=device_info)) 
6. commented out line 152 (response = request.call()) in pgoapi.py in python installation (<python)_root>\Lib\site-packages\pgoapi\pgoapi.py) 
7. commented line mentioned in #5830
8. fixed captcha on phone.

bot works. :)

**Comment by pogarek** [comment] 2016-12-29 00:05
@camnomis by default (at least on windows) requirements.txt has -e flag on pgoapi git, which was copying pgoapi python lib to src directory (if I recall corecctly).
Removing -e installas pgoapi lib to the python directory. 
So I don't know how python get installed on mac, but I would search there..

**Comment by MerlionRock** [comment] 2016-12-29 03:52
@camnomis I make the changes at [userdir]/PokemonGo-Bot/src/pgoapi/pgoapi

But I still end up with 400 : Bad request, error = Invalid hash request. Please follow all requirements/guidelines.

**Comment by MerlionRock** [comment] 2016-12-29 03:53
This project might need some major changes... including updating pokemon.json to support all Gen 2 pokemons.

Major tasks ahead....

**Comment by pogarek** [comment] 2016-12-29 06:40
@MerlionRock look for the error in the console : you should see a path to pgoapi.py there.
Yes, project will need changes like:
* exposing hash key to config
* Ditto, Pichu and other gen2 pokemons support for bot and web server (attaching my files with both of them added, but not for web server: [newpoke.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/676689/newpoke.zip))
* #5830 probably
* and others, which I didn't get affected yet

**Comment by pogarek** [comment] 2016-12-29 14:34
Update: I've created a pokemon.json with 251 pokemons. I used the script above (which uses https://fevgames.net/pokedex/) and merged it (by another script - mine in this case) with data from http://www.serebii.net/pokemongo
Enjoy the results:  [newpoke2.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/677275/newpoke2.zip)

**Comment by camnomis** [comment] 2016-12-29 15:21
Fresh install and it seems to work, however with the API check it's still saying 0.45.0, I had assumed adding `git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi` in the requirements would mean its the newer API, or is 0.45.0 still the latest to be cracked?

**Comment by pogarek** [comment] 2016-12-29 16:48
To have 0.51 used by bot, you need to do all of below:
1. buy a key
2. change requirements.txt
3. activate the key , as has been described above. 
Skipping any of above will provide 0.45 api

**Comment by camnomis** [comment] 2016-12-29 19:13
Key was purchased from 

https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer (HashBuddy 500 RPM)

requirements.txt has `git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi` does it need the -e?

have added:

`PGoApi.__init__(self, device_info=device_info)
	    PGoApi.activate_hash_server(self,'***************') `

Error message is now:

`Traceback (most recent call last):
  File "pokecli.py", line 51, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/xxxxx/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in <module>
    from .api_wrapper import ApiWrapper
  File "/Users/xxxxx/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 45
    PGoApi.activate_hash_server(self,'***************') 	
    ^
`

**Comment by stricnina** [comment] 2016-12-29 19:16
must be:
PGoApi.__init__(self, device_info=device_info)
PGoApi.activate_hash_server(self,'***************')

AFTER, not the same line

**Comment by camnomis** [comment] 2016-12-29 20:06
It is on a different line, the formatting of the post made it go on the same line in the comments.

There is a difference, not sure if this a Max thing or not, were as init.py is __init__.py

**Comment by Jcolomar** [comment] 2016-12-29 21:41
Thanks to pogarek first all for his help in discord to make bot run. Now to ppl want use Webserver with this bot, he makes also some changes and i add new pictures of new pokemons. 
[web.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/677906/web.zip)

Images of new pokemons in web:
![pokedex](https://cloud.githubusercontent.com/assets/21227457/21555337/9acbfed6-ce17-11e6-87ee-6fd23c29aa21.png)

Full new pokemons:
![full pokedex](https://cloud.githubusercontent.com/assets/21227457/21555368/e2f71cf4-ce17-11e6-8b97-5067507c3974.png)

Enjoy

**Comment by pogarek** [comment] 2016-12-29 22:14
After a few hours with learning a git , I've made a fork of bot and webui..
So you can get all, changed, files at https://github.com/pogarek/PokemonGo-Bot/commits/dev

**Comment by MerlionRock** [comment] 2016-12-30 02:46
@pogarek your files, changing  of hash key, is it at config?

**Comment by MerlionRock** [comment] 2016-12-30 03:01
Okay. Got it working except on the warning on Nidoran. 

@pogarek Are you able to do a pull request for all the changes and @camnomis able to commit the changes?

**Comment by pogarek** [comment] 2016-12-30 06:44
@MerlionRock I have no idea.. For me the issue was captcha and new TOS, that I needed to accept in a game on a phone..
Someone mentioned on discord, that removing RandomPause and RandomAlivePause from config helps .

**Comment by camnomis** [comment] 2016-12-30 10:01
@pogarek thanks for the effort, hopefully its working better for others than me.

Changed everything as per your commits and its still saying I am using 0.45.0, checked buddyauth portal and the key is still showing UNUSED/INACTIVE

**Comment by pogarek** [comment] 2016-12-30 10:03
@camnomis if you use pokefarmer key, then it won't work for hashing.

**Comment by dogeatdog** [comment] 2016-12-30 18:06
Thanks pogarek ! I cloned your fork (dev branch) and purchased a 150 RPM hashkey. My bot is now running :) Seems to work fine (for now :)).

**Comment by MerlionRock** [comment] 2016-12-31 03:02
@pogarek Sadly it doesn't work. I wonder if it's related to OS since @camnomis and myself are both on Mac OS.

Any Mac user here get the bot going (and moving?)

**Comment by pogarek** [comment] 2016-12-31 07:28
@MerlionRock @camnomis  It seems that you have different errors..
Can you try to backup your configs for bot and webui, delete everything from bot directory (do a backup if you want), clone my dev repo and try again ?

**Comment by camnomis** [comment] 2016-12-31 12:24
@pogarek I have spun up a new ubuntu VM (not sure what OS you are using), I have cloned

`git clone https://github.com/pogarek/PokemonGo-Bot`

But that is not showing any new commits, are they still on your local repo?

**Comment by camnomis** [comment] 2016-12-31 12:37
It works!

**Comment by MerlionRock** [comment] 2016-12-31 17:12
Great! I'll try tomorrow. Now we need someone to commit the changes....

**Comment by MerlionRock** [comment] 2017-01-01 14:58
It work for me too! Great. Err... anything I can do so that the changes can be committed to here?

**Comment by venney** [comment] 2017-01-06 07:44
Server busy or offline, reconnecting in 989 seconds
Does someone know what this is?

What I did,
1. git clone -b dev https://github.com/pogarek/PokemonGo-Bot
2. ./setup.sh -i 
3. Bought the key and input into "configs/config.json"
4. ./run.sh

=== Log ===
(17673) wsgi starting up on http://127.0.0.1:4000
[2017-01-06 15:41:22] [PokemonGoBot] [INFO] Setting start location.
[2017-01-06 15:41:22] [PokemonGoBot] [INFO] Favorite location found: linko ([u'25.059919', u'121.368751'])
[2017-01-06 15:41:22] [PokemonGoBot] [INFO] Location found: Linko (25.059919, 121.368751, 8)
[2017-01-06 15:41:22] [PokemonGoBot] [INFO] Now at (25.059919, 121.368751, 8)
[2017-01-06 15:41:22] [PokemonGoBot] [INFO] Login procedure started.
[2017-01-06 15:41:24] [PokemonGoBot] [INFO] Server busy or offline, reconnecting in 989 seconds
^C[2017-01-06 15:41:27] [PokemonGoBot] [INFO] Bot caught SIGINT. Shutting down.

**Comment by pogarek** [comment] 2017-01-06 08:05
Probably it doesn't matter, but key should be in auth.config .
Have you used a bot before in the same network that you are trying now ?

**Comment by venney** [comment] 2017-01-06 08:15
Yes, I used a bot before and quite familiar with it.
Sorry that key is actually in configs/auth.json as you said. ( I type the post too fast without checking).

I also checked that if my key is not activated.
By registering my email address to buddyhash website, the log changed JUST ONCE:
=== log ===
[2017-01-06 16:03:52] [PokemonGoBot] [INFO] Login procedure started.
[2017-01-06 16:04:01] [PokemonGoBot] [INFO] Login successful.
[2017-01-06 16:04:01] [PokemonGoBot] [INFO] 
[2017-01-06 16:04:01] [PokemonGoBot] [INFO] Server busy or offline, reconnecting in 1009 seconds
=== log ===

Then all "server busy or offline" when running ./run.sh

Any idea ? 
Many thanks.

**Comment by dogeatdog** [comment] 2017-01-06 08:18
I get that message a lot myself, but a much lower retry time (around 50-90
seconds). I always contributed this to the hashing server being overloaded.
Not true?

Op vr 6 jan. 2017 om 09:15 schreef venney <notifications@github.com>

**Comment by venney** [comment] 2017-01-06 08:21
@dogeatdog , So... I just try to run ./run.sh periodically 50-90 seconds, it will work then?

**Comment by dogeatdog** [comment] 2017-01-06 08:26
Yes, but it might take a couple of retries. It will also disconnect a lot
of times while the bot is running, but will reconnect eventually. I never
had this issue with the unforked version, and since the main difference is
the hashing server, I can only assume this is the reason.

I'll check my config and let you know the setting to change the time out
shortly .

Op vr 6 jan. 2017 om 09:21 schreef venney <notifications@github.com>

**Comment by pogarek** [comment] 2017-01-06 08:29
At this moment of time it seems that there is an outage on hashing servers...

**Comment by venney** [comment] 2017-01-06 08:34
Thanks for the information.
So basically, what I did is already enough to run the bot, right?
Many thanks for the help & contribution. :-)

**Comment by pogarek** [comment] 2017-01-06 08:36
Yes.
Np. :-) I'm newbie to python, but I know another languages . And changes needed to be done wasn't to much difficult - I just had time in a proper moment :-)

**Comment by pogarek** [comment] 2017-01-06 08:43
Servers seems to be back online

**Comment by dogeatdog** [comment] 2017-01-06 08:47
Yup, confirmed. Working here as well. I hope they do get their capacity up soon, since this is now a paid service, one might expect a stable server from the guys providing the hashing server(s).

**Comment by venney** [comment] 2017-01-06 08:49
After two "login succesfully" & "server offline...", the bot starts at 3rd trial.
it's running now and captured one pokemon... 
Great and thanks for the help.
Hooray!

**Comment by dogeatdog** [comment] 2017-01-06 08:52
@pogarek I'm not too familiar with github, but is it possible to enable the Issues on your fork ? Keeping communication about your fork through comments on an old issue on the original project is not ideal :)

**Comment by venney** [comment] 2017-01-06 09:05
Is it possible to run the same hash key ( 150RPM ) by two bots ?
Does anyone try this?

**Comment by pogarek** [comment] 2017-01-06 09:08
@dogeatdog I didn't know that I can/need to enable it - I thought it is restricted to main repo. It is enabled now - thanks for the idea
@venney  I have one 150RPM key used by 3 bots.

**Comment by MerlionRock** [comment] 2017-01-07 02:28
@venney Base on output by a different bot, per bot estimate using approximately 30RPM. Therefore, per key could likely used by 5 accounts. But this estimation is done base on a different bot. This bot might be using more RPM.

**Comment by pogarek** [comment] 2017-01-10 05:40
Guys, the main repo is updated now (included my changes) and it supports 0.51. :-)

**Comment by MerlionRock** [comment] 2017-01-10 07:28
@pogarek Finally!

**Comment by venney** [comment] 2017-01-10 16:03
Mmm... Pogarek's fork was working fine yesterday. 
Now I got API check error. Does anyone know what I miss?

========
0.51.0
 We have detected a Pokemon API Change. The current API version 0.45.0 is no longer supported. Exiting...
Wed Jan 11 00:00:47 CST 2017 Pokebot  Stopped.
========

**Comment by pogarek** [comment] 2017-01-10 16:52
HI Venney
The main repo (https://github.com/PokemonGoF/PokemonGo-Bot) got updated with mine (and other changes). So 0.51 is still working, but also a kill switch got implemented :-) It can be disabled in config:
>"check_niantic_api": false

**Comment by venney** [comment] 2017-01-10 17:15
Hi Pogarek,
Thanks. I will try. ( Currently, I copied your fork from other computer & not update it. Ha)
I knew this settings but we already download 0.51 stuffs from Internet when doing setup.sh -i. 
So I think the checking should be passed.
But it turned out not from your saying. Why?

**Comment by pogarek** [comment] 2017-01-10 17:21
the check was done before 0.51 got implemented. I mean the check was awaiting to be merged. 
I think it is , actually, ok that sends the message. User then try to investigate and discover that buying a hashing key is required ( I mean for new user) :)

**Comment by MerlionRock** [comment] 2017-01-11 02:03
@pogarek I agree. Just want to check if 0.45 still working?  Is there a way to set the bot to run 0.45 for those who are adventurous?

Actually we can just update the installation script to include hash key input so that user will know that a hash key is required. In fact, you can also add in disclaimer that hash key is provided by 3rd party.

**Comment by pogarek** [comment] 2017-01-11 05:03
I don't think that bot will work in 0.45 ("check_niantic_api": false + no hash key provided). 
Installation script ? do you mean .\setup.sh and windows_bat\PokemonGo-Bot-Configurator.bat ?

**Comment by MerlionRock** [comment] 2017-01-12 01:26
@pogarek Yes, I mean "./setup.sh -i" and PokemonGo-Bot-Configurator.bat

**Comment by pogarek** [comment] 2017-01-12 05:41
Yeah, we will update that.

**Comment by dogeatdog** [comment] 2017-01-12 17:47
Uhm.. I appreciate it and all, but after the last setup.sh -u I couldn't get it to work anymore.

So, I created a fresh one : 

`git clone -b master https://github.com/pogarek/PokemonGo-Bot`

Copied my old config.json and auth.json (with the hash key).

Added the check_niantic_api : false line in config.json

And now all I get is : 

```
2017-01-12 18:43:53] [pgoapi.pgoapi] [ERROR] Request for new Access Token failed! Logged out...
[2017-01-12 18:43:53] [PokemonGoBot] [INFO] Not logged in, reconnecting in 63 seconds

```

Any idea on how I can fix this ? It worked perfectly until the last update..

**Comment by pogarek** [comment] 2017-01-12 17:55
check #5867

**Comment by dogeatdog** [comment] 2017-01-12 18:00
Aha, missed that one. Just did another clean clone, this time from the main repo master. And now it's just the Server busy or offline message, which is normal when the hashing servers are working their asses off.. I'll let it run for a while and check later. If it still doesn't work, I'll give #5867 a try. Thanks for the support !

**Comment by venney** [comment] 2017-01-13 05:14
I stay with Pogarek's working fork before. :-)
One simple question here:
Do you use the same IP (computer) to run more than 1 bot ? Is it safe?
( I ran two BOTs in two different computers now )

**Comment by pogarek** [comment] 2017-01-13 05:53
I have 3 bots on one cmputer

**Comment by venney** [comment] 2017-01-13 07:02
@pogarek , Cool. Thanks.

**Closed** 2017-02-02 08:07 UTC
