### ISSUE TITLE
Not transferring  Pokémon, bag full

### ISSUE THREAD

**Issue by boscorelly** [PokemonGoF/PokemonGo-Bot#5528] opened 2016-09-18 13:54 UTC
Hi,
I activated the transfert feature, but it doesn't work.
I set keep_best_iv/cp but never transferring. 
So, bag is full. When I start the bot, it says "can not catch". But no transferring. 
Up to date. 
Any idea ?

**Comment by Anakin5** [comment] 2016-09-18 14:14
No config, no logs = no help

**Comment by xiatianyu** [comment] 2016-09-18 16:05
Duplicate of #5507 and #5480.

> Before you create an Issue, please check the following:
> 
> 2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? If so, comment on that issue instead rather than creating a new issue.
> 4. All Issue sections MUST be completed to help us determine the actual problem and find its cause

**Comment by Gobberwart** [comment] 2016-09-18 22:16
Closed. Insufficient information provided. Please use the issue template in future.

**Closed by Gobberwart** 2016-09-18 22:16 UTC
