### ISSUE TITLE
followPath not work

### ISSUE THREAD

**Issue by buzzo123** [PokemonGoF/PokemonGo-Bot#3035] opened 2016-08-08 09:48 UTC
i think followpath configuration not work,
i use this json:

```
  "auth_service": "",
  "username": "",
  "password": "",
  "location": "",
  "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.example.json"
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    }
```
}

but there is no line in the terminal only this:

```
2016-08-08 11:47:48,813 [PokemonGoBot] [INFO] 
2016-08-08 11:47:50,642 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-08 11:47:50,643 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-08 11:47:50,643 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-08 11:47:50,643 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-08 11:47:51,264 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-08 11:47:51,885 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-08 11:47:51,887 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 7.83 km
```

**Comment by SGColdSun** [comment] 2016-08-08 09:53
What does your path file look like? How did you generate it?

**Comment by dogrocker** [comment] 2016-08-08 09:55
path file will be.

```
[
  {"location": "", ""},
  {"location": "", ""},
  {"location": "", ""},
  {"location": "", ""},
]
```

**Comment by buzzo123** [comment] 2016-08-08 09:59
[
	{"location": "44.811245, 12.008759"},
	{"location": "44.809, 12.009886"},
	{"location": "44.805468, 12.011721"},
	{"location": "44.809, 12.009886"}
]

**Comment by buzzo123** [comment] 2016-08-08 10:00
@dogrocker  mmm i try but the program not works

**Comment by ckrmml** [comment] 2016-08-08 19:41
same here, this config just wrecks the bot

**Comment by Nik0lashka** [comment] 2016-08-08 22:46
@buzzo123 same for me. @SGColdSun it just doesn't show any [FollowPath] messages and coordinates of trainer don't change according path.

**Comment by buzzo123** [comment] 2016-08-09 07:55
how can we contact a dev for this?

**Comment by Nik0lashka** [comment] 2016-08-09 09:45
@buzzo123 "FollowPath" appears in three files in repo and aepecially in follow_path.py as class declaration. In https://github.com/PokemonGoF/PokemonGo-Bot/blob/5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d/pokemongo_bot/cell_workers/follow_path.py there are mentioned three contributors @TheSavior @douglascamata @achretien, may be they know.

**Comment by buzzo123** [comment] 2016-08-09 09:53
@douglascamata  thanks!

**Comment by nifloutch** [comment] 2016-08-09 18:09
@douglascamata  I think I found something. 

I compared the two files follow_spiral.py and follow_path.py and in the file follow_path.py there is no call to emit_event method. 

(from follow_spiral.py : )
```
self.emit_event(
                    'position_update',
                    formatted="Walking from {last_position} to {current_position} ({distance} {distance_unit})",
                    data={
                        'last_position': self.bot.position,
                        'current_position': (point['lat'], point['lng'], 0),
                        'distance': dist,
                        'distance_unit': 'm'
                    }
                )
```

I don't know how to correct it properly (and I'm not sure it's even the problem) but maybe this information can help one of the author if the file. 

I'm currently testing an adaptation of a wild copy/paste of this call, but again, I'm not sure how to implement it properly (since there is some variables in follow_spiral that are not documented and I don't know what there are for)

Hope it helps

**Comment by douglascamata** [comment] 2016-08-09 19:06
@nifloutch the event won't update the location, it will just print stuff. But thx for the finding!

**Comment by jomarocas** [comment] 2016-08-10 21:57
Ok any implementation of this, i tried but no working, im no programmer in python and is dificult for me, thanks is any pull request

**Comment by checkmate1982** [comment] 2016-08-11 20:00
Hi all. I'm currently looking into this issue as I'm also intressed in using FollowPath.
In the __init__.py file states that for each row in the path.json file, if the location is a {Lat, Long} it will print out "Coordinates found in passed in location, not geocoding". So this message is by design, the path.json is being read and no error has been found.
Only the data doesn't get used. I'll check back when I get more into this.

**Comment by leadboots5** [comment] 2016-08-11 21:10
I am going to close this as the thread is very fragmented. The initial guy who opened the issue didn't post an actual issue. The one guy who did post an error just had his path file formatted in correctly. So I'm not sure what the issue is.

For what its worth I am using FollowPath and it functions.

If anyone is having issues with FollowPath please open a new thread describing the issue you are having to get some fresh eyes on it without all the noise.

**Closed by leadboots5** 2016-08-11 21:10 UTC
Labels: approved, needs clarification
