### ISSUE TITLE
Keep 1 best xPokemon, based on cp

### ISSUE THREAD

**Issue by Takkwon** [PokemonGoF/PokemonGo-Bot#1514] opened 2016-07-28 23:17 UTC
### Expected Behavior
Only release the pokemon I have in the Release{xxxxx.....xxx}
For example if I have two gyarados 1500CP I want to keep them both. And I want to keep other future duplicate catches that are rare.

### Actual Behavior
In the log:
Keep 1 best xPokemon, based on cp
and then it transfer ALL duplicates I didn't specify in the Release{xxxxx....xxx}

### Other Information
It's since the release_pokemon=true update. here is my config.json:
  "release_pokemon": true,
    "release": {
      "any": {"release_below_cp": 200, "release_below_iv": 0.9, "logic": "or"},
      "any": {"keep_best_cp": true},
      "Magikarp": { "release_below_cp" :130, "release_below_iv": 0.89, "logic": "and" },
      "Caterpie": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Weedle": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Diglett": { "release_below_cp": 158, "release_below_iv": 0.8, "logic": "and" },
      "Metapod": { "release_below_cp": 168, "release_below_iv": 0.8, "logic": "and" },
      "Kakuna": { "release_below_cp": 170, "release_below_iv": 0.8, "logic": "and" },
      "Rattata": { "release_below_cp": 204, "release_below_iv": 0.8, "logic": "and" },
      "Abra": { "release_below_cp": 208, "release_below_iv": 0.8, "logic": "and" },
      "Zubat": { "release_below_cp": 280, "release_below_iv": 0.9, "logic": "and" },
      "Chansey": { "release_below_cp": 235, "release_below_iv": 0.8, "logic": "and" },
      "Pidgey": { "release_below_cp": 300, "release_below_iv": 0.9, "logic": "and" },
      "Rattata": { "release_below_cp": 245, "release_below_iv": 0.9, "logic": "and" },
      "Spearow": { "release_below_cp": 240, "release_below_iv": 0.8, "logic": "and" },
      "Meowth": { "release_below_cp": 264, "release_below_iv": 0.8, "logic": "and" },
      "Krabby": { "release_below_cp": 276, "release_below_iv": 0.8, "logic": "and" },
      "Sandshrew": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Poliwag": { "release_below_cp": 365, "release_below_iv": 0.9, "logic": "and" },
      "Horsea": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Gastly": { "release_below_cp": 280, "release_below_iv": 0.8, "logic": "and" },
      "Ekans": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
      "Shellder": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
      "Vulpix": { "release_below_cp": 290, "release_below_iv": 0.8, "logic": "and" },
      "Voltorb": { "release_below_cp": 292, "release_below_iv": 0.8, "logic": "and" },
      "Geodude": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
      "Doduo": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
      "Onix": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
      "Mankey": { "release_below_cp": 307, "release_below_iv": 0.8, "logic": "and" },

**Comment by friederschueler** [comment] 2016-07-28 23:29
Please close this issue, this is not a bug. The question the program asks is: Shall I release this pokemon? If you use `"logic": "or"` then the pokemon will be released if one of both conditions are true. So your 1500CP pokemon have lower IV than 0.9 and will be released.
Switch to "and" and everything will work as expected.

**Closed** 2016-07-28 23:38 UTC
