### ISSUE TITLE
[ENHANCEMENT]: Dont revisit a pokestop recently visited < 5 minutes ago

### ISSUE THREAD

**Issue by MikeDX** [PokemonGoF/PokemonGo-Bot#710] opened 2016-07-24 18:57 UTC
### Expected Behavior

Ignore pokestop visited since 5 minutes ago

### Actual Behavior

Bot tries to re-visit a pokestop since 5 minutes ago if it is the "furthers away" set by the steps config value.

### Steps to Reproduce

Run bot in location with two pokestops a fair distance apart and large step count

**Comment by phupabegim** [comment] 2016-07-24 19:13
I have the same issue. My bot is staying at the same location revisiting the same PokeStop over 10 times now.

**Comment by MikeDX** [comment] 2016-07-24 21:55
I think this will be resolved with the new walker class, so I guess we have to just cope with it for now. Maybe do what I did and move your bot to a location with a much higher density of pokestops

**Comment by surfaace** [comment] 2016-07-24 22:06
actually its not a 'bug' but more of a enhancement as there currently is no option or code that should prevent this.

Adding it as enhancement

**Comment by surfaace** [comment] 2016-07-24 22:11
duplicate of #10

**Closed by surfaace** 2016-07-24 22:11 UTC
Labels: duplicate, enhancement

**Comment by MikeDX** [comment] 2016-07-24 22:14
How can this not be a bug just because there is no code to prevent it? You could apply that logic to all bugs! It is a bug because the bot should not do it.
