### ISSUE TITLE
"release" "any": {"keep_best_iv": 1}, not working properly

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#4621] opened 2016-08-23 15:04 UTC
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
YES
2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? If so, comment on that issue instead rather than creating a new issue.
YES
3. Are you running on the `master` branch? We work on the `dev` branch and then add that functionality to `master` when it is stable. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.
DEV

### Expected Behavior
Got every Pokemon with best IV

### Actual Behavior
Got some 10x this same Pokemons.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://www.wklej.org/hash/b14ba84bc91/

### Output when issue occurred
2016-08-23 16:30:06,007 [PokemonGoBot] [INFO] #16 Pidgey: (CP 10, IV 0.53) | (CP 112, IV 0.56) | (CP 142, IV 0.4) | (CP 111, IV 0.51) | (CP 144, IV 0.44) | (CP 110, IV 0.49) | (CP 73, IV 0.33) | (CP 90, IV 0.38) | (CP 57, IV 0.29) | (CP 189, IV 0.67) | (CP 10, IV 0.29) | (CP 59, IV 0.44) | (CP 91, IV 0.4) | (CP 24, IV 0.33) | (CP 131, IV 0.09) | (CP 78, IV 0.56) | (CP 26, IV 0.62) | (CP 78, IV 0.4) | (CP 56, IV 0.2) | (CP 10, IV 0.47) | (CP 23, IV 0.24) | (CP 10, IV 0.4) | (CP 72, IV 0.29) | (CP 162, IV 0.47) | (CP 25, IV 0.53) | (CP 23, IV 0.24) | (CP 53, IV 0.09) | (CP 112, IV 0.6) | (CP 75, IV 0.38) | (CP 58, IV 0.47) | (CP 88, IV 0.31) | (CP 60, IV 0.53) | (CP 39, IV 0.16) | (CP 10, IV 0.29) | (CP 57, IV 0.36) | (CP 90, IV 0.36) | (CP 10, IV 0.6) | (CP 109, IV 0.42) | (CP 95, IV 0.56) | (CP 124, IV 0.38) | (CP 145, IV 0.07) | (CP 68, IV 0.09) | (CP 56, IV 0.24) | (CP 73, IV 0.38)

### Steps to Reproduce
run a bot and get info about pokemons in bag

### Other Information
OS: Debian SID
Branch: DEV
Git Commit: 382a406cccfa68c96c576c6f1d4f3ea9d81deb7d
Python Version: 2.9.7

**Comment by cindyma210** [comment] 2016-08-23 15:52
try increasing the min_free_slot

**Comment by takenek** [comment] 2016-08-23 15:58
Cool but for what is option 
"release" 
"any": {"keep_best_iv": 1},
if he ignore this?

I think change this is not good idea. For me this is a BUG.

**Comment by askovpen** [comment] 2016-08-23 16:41
Transfer pokemon task run if:
config->tasks->TransferPokemon->min_free_slot obtain

**Comment by iamjsed** [comment] 2016-08-23 16:57
Add min_free_slot in your TransferPokemon task to trigger release.

{
            "type": "TransferPokemon",
            "config": {
                "transfer_wait_min": 1,
                "transfer_wait_max": 4,
                **"min_free_slot": 999**
            }
        }

**Comment by mjmadsen** [comment] 2016-08-23 17:31
Current dev branch only transfers pokemon if we're past our minimum free slots or we go past our timed transfer bit. Not a bug.

**Comment by takenek** [comment] 2016-08-23 18:00
@iamjsed thanks, i put "min_free_slot": 999 and working good.

Best Regards!
TaKeN

**Comment by takenek** [comment] 2016-08-23 18:16
@iamjsed  thanks, i put "min_free_slot": 999 and my all pokemons deleted.... now i got 0 pokemons...
Best Regards!
TaKeN

**Comment by Naiters** [comment] 2016-08-23 18:52
Now the TranferPokemon task has transfered all but 10 of my Pokemon. 
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }

I am also using the keep_best_iv: 1 criterion.

**Comment by takenek** [comment] 2016-08-23 18:55
Interesting so why i got so many and when i put 999 he delete all?
Mayby this is problem with dev/master branch, @mjmadsen say something about dev working other than master... mayby i back to master...

**Comment by Naiters** [comment] 2016-08-23 18:56
I got:  'Keeping best of "all" based on iv' for the first time and then it exchanged all but 10 of my Pokemon. Wtf is that. I'm on the enwest dev too...

**Comment by MartinTerp** [comment] 2016-08-23 18:57
something about this commit isnt right
https://github.com/PokemonGoF/PokemonGo-Bot/commit/0d2c391d8729ced307953bcb6ad7bbbcaacd6a00

i have:
      "any": {"keep_best_cp": 1},

and it released all but 1, so i have 1 pokemon now

**Comment by Naiters** [comment] 2016-08-23 18:59
Somebody has trolled us all :D

**Comment by mjmadsen** [comment] 2016-08-23 19:07
#4615 was merged while I was asleep. The behavior was changed for "any" to get rid of ALL pokemon except those that meet the criteria. In the case of "any": {"keep_best_cp": 1} you'll only keep your best CP pokemon. 

In contrast, before any applied to each type of pokemon. This is a major behavior change that will break most people's config.

**Comment by MartinTerp** [comment] 2016-08-23 19:09
@mjmadsen so it should be "any" that results in each type? or do i need it set to "all"?
/confused

**Comment by mjmadsen** [comment] 2016-08-23 19:09
Based on the comments, "any": was supposed to stay the same and "all" was supposed to use your whole bag. It doesn't look like that's the case.

**Comment by MartinTerp** [comment] 2016-08-23 19:11
Rollback! :+1: :)

**Comment by danielsdian** [comment] 2016-08-23 19:24
Got the same thing here. lost all but the top IV pokemon.

**Comment by LitRidl** [comment] 2016-08-24 00:38
It was me who broke the things and a little bit of stealth-style fallback-driven code architecture of `TransferPokemon`.
#4639 should fix it.

**Comment by mjmadsen** [comment] 2016-08-24 00:45
#4639

**Closed by mjmadsen** 2016-08-24 00:45 UTC
Labels: Bug

**Comment by takenek** [comment] 2016-08-24 15:01
Cool - so someone tell me what i must config now to got every pokemon with the best IV nothing else and rest go to candys?
Because now i completly don't understand this...

**Comment by takenek** [comment] 2016-08-24 15:05
I got now:
    "release": {
      "// Keep no more than 1 best IV pokemon for every pokemon type": {},
      "any": {"keep_best_iv": 1},
    },

And i got 20 pidgey....
I use newlatest version of Master branch: de78768634795d1733f8d7e1902d57c238cf0207

**Comment by mjmadsen** [comment] 2016-08-24 15:15
What is your pokebag count and what do you have "min_free_slot" set to?

**Comment by takenek** [comment] 2016-08-24 15:57
min_free_slot is set to 5
and Pokemon Bag: 106/250

But before some patch everything working good.
I got "any": {"keep_best_iv": 1}, and everything working good, i got each one pokemon with the best IV in bag rest go to Candys...

**Comment by mjmadsen** [comment] 2016-08-24 16:04
Since min_free_slot is 5, you won't transfer until you hit at least 245 in your bag.

There is a PR in to have a time based transfer too (force transfer every x minutes).

**Comment by takenek** [comment] 2016-08-24 16:26
Ok so please tell me what i must do.
I want "Keep no more than 1 best IV pokemon for every pokemon type.
3 days ago eveything working good...

**Comment by mjmadsen** [comment] 2016-08-24 16:30
min_free_slot 999

**Comment by takenek** [comment] 2016-08-24 17:52
When i do this my all pokemons deleted and got 0 pokemons... this is bad ideas...

**Comment by mjmadsen** [comment] 2016-08-24 17:54
You tried it again and it did the same thing?

**Comment by takenek** [comment] 2016-08-24 17:56
No i don`t try - when last time someone tell me to do this i lost my all pokemons.....

**Comment by MartinTerp** [comment] 2016-08-24 18:06
they fixed it in the latest dev commit, "any": {"keep_best_iv": 1}, works, i use it (or, just with cp)

**Comment by takenek** [comment] 2016-08-24 18:09
So if i use master i need to wait to merge from dev ? Or master got patch too already?
