### ISSUE TITLE
[Snipe Bug] Bot continues to search for pokemon also after capture

### ISSUE THREAD

**Issue by MatteCarra** [PokemonGoF/PokemonGo-Bot#4143] opened 2016-08-17 07:53 UTC
### Expected Behavior
Bot should walk to the Pokemon, capture it and then go to an other pokemon

### Actual Behavior
Bot walks to the pokemon, captures it and then walks to the same pokemon until it reaches the exact position!

### Output when issue occurred
```

2016-08-17 09:40:01,997 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Golduck, 0.06km, left (10 minutes, 11 seconds)
2016-08-17 09:40:07,858 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Golduck appeared! [CP 430] [Potential 0.56] [A/D/S 4/9/12]
2016-08-17 09:40:11,274 [PokemonCatchWorker] [INFO] [threw_berry] Threw a Razz Berry! Catch rate with Greatball is now: 48.47
2016-08-17 09:40:11,276 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatball, with chance 48.47 (57 left)
2016-08-17 09:40:12,151 [PokemonCatchWorker] [INFO] [pokemon_vanished] Golduck vanished!
2016-08-17 09:40:50,992 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Golduck, 0.04km, left (9 minutes, 22 seconds)
........
 2016-08-17 09:41:00,153 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter] Encountered Pokemon: Golduck
```
### My config
```
{
    "auth_service": "",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "encrypt_location": "",
    "websocket_server": false,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": true,
          "time": "22:00",
          "duration":"10:00",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 15,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Rattata,Weedle,Zubat,Caterpie,Kakuna,Metapod,Diglett,Meowth",
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0.1,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 100,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 0  },
            "Super Potion":   { "keep" : 5  },
            "Hyper Potion":   { "keep" : 60 },
            "Revive":         { "keep" : 60 },
            "Razz Berry":     { "keep" : 60 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 1000,
          "min_time": 60,
          "min_ball": 10,
          "prioritize_vips": true,
          "snipe": false,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,

            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,

            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,

            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,

            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,

            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,

            "Pikachu": 600,
            "Raichu": 1000,

            "==========Semi Rare==========": 0,
            "Porygon": 200,
            "Scyther": 200,
            "Jynx": 200,

            "==========Uncommon==========": 0,

            "Omanyte": 150,
            "Omastar": 500,

            "Seel": 300,
            "Dewgong": 500,

            "Grimer": 200,
            "Muk": 500,

            "Shellder": 200,
            "Cloyster": 500,

            "Gastly": 200,
            "Haunter": 500,
            "Gengar": 1000,

            "Onix": 600,

            "Drowzee": 600,

            "Hypno": 600,

            "Vulpix": 200,
            "Ninetales": 600,

            "Paras": 100,
            "Parasect": 500,

            "Growlithe": 200,
            "Arcanine": 700,

            "Tentacool": 200,
            "Tentacruel": 500,

            "Mankey": 150,
            "Primeape": 500,

            "Clefairy": 150,
            "Clefable": 500,

            "Jigglypuff": 150,
            "Wigglytuff": 500,

            "Venonat": 100,
            "Venomoth": 500,

            "Diglett": 200,
            "Dugtrio": 500,

            "Meowth": 250,
            "Persian": 500,

            "Psyduck": 150,
            "Golduck": 500,

            "Geodude": 100,
            "Graveler": 500,
            "Golem": 800,

            "Eevee": 200,
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,

            "Kabuto": 150,
            "Kabutops": 500,

            "Magikarp": 150,
            "Gyarados": 800,

            "Pinsir": 150,

            "Ponyta": 200,
            "Rapidash": 500,

            "Slowpoke": 200,
            "Slowbro": 500,

            "Magnemite": 250,
            "Magneton": 500,

            "Krabby": 100,
            "Kingler": 500,

            "Voltorb": 200,
            "Electrode": 500,

            "Exeggcute": 300,
            "Exeggcutor": 500,

            "Cubone": 300,
            "Marowak": 800,

            "Hitmonlee": 400,

            "Hitmonchan": 400,

            "Lickitung": 500,

            "Koffing": 200,
            "Weezing": 500,

            "Rhyhorn": 200,
            "Rhydon": 500,

            "Chansey": 800,

            "Tangela": 300,

            "Horsea": 200,
            "Seadra": 600,

            "Goldeen": 150,
            "Seaking": 500,

            "Staryu": 200,
            "Starmie": 800,


            "==========T1 Evolvers==========": 0,
            "Caterpie": 10,
            "Metapod": 10,
            "Butterfree": 500,

            "Kakuna": 10,
            "Beedrill": 500,

            "Pidgeotto": 10,
            "Pidgeot": 300,

            "==========T2 Evolvers==========": 0,
            "Nidoran F": 10,
            "Nidorina": 10,
            "Nidoqueen": 10,

            "Nidoran M": 10,
            "Nidorino": 10,
            "Nidoking": 10,

            "Oddish": 100,
            "Gloom": 200,
            "Vileplume": 600,

            "Poliwag": 200,
            "Poliwhirl": 400,
            "Poliwrath": 800,

            "Abra": 300,
            "Kadabra": 600,
            "Alakazam": 800,

            "Machop": 150,
            "Machoke": 400,
            "Machamp": 800,

            "Bellsprout": 100,
            "Weepinbell": 400,
            "Victreebel": 800

          }
        }
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 2,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"keep_best_cp": 2},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
```

### Other Information
OS: LUbuntu
Branch: master
Git Commit: 423e4dea72c0b04d8882ef90f03949fe3bf35ac2
Python Version: Python 2.7.9

**Comment by Raiven66** [comment] 2016-08-17 07:57
this is not connected to sniping but walking

**Comment by Raiven66** [comment] 2016-08-17 08:16
this is also somewhat not trivial to solve as MoveToMapPokemon, as the name says, takes care only of moving, not catching the pokemon. That is done by a different task. For now the pokemon is considered caught after it's location has been reached

As this is not a bug, but probably a feature request, i would propose adding it to http://feathub.com/PokemonGoF/PokemonGo-Bot
as a feature request

**Comment by Raiven66** [comment] 2016-08-17 10:19
exactly, so I would ignore this issue :P

**Comment by k4n30** [comment] 2016-08-17 11:05
I'm confused as to what the feature request is @Raiven66 ?

Also we're using github for feature requests, not feathub - https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#feature-requests

**Comment by Raiven66** [comment] 2016-08-17 11:59
well currently the bot walks with MoveToMap to the location of the pokemon. It is encountered(and caught) when in range though and not upon reaching the destination. As from what I looked at the code, it would not be trivial to stop pursuing the destination of the pokemon after it being caught and since the bot is working fine (just walks extra 50meters) as-is, I think this would be a nice to have thing rather than a bug/issue.

I would close this and file a feature request like
* [MoveToMapPokemon] stop going "the last mile" to a pokemon's location after it has been caught and switch to another

**Comment by k4n30** [comment] 2016-08-17 12:12
@Raiven66 I'll meet you half way, if you make the FR, I'll close this issue. Deal?

**Comment by Raiven66** [comment] 2016-08-17 12:14
As I am not overly in need of this, @MatteCarra would be the person for that :)

**Closed** 2016-08-17 13:07 UTC
