### ISSUE TITLE
Moving to two forts at same time

### ISSUE THREAD

**Issue by RomikB** [PokemonGoF/PokemonGo-Bot#3646] opened 2016-08-11 20:53 UTC
### Expected Behavior

move to single fort

### Actual Behavior

moving to two forts at same time

[20:46:29] Skipping Recycling of Items. 29 space left in bag.
[20:46:29] Moving towards pokestop Оса - 0.05km
[20:46:29] {'distance_unit': '', 'distance': '', 'current_position': (54.950352043462075, 20.224351399151676), 'last_position': (54.950336954651206, 20.224354216621542)}
[20:46:31] Skipping Recycling of Items. 29 space left in bag.
[20:46:31] Moving towards pokestop Тотемные Столбы - 0.05km
[20:46:31] {'distance_unit': '', 'distance': '', 'current_position': (54.95032408416211, 20.224337047230893), 'last_position': (54.950352043462075, 20.224351399151676)}
[20:46:33] Skipping Recycling of Items. 29 space left in bag.
[20:46:33] Moving towards pokestop Оса - 0.05km
[20:46:33] {'distance_unit': '', 'distance': '', 'current_position': (54.95034224412183, 20.22429766429274), 'last_position': (54.95032408416211, 20.224337047230893)}
[20:46:35] Skipping Recycling of Items. 29 space left in bag.
[20:46:35] Moving towards pokestop Тотемные Столбы - 0.05km
[20:46:35] {'distance_unit': '', 'distance': '', 'current_position': (54.950314209554655, 20.224278398973745), 'last_position': (54.95034224412183, 20.22429766429274)}
[20:46:36] Skipping Recycling of Items. 29 space left in bag.
[20:46:36] Moving towards pokestop Оса - 0.05km
[20:46:36] {'distance_unit': '', 'distance': '', 'current_position': (54.950376545727266, 20.224253236201463), 'last_position': (54.950314209554655, 20.224278398973745)}
[20:46:39] Skipping Recycling of Items. 29 space left in bag.
[20:46:39] Moving towards pokestop Тотемные Столбы - 0.05km

### Your config.json (remove your credentials and any other private info)
```
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 10,
          "item_filter": {
            "Pokeball":       { "keep" : 20 },
            "Greatball":      { "keep" : 35 },
            "Ultraball":      { "keep" : 55 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 35 },
            "Hyper Potion":   { "keep" : 80 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,

```

### Steps to Reproduce

use default config, run bot and wait some time (less or more)

### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by RedViper9** [comment] 2016-08-11 21:21
Changing your location manually and restarting the bot will get you out of the loop.

**Comment by RedViper9** [comment] 2016-08-11 21:58
I'm having trouble reproducing this error; however, reading through move_to_fort.py, line 60 ` if dist > Constants.MAX_DISTANCE_FORT_IS_REACHABLE:` suggests that the bot stops walking as soon as this line returns false.

MAX_DISTANCE is set to 40m, which indeed is the maximum reachable distance, but if the bot doesn't spin immediately and instead moves away, you may get stuck.

Two possible solutions I can see:
1) Set line 60 to take force one more step toward the fort:
```
if dist >= Constants.MAX_DISTANCE_FORT_IS_REACHABLE:
```
2) Reduce MAX_DISTANCE_FORT_IS_REACHABLE (PokemonGo-Bot/pokemongo_bot/constants.py) to something like 38.

I can so far only say that neither of these solutions breaks the bot. Let me know if it works for you.

**Comment by umbreon222** [comment] 2016-08-11 22:17
Having the same issues as described in OP. Tried, @RedViper9 's suggested code changes but the bug persists. I noticed it's only when the distances between the pokestops are the same, I'm guessing what would have to happen is that the bot would have to remember which stop it was originally walking to so when the forts are equidistant it knows which one it should step closer to.

**Comment by umbreon222** [comment] 2016-08-11 23:38
Duplicate of issues #3475 #3394 #3308

**Comment by exoji2e** [comment] 2016-08-11 23:52
I'm getting a similar issue, and applying both possible solutions presented above (setting constant to 38 and adding the =-sign) doesn't help. My issue has the same weird json print: 
[01:49:34] {'distance_unit': '', 'distance': '', 'current_position': (lon,lat), 'last_position': (lon,lat)}, but it just repeats this lines with new coordinates. I'm on master, with walk speed 4.16.

**Closed** 2016-08-12 00:01 UTC
Labels: duplicate

**Comment by k4n30** [comment] 2016-08-12 10:43
#3308 #3394 #3475 #3646 #3692 #3711 #3721
