### ISSUE TITLE
[ENHANCEMENT] Keep new unique Pokemons if found in farm mode

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#521] opened 2016-07-23 22:57 UTC
In farm mode, if found a new pokemon, then ignore the release rule and keep it.

**Comment by Aiyubi** [comment] 2016-07-24 07:57
Why should it? That is exactly what the release rules are designed for.

**Comment by akhilravichandran11** [comment] 2016-07-24 08:52
can we have this an option ? As some of us want to 'Catch em all'

**Comment by OrangeBonk** [comment] 2016-07-25 09:57
Sorry for my bad english.
But i find the way to keep new pokemon.
In first step u will need to setup ur config and release config.
In release config set CP and IV sorting by 0.
In config,json setup "initial_transfer" parameter depending on your level (for example im 21 level and have 850)
With this configuration bot will transfer "dublicated" pokemons by factor of CP.
They keep one unit every kind of pokemon even if it is pretty weak.
And that will keep pokemon with CP above than 850 (or ur parameter).
After transfering weak dublicated pokemon bot will cath every pokemon it they way.
And after restart will sort it again.
But here is the problem. I'm too lazy for restart the bot manually. And i think u too :)
In next step u have to create one another folder in bot main folder and named it like "test" "help" "111" etc.
In that folder create .js file and name it (im name it "30min.js).
Put there next code

`WScript.Sleep(1800000);`

After that create .bat file on ur destop and put there another code

`cls`
`:start`
`cd C:\**\PokemonGo-Bot`
`start python pokecli.py`
`cd *ur 30min.js folder*`
`start /b /wait 30min.js`
`taskkill  /im python.exe`
`goto start`

After starting the bat file the bot will sort ur pokemons by factor of CP and keep catch every pokemon. 
**1. If bot catch a pokemon what u never get before, it will keep them despite its level of CP.
2. If bot catch a pokemon what u have only one before, and they weakness than 850 CP but powerful that pokemon that u have before, bot will transfer old pokemon and replace that will new more powerfull pokemon**
After 30 minutes bot will automatically restart and repeate sorting and keep catching.
But here one drawback, u cant sort pokemons by IV.
For me it isn't problem, becouse i want first catch them all (i already have 80% of all pokemons for 2 days) and only the next step will be a give a fu*k about IV and other battle statistic.
I hope my litle instruction will help u in ur adventure!
Good luck, trainer ^_^

**Comment by ironbishop** [comment] 2016-07-28 10:31
duplicate of #604

**Comment by TheGoldenXY** [comment] 2016-07-28 22:21
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/604

/closed

**Closed by TheGoldenXY** 2016-07-28 22:21 UTC
Labels: enhancement, new feature
