### ISSUE TITLE
Bot throws pokeball even if there're none left

### ISSUE THREAD

**Issue by Ced4** [PokemonGoF/PokemonGo-Bot#2075] opened 2016-07-31 14:56 UTC
### Expected Behavior
Bot uses better ball or does not catch the pokemon

### Actual Behavior
Bot throws non-existing pokeball

> [16:42:54]  A Wild Tentacool appeared! [CP 300] [Potential 0.58]
> [16:42:54] IV [Stamina/Attack/Defense] = [4/10/12]
> [16:42:57] Using Pokeball (chance: 41.52%)... (-1 left!)
> [16:44:30] Something rustles nearby!
> [16:44:30]  A Wild Rattata appeared! [CP 65] [Potential 0.44]
> [16:44:30] IV [Stamina/Attack/Defense] = [5/9/6]
> [16:44:34] Using Pokeball (chance: 68.91%)... (-1 left!)
> [16:51:50] Something rustles nearby!
> [16:51:50]  A Wild Magikarp appeared! [CP 127] [Potential 0.64]
> [16:51:50] IV [Stamina/Attack/Defense] = [11/10/8]
> [16:51:54] Using Pokeball (chance: 46.87%)... (-1 left!)

### Steps to Reproduce
have no pokeballs and find a wild pokemon

### Other Information
newest Dev and CentOS 7

**Comment by xc-mezcal** [comment] 2016-07-31 17:19
Confirmed, I will do a fast fix for this issue.

**Comment by hobbes3** [comment] 2016-07-31 17:49
Simiarl to https://github.com/PokemonGoF/PokemonGo-Bot/issues/1985

**Comment by Parth6182** [comment] 2016-07-31 17:54
> Confirmed, I will do a fast fix for this issue.

How do we install the fix you create?

**Comment by xc-mezcal** [comment] 2016-07-31 18:06
Check this PR
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2113

**Comment by xorinzor** [comment] 2016-08-01 18:16
agreed with @hobbes3, duplicate of #2075

**Closed** 2016-08-05 08:33 UTC
