### ISSUE TITLE
Crash on launch in dev branch

### ISSUE THREAD

**Issue by sgitkene** [PokemonGoF/PokemonGo-Bot#1272] opened 2016-07-27 22:10 UTC
### Expected Behavior
Start walking towards a pokestop

### Actual Behavior
[00:04:51] Scanning area for objects....
[00:04:51] Walking from (4886673895734975231, 4886673885291154728) to [4.886425257326149e+18, 4.886414562853954e+18] 11101.88km
Traceback (most recent call last):
  File "pokecli.py", line 272, in <module>
    main()
  File "pokecli.py", line 238, in main
    bot.take_step()
  File "/home/max/PokemonGo-Bot/pokemongo_bot/__init__.py", line 47, in take_step
    self.process_cells()
  File "/home/max/PokemonGo-Bot/pokemongo_bot/__init__.py", line 67, in process_cells
    "catchable_pokemons": catchable_pokemons}, location)
  File "/home/max/PokemonGo-Bot/pokemongo_bot/__init__.py", line 204, in work_on_cell
    self.navigator.take_step()
  File "/home/max/PokemonGo-Bot/pokemongo_bot/spiral_navigator.py", line 85, in take_step
    point['lng']
  File "/home/max/PokemonGo-Bot/pokemongo_bot/cell_workers/utils.py", line 33, in distance
    return 12742 * asin(sqrt(a)) * 1000
ValueError: math domain error

### Steps to Reproduce
Start bot with location "Luzern" and cached location turned off.
Config:
{
    "auth_service": "google",
    "username": "xxx@gmail.com",
    "password": "xxx",
    "location": "Luzern Löwenplatz",
    "gmapkey": "xxx",
    "max_steps": 6,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,

### Other Information
OS: Archlinux
Git Commit: 15e0161d32c7a78c230c6e75cfd6867663c985d1

**Comment by sgitkene** [comment] 2016-07-27 22:12
this seems related to the coordinates not being passed correctly, like in #1263

**Comment by GRB** [comment] 2016-07-27 22:15
Exactly the same problem.

revert to a working commit,

git reset --hard 74e37de

**Comment by JonathanRosado** [comment] 2016-07-27 22:28
+1 Same issue

**Comment by stout01** [comment] 2016-07-27 22:36
I had the same issue, I did a reinstall of the requirements.txt and it is now working fine.

**Comment by GRB** [comment] 2016-07-27 22:40
you, it worked like he said.

Do:

c:\python27\scripts\pip.exe install -r requirements.txt --upgrade

and it will work again.

**Comment by Calcyfer** [comment] 2016-07-28 00:00
Correct, `c:\python27\scripts\pip.exe install -r requirements.txt --upgrade` is the fix for this.
The new version of the PgoAPI we use handles coordinates differently.

**Comment by zenety** [comment] 2016-07-28 00:26
Still having this issue. Tried reinstalling everything. (pip uninstall -r requirements.txt and then an install) But coordinates are still messed up.

Pgoapi-1.1.0 is the correct one?

**Comment by Calcyfer** [comment] 2016-07-28 00:38
Can you paste the first line of requirements.txt?

**Comment by zenety** [comment] 2016-07-28 00:51
@Calcyfer -e git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi

**Comment by Calcyfer** [comment] 2016-07-28 00:58
That's the right one.
Does /pokemongo_bot/__init__.py have `i2f` in it anywhere?
If not, what are the coordinates you are giving?

**Comment by zenety** [comment] 2016-07-28 01:03
Yes it does.

from cell_workers.utils import distance, get_cellid, encode, i2f

Coordinates are: 40.782771,-73.969303

**Comment by Calcyfer** [comment] 2016-07-28 01:05
If that's the only location i2f is present in that file, that's not the issue.

Have you tried removing the entire folder (keeping config) and re-pulling and installing?

If that doesn't fix it, I'm afraid I can't figure out what the issue is.

**Comment by zenety** [comment] 2016-07-28 01:16
@Calcyfer removed everything and repulled and it's working fine now. No idea where the problem would lie. Thanks :)

**Comment by Calcyfer** [comment] 2016-07-28 01:17
Welcome, glad it works. :)

**Closed** 2016-07-28 03:24 UTC
