### ISSUE TITLE
1 Hour till Bot Dies

### ISSUE THREAD

**Issue by kriswong** [PokemonGoF/PokemonGo-Bot#1098] opened 2016-07-27 01:48 UTC
### Expected Behaviour
Bot will continu running indefinitely

### Actual Behavior
Bot has error below at 1hour +/- 5 minutes.

### Steps to Reproduce
Run the Bot for more than 1 hour +/- 5 min and you bot will have this crash.

### Other Information
OS: Ubuntu 14.04

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/root/PokemonGo-Bot/pokemongo_bot/stepper.py", line 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "/root/PokemonGo-Bot/pokemongo_bot/stepper.py", line 84, in _walk_to
    self.bot.heartbeat()
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 395, in heartbeat
    self.api.call()
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 80, in call
    response = request.request(api_endpoint, self._req_method_list, player_posi$
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 93, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 201, in _parse_$
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests$
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 208, in _parse_$
    del response_proto_dict['returns']
KeyError: 'returns'

**Comment by TheGoldenXY** [comment] 2016-07-27 01:50
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1092

/closed

**Closed by TheGoldenXY** 2016-07-27 01:50 UTC
Labels: duplicate
