### ISSUE TITLE
OSX Terminal stops working

### ISSUE THREAD

**Issue by Corecrafts** [PokemonGoF/PokemonGo-Bot#1680] opened 2016-07-29 17:54 UTC
### Expected Behavior
Bot should work 24/7

### Actual Behavior
Bot turns off action after 1hour - up to 3 hours.

Im running OSX ElCaptn and the dev version works just fine. The Issue i've got: my terminal stop working after certain amount of time. (like its sleeping)
i've alrdy tried the script to restart when crashing but it doesnt crash at all - theres just no action taking place anymore. any fixes 

### Other Information
OS: El Captitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by rkodali22** [comment] 2016-07-29 17:56
Can you post the terminal output?

**Comment by Corecrafts** [comment] 2016-07-29 18:04
i aint got a n output but the last msg was this one:
[19:34:34] Moving towards fort 01bd3441ba454bc6827d2824116a6cac.16, 0.05km left

Then the client "fell kinda asleep"

**Comment by Philipp59** [comment] 2016-07-29 18:08
use caffeine and no sleep together to fix this

**Comment by Corecrafts** [comment] 2016-07-29 18:10
my mac didnt turn on any kind of sleep mode.

**Comment by Philipp59** [comment] 2016-07-29 18:12
try does both programs together Iam sure they will fix it to 99%

**Comment by Corecrafts** [comment] 2016-07-29 18:23
is there any timer who sets terminal into sleep mode?

**Comment by Philipp59** [comment] 2016-07-29 18:25
its the display or hdd I guess and yes even when you turn off all energy saving settings it will stop, i got the same error and fix it with those both programs

**Comment by TheRealJoeSmoe** [comment] 2016-07-29 18:31
Try updating in project directory.

`git pull`

Or try changing step distance in config.json

**Comment by Corecrafts** [comment] 2016-07-29 18:39
@TheRealJoeSmoe on which value? 
thx in adv

**Comment by ITDebicki** [comment] 2016-07-30 00:45
1. Modify the pokecli.py file to be an executable:
    `chmod 774 pokecli.py`
2. Run nohup
   `nohup ./pokecli.py &`

The output will be put into a file called `nohup.out`.
If you want to stop the program later, use `jobs` command to find the correct job number, followed by `kill %1` where the correct job number will be in place of the 1

**Comment by gregtampa** [comment] 2016-07-30 09:08
come to slack chat #help and someone can help you
NOT A BUG

**Closed by gregtampa** 2016-07-30 09:08 UTC
Labels: help wanted
