### ISSUE TITLE
not using ultraballs when pokeballs.count = 0

### ISSUE THREAD

**Issue by roytz** [PokemonGoF/PokemonGo-Bot#3683] opened 2016-08-12 04:25 UTC
I keep getting this message:
```
[07:15:54] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:15:57] No usable pokeballs found!
[07:16:04] Something rustles nearby!                                            
[07:16:04] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:16:07] No usable pokeballs found!
[07:16:14] Something rustles nearby!                                            
[07:16:14] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:16:18] No usable pokeballs found!
[07:16:24] Something rustles nearby!                                            
[07:16:25] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:16:28] No usable pokeballs found!
[07:16:35] Something rustles nearby!                                            
[07:16:36] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:16:39] No usable pokeballs found!
[07:16:45] Next egg incubates in 0.23 km
[07:16:46] Something rustles nearby!                                            
[07:16:46] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:16:50] No usable pokeballs found!
[07:16:57] Something rustles nearby!                                            
[07:16:58] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:17:00] No usable pokeballs found!
[07:17:08] Something rustles nearby!                                            
[07:17:09] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:17:12] No usable pokeballs found!
[07:17:19] Something rustles nearby!                                            
[07:17:20] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:17:23] No usable pokeballs found!
[07:17:33] Something rustles nearby!                                            
[07:17:33] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:17:35] No usable pokeballs found!
[07:17:43] Something rustles nearby!                                            
[07:17:43] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:17:47] No usable pokeballs found!
[07:17:54] Something rustles nearby!                                            
[07:17:55] A wild Ekans appeared! [CP 316] [Potential 0.56] [A/D/S 13/6/6]
[07:17:58] No usable pokeballs found!
[07:18:05] Something rustles nearby!                                            
```

I have 0 pokeballs but I also have 184 ultraballs.

**Comment by k4n30** [comment] 2016-08-12 04:29
Can you please use the issue template

**Comment by keugnu** [comment] 2016-08-12 04:35
Working as intended https://github.com/PokemonGoF/PokemonGo-Bot/blob/f7838b8b431ff36b12f6c0bd643dbf673db34be5/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L259

**Comment by k4n30** [comment] 2016-08-12 06:13
Closing as the bot is working as intended, and the link from keugnu will fix your problem when it is merged

**Closed by k4n30** 2016-08-12 06:13 UTC
Labels: waiting on changes

**Comment by roytz** [comment] 2016-08-12 09:03
@k4n30, @keugnu - I'm running the dev branch, not the master. I saw that this change is already in the latest pull I did..
still not working..

**Comment by k4n30** [comment] 2016-08-12 10:14
@roytz it hasn't been merged into dev yet as the PR is still open
