### ISSUE TITLE
Unknown Pokestop

### ISSUE THREAD

**Issue by Gexx** [PokemonGoF/PokemonGo-Bot#658] opened 2016-07-24 11:51 UTC
### Expected Behavior
Bot should run to the next Pokestop.

### Actual Behavior
Bot loops on one 'Unknown' Pokestop, and does not catch pokemons. It also stops moving on map.

[2016-07-24 13:21:39] [x] Captured Ekans! [CP 304]
[2016-07-24 13:23:25] [#] Finished walking
[2016-07-24 13:23:25] [#] Arrived at Pokestop
[2016-07-24 13:23:27] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-24 13:23:33] [#] Found fort 7955edff55c24b3594c383f4beee0a85.16 at distance 0.18km
[2016-07-24 13:23:33] [#] Need to move closer to Pokestop
[2016-07-24 13:23:33] [#] Walking from (45.025606, 14.57373) to (45.025527, 14.574527) for approx. 16.00 seconds
[2016-07-24 13:24:10] [#] Finished walking
[2016-07-24 13:24:11] [#] Arrived at Pokestop
[2016-07-24 13:24:13] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-24 13:24:22] [#] Found fort 9480af22803d40bc8c28449c4d318629.16 at distance 0.18km
[2016-07-24 13:24:22] [#] Need to move closer to Pokestop
[2016-07-24 13:24:22] [#] Walking from (45.025527, 14.574527) to (45.026334, 14.575386) for approx. 28.00 seconds
[2016-07-24 13:25:17] [#] Finished walking
[2016-07-24 13:25:18] [#] Arrived at Pokestop
[2016-07-24 13:25:22] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-24 13:25:36] [#] Found fort d5cd1b6e274748918d3018f72c7a9b70.16 at distance 0.27km
[2016-07-24 13:25:36] [#] Need to move closer to Pokestop
[2016-07-24 13:25:36] [#] Walking from (45.026334, 14.575386) to (45.025918, 14.576373) for approx. 23.00 seconds
[2016-07-24 13:26:22] [#] Finished walking
[2016-07-24 13:26:23] [#] Arrived at Pokestop
[2016-07-24 13:26:26] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-24 13:26:36] [#] Found fort 0f1504c0969d4bc6999699f6de255c6f.16 at distance 0.51km
[2016-07-24 13:26:36] [#] Need to move closer to Pokestop
[2016-07-24 13:26:36] [#] Walking from (45.025918, 14.576373) to (45.025354, 14.579274) for approx. 58.00 seconds
[2016-07-24 13:28:25] [#] Finished walking
[2016-07-24 13:28:26] [#] Arrived at Pokestop
[2016-07-24 13:28:27] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-24 13:28:44] [#] Scanning area for objects (3 / 25)
[2016-07-24 13:28:44] [#] Walking from (45.025354, 14.579274) to (45.0293734, 14.575662) for approx. 2.17 minutes

### Steps to Reproduce
*Unknown*
Leave bot to walk for 30-45 minutes until it happens.

### Other Information
OS: Linux
Git Commit: d0c6bc0d3d59b61b12295ba36b4ffda116b8e6be

### Ideas what is causing it (Blind guesses)
There is a chance that maybe bot just disconnects and then can't continue the walk.
Because it works for 30-45 min it could be a session problem.

### P.s.
The pokestop on that location/s exist.

**Comment by Gexx** [comment] 2016-07-24 12:03
Probably duplicate of #651 but if the response is empty why bot stops catching/spinning, moving on map?

**Comment by MikeDX** [comment] 2016-07-24 17:13
duplicate of #643 #694 and others

**Comment by gpires** [comment] 2016-07-24 17:30
Could be session that ends? I'm using Google to auth

**Comment by surfaace** [comment] 2016-07-24 23:33
duplicate of #643, maybe fixed in #701

**Closed by surfaace** 2016-07-24 23:33 UTC
Labels: bug, duplicate
