### ISSUE TITLE
Can someone please point me in the right direction.

### ISSUE THREAD

**Issue by Rlewisrlou666** [PokemonGoF/PokemonGo-Bot#1623] opened 2016-07-29 12:09 UTC
Hi i'm just looking to set up the map GUI how do I go about doing that?

**Comment by vicch** [comment] 2016-07-29 12:17
Have you read this? https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Google-Maps-API-(web-page)

**Comment by Rlewisrlou666** [comment] 2016-07-29 12:55
I got it to display in the web browser but its not tracking my movement or anything.
I might give it a bash later Thanks for the help.

**Comment by ironbishop** [comment] 2016-07-29 14:42
known issue, currently the web doesnt work in the master branch

workaround is manually creating an empty  "location-USER.json" file

duplicate #691

**Comment by TheGoldenXY** [comment] 2016-07-29 18:30
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/691

/closed

**Closed by TheGoldenXY** 2016-07-29 18:30 UTC
