### ISSUE TITLE
No Pokemon being released

### ISSUE THREAD

**Issue by lukemeaden** [PokemonGoF/PokemonGo-Bot#1639] opened 2016-07-29 13:58 UTC
Hi all,

I have a config file I believe is set to just release everything below 600 cp or 0.8 IV, but it isn't working:

`{`
`    "auth_service": "google",`
`    "username": "~",`
`    "password": "~",`
`    "location": "~",`
`    "gmapkey": "~",`
`    "max_steps": 50,`
`    "catch_pokemon": true,`
`    "spin_forts": true,`
`    "walk": 4.16,`
`    "debug": false,`
`    "test": false,`
`    "initial_transfer": false,`
`    "location_cache": true,`
`    "distance_unit": "km",`
`    "reconnecting_timeout": 15,`
`    "item_filter": {`
`      "1": { "keep" : 100 },`
`      "101": { "keep" : 10 },`
`      "102": { "keep" : 30 },`
`      "103": { "keep" : 30 },`
`      "201": { "keep" : 30 },`
`      "701": { "keep" : 100 }`
`    },`
`    "evolve_all": false,`
`    "evolve_speed": 20,`
`    "cp_min": 600,`
`    "use_lucky_egg": false,`
`    "evolve_captured": false,`
`    "catch": {`
`      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},`
`      "// Example of always catching Rattata:": {},`
`      "// Rattata": { "always_catch" : true }`
`    },`
`    "release": {`
`      "any": {"release_below_cp": 600, "release_below_iv": 0.8, "logic": "or" }`
`    }`
`}`

Can anyone shed some light?

Thanks

**Comment by mrseeker** [comment] 2016-07-29 14:12
Might have to add this one:
`"release_pokemon": true,`

**Comment by xorinzor** [comment] 2016-07-29 14:17
This is a duplicate of #1624

**Comment by lukemeaden** [comment] 2016-07-29 15:11
@mrseeker 's reply seems to have fixed it for me:

`run-0 Releasing Pidgey with CP 59 and IV 0.49. Matching release rule: CP < 600 OR IV < 0.8. `
`run-0 Exchanging Pidgey [CP 59] [Potential 0.49] for candy!`

Although it doesn't seem to happen when you would expect it to. I would expect any Pokemon that is caught to then be checked rather than being periodically checked?

**Comment by TheGoldenXY** [comment] 2016-07-29 18:31
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1624

/closed

**Closed by TheGoldenXY** 2016-07-29 18:31 UTC
