### ISSUE TITLE
[Pokemon] [ERROR] Unexpected moveset [Lick, Aqua Jet] for #86 Seel, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#4332] opened 2016-08-20 08:54 UTC
[Pokemon] [ERROR] Unexpected moveset [Lick, Aqua Jet] for #86 Seel, please update info in pokemon.json and create issue/PR

**Comment by agetnc313** [comment] 2016-08-20 08:56
[Pokemon] [ERROR] Unexpected moveset [Poison Jab, Sludge] for #88 Grimer, please update info in pokemon.json and create issue/PR

**Comment by bruno-kenji** [comment] 2016-08-20 08:58
Unnecessary double comments and duplicate of #4323

**Closed** 2016-08-20 08:59 UTC
