### ISSUE TITLE
ServerBusyOrOfflineException every 10 Minutes

### ISSUE THREAD

**Issue by IcicleTF** [PokemonGoF/PokemonGo-Bot#2009] opened 2016-07-31 05:32 UTC
### Expected Behavior
Bot runs uninterrupted.

### Actual Behavior
After 10 minutes (almost on the dot):
Server seems to be busy or offline - try again - 1/5
Server seems to be busy or offline - try again - 2/5
Server seems to be busy or offline - try again - 3/5
Server seems to be busy or offline - try again - 4/5
Server seems to be busy or offline - try again - 5/5
Trackback (most recent call last):
 File "D:\Github\PokemonGo-Bot\pokecli.py", line 490, in <module>
 File "D:\Github\PokemonGo-Bot\pokecli.py", line 81, in main
 File "D:\Github\PokemonGo-Bot\pokecli.py", line 89, in report_summary
 File "D:\Github\PokemonGo-Bot\pokemongo_bot\metrics.py, line 75, in capture_stats
 File "D:\Github\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException
### Steps to Reproduce
Running pokecli.py with login info and default config. Pokemon are captured and forts are spun within the 10 minute period, but is disconnected afterwards.

### Other Information
OS: Windows 10
Git Commit: (562959056d966e92de394955a703fec5e4fee80d)

**Comment by raxxon** [comment] 2016-07-31 05:50
I'm actually seeing it every 8minutes 45 seconds +/- 3 seconds.

I setup the run.sh to track the run time, restart after a 5 minute wait and count the iterations through the loop. Sitting here watching the output while doing other random crap it's been 8min 45sec for the disconnect with minor timing slides....

**Comment by IcicleTF** [comment] 2016-07-31 05:53
It's odd how consistent the disconnects are. I'd expect them to much more scattered were it an actual problem with the servers.

**Comment by raxxon** [comment] 2016-07-31 05:57
I've been screwing about with the configs for the past few hours thinking it was something I had setup/tweaked wrong.... Nothing I'm doing in the configs seems to make a difference. And I don't think it's a memory issue... python never exceeds 100mb of RAM, I have 128gb in the system... Something is breaking, but the details are a little thin as to where to poke....

**Comment by CattDamon** [comment] 2016-07-31 06:05
Yeah same here. Pretty damn annoying.  I usually make it 15 minutes.  I need to write a script that just restarts it every 14 minutes.

**Comment by xc-mezcal** [comment] 2016-07-31 06:11
Confirmed!

I guess the issue is making too much API calls

**Comment by raxxon** [comment] 2016-07-31 06:13
I'm currently set to a 5 minimum, 12 max delay and I'm getting the same "timeout" as I was at the defaults of 1 and 4.... Not sure if it's "too many API calls"...

**Comment by xc-mezcal** [comment] 2016-07-31 06:16
@raxxon 

That 5,12 is a misleading set. It only affects capture/release stuff. :D

**Comment by raxxon** [comment] 2016-07-31 06:23
Well that's kinda odd... I'm watching the timestamps and all actions are at those time limits... I know it's going to make a few more calls that aren't getting events logged, but if it's just making a chain series of requests without a timer control then what's the point of having the delays for capture/release?

**Comment by CattDamon** [comment] 2016-07-31 06:55
The master does not have this problem.  My dev was crashing so often but the master is rock solid.

**Comment by akbaribnu** [comment] 2016-07-31 07:55
i have problem same too...

**Comment by crowbarto** [comment] 2016-07-31 08:01
This commit from 2 days ago does not have the issue and is rock solid 50716223fece99832b11d643f0347fe6eec52655.  I'm trying to narrow down the exact commit this started for me.  It is within four commits past this one for sure.

**Comment by akbaribnu** [comment] 2016-07-31 08:10
but after branch dev update branch master same issue too, and always server busy, 

i try to change vps or ip public and gmail account but same too

**Comment by MartinTerp** [comment] 2016-07-31 08:51
I cant even get initial login to work, https://github.com/PokemonGoF/PokemonGo-Bot/commit/50716223fece99832b11d643f0347fe6eec52655 dosnt work either

**Comment by gregtampa** [comment] 2016-07-31 08:58
commit 50716223fece99832b11d643f0347fe6eec52655 doesnt have the bug,  then commit after that one 2805cb75be3d30de272095675316f1bf9138b639 has it and every commit since

**Comment by SteffanLong** [comment] 2016-07-31 09:07
I don't have this issue on the latest dev.

**Comment by akbaribnu** [comment] 2016-07-31 09:19
whats your id.? ptc or google.?

**Comment by crowbarto** [comment] 2016-07-31 09:25
Mine is a google login with the bug.  I have not tried with a ptc login yet.

**Comment by raxxon** [comment] 2016-07-31 09:32
Mine's google as well....

**Comment by tvb** [comment] 2016-07-31 09:34
5071622 does not work for me.

**Comment by IcicleTF** [comment] 2016-07-31 09:34
Yeah, I'm also using google.
Also, currently using bdaddec9ee64691e5b0a8bda55bf76f83442232f

**Comment by crowbarto** [comment] 2016-07-31 09:54
Just tried latest dev with a **PTC login** and same crash after 9 mins 45 seconds.


[02:50:03]  50 xp
[02:50:04]  - 3x Pokeball (Total: 82)
[02:50:04] PokeStop on cooldown. Time left: 5 minutes, 2 seconds
[02:50:06] Moving towards fort Pier 39 Mural, 0.04km left
[02:50:11] Walking from (37.80854248124627, -122.41007007104047) to [37.810317000000005, -122.410119] 0.20km
[02:50:27]  Server seems to be busy or offline - try again - 1/5
[02:50:28]  Server seems to be busy or offline - try again - 2/5
[02:50:29]  Server seems to be busy or offline - try again - 3/5
[02:50:30]  Server seems to be busy or offline - try again - 4/5
[02:50:31]  Server seems to be busy or offline - try again - 5/5
[02:50:31]  Server seems to be busy or offline - try again - 1/5
[02:50:32]  Server seems to be busy or offline - try again - 2/5
[02:50:33]  Server seems to be busy or offline - try again - 3/5
[02:50:34]  Server seems to be busy or offline - try again - 4/5
[02:50:35]  Server seems to be busy or offline - try again - 5/5
Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
  File "pokecli.py", line 81, in main
  File "pokecli.py", line 89, in report_summary
  File "C:\PokemonGo-Bot\pokemongo_bot\metrics.py", line 75, in capture_stats
  File "C:\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException

**Comment by raxxon** [comment] 2016-07-31 10:10
I went with a little more detail in my run.sh....

`loops=0
while true
do
  SECONDS=0
  python pokecli.py --config ${config}
  ((loops++))
  echo -e
  echo -e "We seeem to have crashed, removing webcache location, sleeping 3 minutes and restarting...."
  echo -e "Loop Iterations: " $loops
  duration=$SECONDS
  echo -e "Runtime was $(($duration / 60)) minutes and $(($duration % 60)) seconds"
  echo -e
  rm web/location*.json
  sleep 180
done`

**Comment by IcicleTF** [comment] 2016-07-31 10:41
Thanks for this, Raxxon. I'll probably use this w/ cygwin until there's a proper fix.

**Comment by raxxon** [comment] 2016-07-31 11:27
trying to do some digging... The error points to this chunk from pgoapi.py:

if try_cnt >= max_retry:
  raise ServerBusyOrOfflineException()

I follow that back and as far as I can tell, it just generates the error message that is displayed in the log/console. After it reaches 5 times in that loop it breaks hard and dies. Commenting out the 2 lines so that it doesn't trip still ultimately causes a failure, it just doesn't break hard after 5 tries....

[06:18:47]  Server seems to be busy or offline - try again - 206/5
[06:18:47]  Server seems to be busy or offline - try again - 207/5
[06:18:49]  Server seems to be busy or offline - try again - 208/5
[06:18:50]  Server seems to be busy or offline - try again - 209/5

**Comment by tvb** [comment] 2016-07-31 11:46
Perhaps this is true? https://github.com/PokemonGoF/PokemonGo-Bot/issues/2027#issuecomment-236422398

**Comment by raxxon** [comment] 2016-07-31 11:49
I'm not having problems logging in, just in staying connected with the bot. I can play from my ipad on the same internet connection and it has no problems with me being online for an hour or more (except that the GPS appears to be shit on the ipad). If they've blocked access to the netblock I'm in then they're taking a crap on the business that are on FIOS....

**Comment by Phantom11011** [comment] 2016-07-31 13:56
I have the same problem, a solution is avaible please ?

[15:46:04]  Server seems to be busy or offline - try again - 4/5
[15:46:05]  Server seems to be busy or offline - try again - 5/5
[15:46:05]  Server seems to be busy or offline - try again - 1/5
[15:46:07]  Server seems to be busy or offline - try again - 2/5
[15:46:08]  Server seems to be busy or offline - try again - 3/5
[15:46:09]  Server seems to be busy or offline - try again - 4/5
[15:46:10]  Server seems to be busy or offline - try again - 5/5
[15:46:10]  Server seems to be busy or offline - try again - 1/5
[15:46:11]  Server seems to be busy or offline - try again - 2/5
[15:46:12]  Server seems to be busy or offline - try again - 3/5
[15:46:13]  Server seems to be busy or offline - try again - 4/5
[15:46:14]  Server seems to be busy or offline - try again - 5/5
Traceback (most recent call last):
  File "./pokecli.py", line 494, in <module>
  File "./pokecli.py", line 81, in main
  File "./pokecli.py", line 89, in report_summary
  File "C:\Users\Melina\Documents\pokemon\dev\PokemonGo-Bot\pokemongo_bot\metrics.py", line 75, in capture_stats
  File "C:\Users\Melina\Documents\pokemon\dev\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 74, in call
pgoapi.exceptions.ServerBusyOrOfflineException

**Comment by tvb** [comment] 2016-07-31 13:58
My guess is that they have banned all IP addresses from amazon, azure etc.

**Comment by Phantom11011** [comment] 2016-07-31 13:59
the bot turn on my computer.

**Comment by metheos** [comment] 2016-07-31 14:47
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1654

**Comment by vicch** [comment] 2016-07-31 17:32
An observation: the bot tends to encounter this problem when it arrives at a pokestop it already visited, in other words, walking in a circle.

**Comment by raxxon** [comment] 2016-07-31 18:10
Not in my case. The path I have has the bot in an area where there are no pokestops when it crashes. When I let the bot "free roam" it was usually just meandering across a highway or something when it crashed.

**Comment by Phantom11011** [comment] 2016-07-31 18:24
Thanks metheos for the reply , my issue is resolved. I edited the file src\pgoapi\pgoapi/rpc_api.py.
https://github.com/tejado/pgoapi/commit/e6db98b9a931731a9f449365a31dc1a9b794f5a0
Thanks too @douglascamata for answer at my problem.

**Comment by raxxon** [comment] 2016-07-31 18:34
Testing to see if it addresses issue for me....

**Comment by raxxon** [comment] 2016-07-31 18:55
Been running for longer than 20 minutes now, previously it was less than 10. Appears to have addressed issue for me.

**Comment by kaoztheory** [comment] 2016-07-31 19:05
server busy for me

**Comment by WebberTakken** [comment] 2016-07-31 20:00
also testing if this fixes the issue for me

**Comment by WebberTakken** [comment] 2016-07-31 20:27
Have been running it without any problem now

**Comment by crowbarto** [comment] 2016-07-31 21:28
Editing the file src\pgoapi\pgoapi/rpc_api.py as described above seemed to have resolved the issue for me as well.

**Comment by saintnik2015** [comment] 2016-07-31 22:09
Have this problem too. Fixing src\pgoapi\pgoapi/rpc_api.py didn't help. :(

**Comment by kaoztheory** [comment] 2016-08-01 02:44
Did not help editing rpc_api.py

**Comment by raxxon** [comment] 2016-08-01 06:18
Appears to be fixed in the current state, but most likely you'll need to run an extra command...

git pull
pip install --upgrade -r requirements.txt

That should update the bot (make sure you check your configs as they've been altered several times in the last 24h) and makes sure that the pgoapi is updated.

**Closed** 2016-08-05 08:32 UTC
Labels: approved, bug, help wanted
