### ISSUE TITLE
(MASTER) struct.error: integer out of range for 'Q' format code

### ISSUE THREAD

**Issue by YvesHenri** [PokemonGoF/PokemonGo-Bot#1844] opened 2016-07-30 12:59 UTC
Bot was working flawlessly for a whole day. At night, when I got home, poped up an egg to evolve some pokes and got it to bot again. I'm not sure if that was the problem, but...

### Expected Behavior
Log in, set position then start walking/hunting/spinning

### Actual Behavior
Log in, set position and crash immediately

### Steps to Reproduce
self.api._position_lat = 42.3358578
self.api._position_lng = -83.050096

### Other Information
OS: Windows 10
Git Commit: 03f1b428e8781b8c4aa35d1cd6a305fc13bbaff7
Stack trace:
File "pokecli.py", line 220, in <module>
   main()
 File "pokecli.py", line 211, in main
   bot.take_step()
 File "SOME_PATH\master\pokemongo_bot\__init__.py", line 36, in take_step
   self.stepper.take_step()
 File "SOME_PATH\master\pokemongo_bot\stepper.py", line 53, in take_step
   self._walk_to(self.config.walk, *position)
 File "SOME_PATH\master\pokemongo_bot\stepper.py", line 66, in _walk_to
   dist = distance(i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
 File "SOME_PATH\master\pokemongo_bot\cell_workers\utils.py", line 99, in i2f
   return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code

**Comment by Erody** [comment] 2016-07-30 13:16
Same error here on master branch. 55390cfd7fcedace99c2c3d372b3790ef5b7cfd7

**Comment by YvesHenri** [comment] 2016-07-30 13:31
Theyre basically the same version. 55390cf has just changed the git's README.md.

**Comment by mako-taco** [comment] 2016-07-30 15:14
duplicate of #1042

**Comment by YvesHenri** [comment] 2016-07-30 15:39
It's happening on master. The solution listed in your link shows to upgrade to the dev branch, which isnt what I'm looking for.

> "Please upgrade to the latest dev branch by running this command"

**Comment by mako-taco** [comment] 2016-07-30 15:46
right, but it's worth noting that we're probably seeing the same issue which was seen before!

**Comment by steveplusplus** [comment] 2016-08-01 00:34
This showed up for me after trying out the Dev stream. I was able to get around this by re-running a few commands from the installation manual:

pip2 install -r requirements.txt
git submodule init
git submodule update

**Closed** 2016-08-05 08:32 UTC
