### ISSUE TITLE
ServerSideRequestThrottlingException

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#2400] opened 2016-08-02 21:34 UTC
### Expected Behavior
Working bot

### Actual Behavior
Broken on start
rverBusyOrOfflineException, NoPlayerPositionSetException, EmptySubrequestChainException
ImportError: cannot import name ServerSideRequestThrottlingException

It is in a fresh new virtualenv with pip -r requirements. 
### Steps to Reproduce
run python pokecli.py

### Other Information
OS: Ubuntu 
Git Commit: 1fe2bfe16dbbbddd6e44f4479285b12160e57954
Python Version: 2.7.11

**Comment by JSchwerberg** [comment] 2016-08-02 21:36
Duplicate of issue #2391.  There is currently a PR to remedy this #2393, but has not been accepted upstream yet..

**Comment by douglascamata** [comment] 2016-08-02 23:38
PR #2393 merged and fixed this.

**Closed by douglascamata** 2016-08-02 23:38 UTC
