### ISSUE TITLE
 WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by bilalkamoon** [PokemonGoF/PokemonGo-Bot#3834] opened 2016-08-13 09:09 UTC
Getting this error when running Pokecli.py:

 Encrypt.so directory: C:\Users\Win8\Downloads\PokemonGo-Bot-dev\PokemonGo-Bot-d
ev
2016-08-13 11:57:11,019 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 145, in main
    report_summary(bot)
  File "pokecli.py", line 180, in report_summary
    metrics.capture_stats()
  File "C:\Users\Win8\Downloads\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bo
t\metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "C:\Users\Win8\Downloads\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bo
t\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\Win8\Downloads\PokemonGo-Bot-dev\PokemonGo-Bot-dev\pokemongo_bo
t\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\win8\downloads\pokemongo-bot-master\src\pgoapi\pgoapi\pgoapi.py
", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\win8\downloads\pokemongo-bot-master\src\pgoapi\pgoapi\rpc_api.p
y", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

### Other Information
OS: Win 8
Branch: dev
Python Version: 2.7.12

**Comment by k4n30** [comment] 2016-08-13 10:24
Duplicate of #3810 

You need to ensure you have the correct dll for you OS

**Closed by k4n30** 2016-08-13 10:24 UTC
