### ISSUE TITLE
Server is throttling error/bug

### ISSUE THREAD

**Issue by youberser** [PokemonGoF/PokemonGo-Bot#4032] opened 2016-08-15 21:57 UTC
### Expected Behavior
Work as always

### Actual Behavior
"Server" error, but I can use other windows bot or even the PoGo Android app

### Your config.json (remove your credentials and any other private info)
```
"auth_service": "ptc",
    "username": "MYUSER",
    "password": "MYPASS",
    "location": "40.417338,-3.683095",
    "gmapkey": "MYAPIKEY",
    "encrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "00:00",
          "duration":"0:00",
          "time_random_offset": "00:00",
          "duration_random_offset": "00:00"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Carterpie,Spearow,Paras,Pidgeotto,Ekans,Meowth,Growlithe,Mankey,Pidgey,Rattata,Weedle,Zubat",
            "first_evolve_by": "cp",
            "evolve_above_cp": 10,
            "evolve_above_iv": 0.01,
            "logic": "or",
"evolve_speed": 5,
            "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 5,
          "item_filter": {
            "Pokeball":       { "keep" : 70 },
            "Greatball":      { "keep" : 40 },
            "Ultraball":      { "keep" : 45 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Max Potion":     { "keep" : 50 },
            "Revive":         { "keep" : 24 },
            "Razz Berry":     { "keep" : 45 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
{
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk_min": 14.9,
    "walk_max": 10,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
"distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 5,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Ekans": { "never_catch" : true },
      "// Scyther": { "never_catch" : true },
      "// Pidgey": { "never_catch" : true },
      "// Rattata": { "never_catch" : true },
      "// Zubat": { "never_catch" : true },
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "// any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
 "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "any": {"keep_best_cp": 1},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
`"auth_service": "ptc",
    "username": "MYUSER",
    "password": "MYPASS",
    "location": "40.417338,-3.683095",
    "gmapkey": "MYAPIKEY",
    "encrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "00:00",
          "duration":"0:00",
          "time_random_offset": "00:00",
          "duration_random_offset": "00:00"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Carterpie,Spearow,Paras,Pidgeotto,Ekans,Meowth,Growlithe,Mankey,Pidgey,Rattata,Weedle,Zubat",
            "first_evolve_by": "cp",
            "evolve_above_cp": 10,
            "evolve_above_iv": 0.01,
            "logic": "or",
"evolve_speed": 5,
            "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 5,
          "item_filter": {
            "Pokeball":       { "keep" : 70 },
            "Greatball":      { "keep" : 40 },
            "Ultraball":      { "keep" : 45 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Max Potion":     { "keep" : 50 },
            "Revive":         { "keep" : 24 },
            "Razz Berry":     { "keep" : 45 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
{
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk_min": 14.9,
    "walk_max": 10,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
"distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 5,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Ekans": { "never_catch" : true },
      "// Scyther": { "never_catch" : true },
      "// Pidgey": { "never_catch" : true },
      "// Rattata": { "never_catch" : true },
      "// Zubat": { "never_catch" : true },
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "// any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
 "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "any": {"keep_best_cp": 1},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
```

### Steps to Reproduce
Just try to start the bot

### Other Information
OS: Linux Server 14.04
Git Commit: db361cc6b89276f27de8c522b85a33308d24cd97
Python Version: Python 2.7.6

**Comment by youberser** [comment] 2016-08-15 22:02
![poke](https://cloud.githubusercontent.com/assets/20970812/17681228/b300dd8e-6344-11e6-9f86-2670fdc54625.png)

**Comment by youberser** [comment] 2016-08-15 22:04
![poke](https://cloud.githubusercontent.com/assets/20970812/17681273/f4c24438-6344-11e6-9333-83277f155747.png)

**Comment by youberser** [comment] 2016-08-15 22:09
@GitPupper I can spin and farm pokestops, spin them, catch pokemon and throw berries with my android phone (using mock mock xposed module and fakegps to mimic my config)

**Comment by k4n30** [comment] 2016-08-16 01:42
Duplicate of #3253

**Closed** 2016-08-16 04:22 UTC
Labels: Duplicate
