### ISSUE TITLE
While in catch mode, it continually jumps between two locations instead of searching around

### ISSUE THREAD

**Issue by JVenberg** [PokemonGoF/PokemonGo-Bot#872] opened 2016-07-25 21:11 UTC
### Expected Behavior
To search area for pokemon

### Actual Behavior
**Output**
[14:05:16] Starting PokemonGo Bot....
[14:05:16] Scanning area for objects....
[14:05:16] Walking from (33.4657272, -112.0726404) to (33.4657272, -112.0726404) 0.00mi
[14:05:17] No lucky eggs... skipping evolve!
[14:05:17] Scanning area for objects....
[14:05:17] Walking from (33.4657272, -112.0726404) to (33.4682272, -112.0726404) 0.17mi
[14:05:20] Scanning area for objects....
[14:05:20] Walking from (33.46580822086005, -112.07263184167847) to (33.4682272, -112.0726404) 0.17mi
[14:05:24] Scanning area for objects....
[14:05:24] Walking from (33.46589104203378, -112.07263281898337) to (33.4682272, -112.0726404) 0.16mi
[14:05:27] Scanning area for objects....
[14:05:27] Walking from (33.465946366739594, -112.07262476643787) to (33.4682272, -112.0726404) 0.16mi
[14:05:30] Scanning area for objects....
[14:05:30] Walking from (33.46600398473784, -112.07262271156061) to (33.4682272, -112.0726404) 0.15mi
[14:05:33] Scanning area for objects....
[14:05:33] Walking from (33.46606070552212, -112.07264118401011) to (33.4682272, -112.0726404) 0.15mi
[14:05:37] Scanning area for objects....
[14:05:37] Walking from (33.46613779628475, -112.0726598451578) to (33.4682272, -112.0726404) 0.14mi
[14:05:40] Scanning area for objects....
[14:05:40] Walking from (33.466194885942954, -112.07265569068018) to (33.4682272, -112.0726404) 0.14mi
[14:05:43] Scanning area for objects....
[14:05:43] Walking from (33.46627803362661, -112.07266309179134) to (33.4682272, -112.0726404) 0.13mi
[14:05:45] Scanning area for objects....
[14:05:45] Walking from (33.466324710200645, -112.07264664521821) to (33.4682272, -112.0726404) 0.13mi
[14:05:48] Scanning area for objects....
[14:05:48] Walking from (33.466408095635096, -112.07263947143495) to (33.4682272, -112.0726404) 0.13mi
[14:05:52] Scanning area for objects....
[14:05:52] Walking from (33.466446415373696, -112.07266418590034) to (33.4682272, -112.0726404) 0.12mi
[14:05:55] Scanning area for objects....
[14:05:55] Walking from (33.466526971472575, -112.0726853428035) to (33.4682272, -112.0726404) 0.12mi
[14:05:58] Scanning area for objects....
[14:05:58] Walking from (33.46656838335654, -112.07267372688378) to (33.4682272, -112.0726404) 0.11mi

### Steps to Reproduce
Enter in catch mode with no pokemon around

### Other Information
OS: OSX El Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by 03t02** [comment] 2016-07-25 21:15
Your bag is probably full, and bot switch automatically in catch mode. It seems your problem is the same for this issue https://github.com/PokemonGoF/PokemonGo-Bot/issues/821

**Comment by surfaace** [comment] 2016-07-25 21:28
duplicate of #816

**Closed by surfaace** 2016-07-25 21:28 UTC
Labels: bug
