### ISSUE TITLE
teleporting to the gulf of guinea on start [0.00, 0.00]

### ISSUE THREAD

**Issue by wcrwcr** [PokemonGoF/PokemonGo-Bot#1229] opened 2016-07-27 17:06 UTC
### Expected Behavior
start at the given coordinates

### Actual Behavior
teleporting to 0.00, 0.00 and hanging

[18:56:19] Configuration initialized
[18:56:19] [x] Coordinates found in passed in location, not geocoding.
[18:56:19]
[18:56:19] Location Found: 22.22,22.22
[18:56:19] GeoPosition: (1.14e-322, 1.04e-322, 0)
...
[18:56:24] Starting PokemonGo Bot....
[18:56:29] Scanning area for objects....
[18:56:29] Walking from (0.0, 0.0) to [0.0, 0.0] 0.00km

[18:56:33] Scanning area for objects....
[18:56:33] Walking from (0.0, 0.0) to [0.0018, 0.0] 0.20km

### Steps to Reproduce
any location in config.json
start bot

### Other Information
OS: win7
Git Commit: 3a18aa57dfb67e2e09c207087cad6e5aa1867112

**Comment by LasseSkogland** [comment] 2016-07-27 17:18
Download latest dev.
```
git reset --hard
git pull -f
```

**Comment by wcrwcr** [comment] 2016-07-27 17:28
didnt help. 
works after deleting everything and clonning from the scratch

**Comment by LasseSkogland** [comment] 2016-07-27 17:29
If the issue is resolved, close this issue.

**Comment by TheGoldenXY** [comment] 2016-07-27 17:34
Issue has been resolved, closing this.

/closed

**Closed by TheGoldenXY** 2016-07-27 17:34 UTC
