### ISSUE TITLE
unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by fence1247** [PokemonGoF/PokemonGo-Bot#2863] opened 2016-08-07 16:47 UTC
It seems like whenever the bot tries to complete an action, like spinning a pokestop, it runs into this error. My bot only runs for about 8-11 seconds total each time.

016-08-07 10:19:24,084 [PokemonGoBot] [INFO] 
2016-08-07 10:19:24,084 [PokemonGoBot] [INFO] 
2016-08-07 10:19:31,577 [ cli] [INFO] 
2016-08-07 10:19:31,577 [ cli] [INFO] Ran for 0:00:11
Traceback (most recent call last):
File "pokecli.py", line 493, in 
main()
File "pokecli.py", line 127, in main
report_summary(bot)
File "pokecli.py", line 139, in report_summary
logger.info('Total XP Earned: {} Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
File "/Users/trevor/PokemonGo-Bot/pokemongo_bot/metrics.py", line 28, in xp_earned
return self.xp['latest'] - self.xp['start']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by ti0ma** [comment] 2016-08-08 15:24
I fixed it by putting some type checks: https://gist.github.com/ti0ma/2e906029ebe39d4f246f7d5f0596fd5c

and commented the line 145 at pokecli.py

I also had this error: "The EvolveAll task has been renamed to EvolvePokemon" after fixing the above errors, so I changed the task in my config file.

All this is a quick fix, while waiting for a fix :)

**Comment by k4n30** [comment] 2016-08-12 00:13
@fence1247 can you update to the latest version and indicate if this is still an issue

**Comment by k4n30** [comment] 2016-08-13 01:53
Duplicate of #2596

**Closed by k4n30** 2016-08-13 01:53 UTC
Labels: duplicate
