### ISSUE TITLE
Bot stops working after ~1 hour

### ISSUE THREAD

**Issue by engise** [PokemonGoF/PokemonGo-Bot#3238] opened 2016-08-09 08:18 UTC
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Bot walks, spins pokestops and catches pokemon

### Actual Behavior
Bot walks, spins pokestops and catches pokemon, but stops after ~1 hour (sometimes 0:59:--)

### Steps to Reproduce
Run the bot and let it farm for an hour or more

### Other Information
OS: OS X El Capitan 10.11.16
Git Commit: 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: Python 2.7.11

**Comment by urbels** [comment] 2016-08-09 08:20
error?

**Comment by engise** [comment] 2016-08-09 08:22
Whoops... I forgot the snippet.

`2016-08-09 11:07:45,300 [       cli] [INFO] 
2016-08-09 11:07:45,300 [       cli] [INFO] Ran for 1:00:00
2016-08-09 11:07:45,300 [       cli] [INFO] Total XP Earned: 7350  Average: 7350.85/h
2016-08-09 11:07:45,300 [       cli] [INFO] Travelled 1.64km
2016-08-09 11:07:45,300 [       cli] [INFO] Visited 30 stops
2016-08-09 11:07:45,300 [       cli] [INFO] Encountered 25 pokemon, 25 caught, 18 released, 1 evolved, 0 never seen before
2016-08-09 11:07:45,301 [       cli] [INFO] Threw 26 pokeballs
2016-08-09 11:07:45,301 [       cli] [INFO] Earned 2500 Stardust
2016-08-09 11:07:45,301 [       cli] [INFO] 
2016-08-09 11:07:45,301 [       cli] [INFO] Highest CP Pokemon: Rhyhorn [CP: 566] [IV: 14/5/7] Potential: 0.58 
2016-08-09 11:07:45,301 [       cli] [INFO] Most Perfect Pokemon: Zubat [CP: 274] [IV: 11/14/11] Potential: 0.8 
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)
2016-08-09 11:07:45,316 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-09 11:07:45,320 [sentry.errors.uncaught] [ERROR] [u"TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']`

**Comment by pranavperfect** [comment] 2016-08-09 08:24
Duplicate of #2864, #2874

**Comment by engise** [comment] 2016-08-09 08:41
I should've searched for the issue, I'm sorry.

I saw in some of those other threads that people recommend that you stop the evolving and update pgoapi. I'll update in an hour.

**Closed** 2016-08-12 04:38 UTC
Labels: duplicate
