### ISSUE TITLE
Issue UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by solderzzc** [PokemonGoF/PokemonGo-Bot#2641] opened 2016-08-07 04:00 UTC
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

**Comment by jolivier** [comment] 2016-08-07 04:05
same for me

**Comment by solderzzc** [comment] 2016-08-07 04:06
I just rerun the script lol

**Comment by solderzzc** [comment] 2016-08-07 04:06
`
#!/bin/bash
while [ true  ]
do
python pokecli.py -cf testconfig.json
sleep 20
done
`

**Comment by MarianoCordoba** [comment] 2016-08-07 04:17
Same here

**Comment by islanderman** [comment] 2016-08-07 05:05
I am having the same issue on CentOS 7 and Raspberry Pi.  However Mac works.

**Comment by mrgohamilton** [comment] 2016-08-07 05:19
anyone figure this out?

**Comment by philly223** [comment] 2016-08-07 05:28
getting this same error but on mac. encrypt.so file is already next to pokecli.py

**Comment by WaffleMoose** [comment] 2016-08-07 06:00
Also getting this error, from what i can see the api isn't getting a latitude and longitude for the player
2016-08-07 07:57:38,053 [pgoapi.pgoapi] [INFO] latNone lngNone
pokemongo_bot\api_wrapper.py", line 55, in can_call
    raise NoPlayerPositionSetException()

**Comment by WaffleMoose** [comment] 2016-08-07 07:07
This error is caused by Line 779 in __init__.py and can be fixed by turning test off in the config
        if self.config.test:
            # TODO: Add unit tests
            return

**Closed** 2016-08-11 02:35 UTC
