### ISSUE TITLE
Bot walking away from pokestops 

### ISSUE THREAD

**Issue by em202020** [PokemonGoF/PokemonGo-Bot#1949] opened 2016-07-31 00:19 UTC
### Expected Behavior
Walking to nearest pokestop(Obviously)

### Actual Behavior
When placed at Santa Monica Pier, it walks out into the water
http://i.imgur.com/ZxjvyOE.png

EDIT: This was the path after a couple hours of running the bot
http://i.imgur.com/GFJQPqt.png

### Steps to Reproduce
I tried re-running the bot multiple times to just have the bot walk off into the distance.
This is my config file: http://pastebin.com/z63nHp5R
I dont have the new "navigation" setting in the config, as it was not yet added to the example, nor is there much documentation about what each setting does.

### Other Information
OS: Ubuntu 16.04.1
Git Commit: 637b7e646e61bf5be7bfc1b024f78abe21379c07

**Comment by skorokithakis** [comment] 2016-07-31 02:52
Looks like a duplicate of #1885.

**Closed** 2016-07-31 07:09 UTC
