### ISSUE TITLE
after a git pull to update my branches the bot stopped to work when I try to run the bot. I cannot start on master or dev branches

### ISSUE THREAD

**Issue by palerique** [PokemonGoF/PokemonGo-Bot#4121] opened 2016-08-16 22:43 UTC
### Expected Behavior

start the bot.

### Actual Behavior

after a git pull to update my branches the bot stopped to work when I try to run the bot. I cannot start on master or dev branches.

./run.sh 
./run.sh: line 29:  3182 Illegal instruction     python pokecli.py -cf $filename
Tue Aug 16 19:36:05 BRT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
    "auth_service": "google",
    "username": "XxX",
    "password": "XxX",
    "location": "-15,-47",
    "gmapkey": "XxX",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
	  "catch_simulation": {
	    "flee_count": 3,
	    "flee_duration": 2,
	    "catch_wait_min": 2,
	    "catch_wait_max": 6,
	    "berry_wait_min": 2,
	    "berry_wait_max": 3,
	    "changeball_wait_min": 2,
	    "changeball_wait_max": 3
	  },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Output when issue occurred
wrote above

### Steps to Reproduce
wrote above

### Other Information
OS: 
Linux
Branch: 
dev and master
Git Commit: 
on master: 423e4dea72c0b04d8882ef90f03949fe3bf35ac2
on dev: e68c2e80202b9457311368eb2248c5a762fa35bc

Python Version: 
Python 2.7.6

Any other relevant files/configs (eg: path files) 
no

**Comment by k4n30** [comment] 2016-08-17 04:20
@palerique While there have been changes to run.sh, there hasn't been any changes to the line which is causing you issues for 8 days, or anything that it calls for 5 days.

This problem seems like an issue with your OS and unfortunately we can't help any further without going down the path of installing a debugger like gdb or similar.  If the issue doesn't resolve itself, I'd suggest jumping on the slack and seeing if anyone there can help you.

Closing this issue as it's not a bug in the bot

**Closed by k4n30** 2016-08-17 04:20 UTC
