### ISSUE TITLE
New error?

### ISSUE THREAD

**Issue by fvorez** [PokemonGoF/PokemonGo-Bot#1441] opened 2016-07-28 17:05 UTC
[2016-07-28 10:04:17] [x] PokemonGO Bot v1.0
[2016-07-28 10:04:17] [x] Configuration initialized
[2016-07-28 10:04:18]
[2016-07-28 10:04:18] [x] Address found: 33.760757, -118.19507

[2016-07-28 10:04:21] [#] -- Pokestops Visited: 894
[2016-07-28 10:04:21] [#]
[2016-07-28 10:04:22] [x] Starting PokemonGo Bot....
[2016-07-28 10:04:22] [#] Scanning area for objects (1 / 25)
Traceback (most recent call last):
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\pokecli.py", line 220, in <mo
dule>
    main()
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\pokecli.py", line 211, in mai
n
    bot.take_step()
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\pokemongo_bot\__init__.py", l
ine 36, in take_step
    self.stepper.take_step()
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\pokemongo_bot\stepper.py", li
ne 53, in take_step
    self._walk_to(self.config.walk, *position)
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\pokemongo_bot\stepper.py", li
ne 67, in _walk_to
    i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-master\pokemongo_bot\cell_workers\ut
ils.py", line 98, in i2f
    return struct.unpack('<d', struct.pack('<Q', int))[0]
struct.error: integer out of range for 'Q' format code

**Comment by larssy1** [comment] 2016-07-28 17:07
Duplicate: https://github.com/PokemonGoF/PokemonGo-Bot/issues/1249

**Comment by fvorez** [comment] 2016-07-28 17:13
Ahh, indeed, thank you.

**Comment by TheGoldenXY** [comment] 2016-07-28 22:30
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1249

/closed

**Closed by TheGoldenXY** 2016-07-28 22:30 UTC
