### ISSUE TITLE
Crash during Login: TypeError: None has type <type 'NoneType'>

### ISSUE THREAD

**Issue by Devilbilly** [PokemonGoF/PokemonGo-Bot#3031] opened 2016-08-08 09:02 UTC
### Expected Behavior
Succ login

### Actual Behavior
Crash

### Steps to Reproduce
Got a crash after ./run.sh.
I have done all the instructions mentioned in the wiki and set config.json

### Other Information
OS: Centos 7
Git Commit: format563f898f61233ff86d38d83b68d8399c1f63051b
Python Version: 2.7.5

(PokemonGo-Bot) [billy@IRISLAB-44 PokemonGo-Bot]$ ./run.sh 
2016-08-09 00:57:26,810 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-09 00:57:26,812 [       cli] [INFO] Configuration initialized
2016-08-09 00:57:26,812 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-09 00:57:26,812 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-09 00:57:26,820 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-09 00:57:26,840 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-09 00:57:26,841 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-09 00:57:26,841 [PokemonGoBot] [INFO] [location_found] Location found: 24.80401287450498,120.97030162723968 (24.8040128, 120.9703016, 0.0)
2016-08-09 00:57:26,841 [PokemonGoBot] [INFO] [position_update] Now at (24.8040128, 120.9703016, 0)
2016-08-09 00:57:26,842 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 131, in main
    report_summary(bot)
  File "pokecli.py", line 140, in report_summary
    metrics.capture_stats()
  File "/home/billy/git/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/billy/git/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/home/billy/git/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/home/billy/git/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/home/billy/git/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 126, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/home/billy/git/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 216, in _build_main_request
    request.auth_info.token.contents = self._auth_provider.get_access_token()
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 176, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)
2016-08-09 00:57:27,607 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 833, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-09 00:57:27,609 [sentry.errors.uncaught] [ERROR] [u"TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)", u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 131, in main', u'  File "pokecli.py", line 140, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 126, in request', u'  File "pgoapi/rpc_api.py", line 216, in _build_main_request', u'  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/home/billy/git/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 176, in CheckValue']

**Comment by homegrow** [comment] 2016-08-08 15:34
This happened to me after exactly 1 hour of running the bot. Everything worked fine...then this:

2016-08-08 17:25:31,554 [       cli] [INFO] Ran for 1:00:00
...
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)
2016-08-08 17:25:31,613 [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
...
2016-08-08 17:25:31,625 [sentry.errors.uncaught] [ERROR] [u"TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)", u'  File "pokecli.py", line 503, in <module>', u'  File "pokecli.py", line 89, in main', u'  File "pokemongo_bot/__init__.py", line 434, in tick', u'  File "pokemongo_bot/cell_workers/evolve_pokemon.py", line 28, in work', u'  File "pgoapi/pgoapi.py", line 122, in function', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 220, in call', u'  File "pgoapi/rpc_api.py", line 126, in request', u'  File "pgoapi/rpc_api.py", line 216, in _build_main_request', u'  File "/Users/LordWilson/Applications/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/Users/LordWilson/Applications/PokemonGo-Bot/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 176, in CheckValue']

**Comment by homegrow** [comment] 2016-08-08 15:35
Will try another run. May this was just random.

**Comment by noncicredo** [comment] 2016-08-09 01:14
same here: crashes after 1 hour of running. tried everything i found about it but nothing worked

**Comment by LeeRongWen** [comment] 2016-08-09 10:01
i have same problem

2016-08-09 15:50:25,742 [       cli] [INFO] Ran for 0:59:40
2016-08-09 15:50:25,742 [       cli] [INFO] Total XP Earned: 4610  Average: 4635.14/h
2016-08-09 15:50:25,742 [       cli] [INFO] Travelled 0.17km
2016-08-09 15:50:25,742 [       cli] [INFO] Visited 5 stops
2016-08-09 15:50:25,742 [       cli] [INFO] Encountered 16 pokemon, 16 caught, 11 released, 0 evolved, 2 never seen before
2016-08-09 15:50:25,742 [       cli] [INFO] Threw 17 pokeballs
2016-08-09 15:50:25,743 [       cli] [INFO] Earned 1600 Stardust
2016-08-09 15:50:25,743 [       cli] [INFO]
2016-08-09 15:50:25,743 [       cli] [INFO] Highest CP Pokemon: Goldeen [CP: 344] [IV: 8/10/7] Potential: 0.56
2016-08-09 15:50:25,743 [       cli] [INFO] Most Perfect Pokemon: Voltorb [CP: 11] [IV: 13/12/11] Potential: 0.8
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

**Comment by homegrow** [comment] 2016-08-09 10:30
This may has something to do with the cell_workers folder. I exchanged it for a colored version of the bot before. Switched to the old one again. Will see if it comes up again. Couldn't try yet.

**Comment by k4n30** [comment] 2016-08-13 01:54
Duplicate of #2975

**Closed by k4n30** 2016-08-13 01:54 UTC
Labels: duplicate
