### ISSUE TITLE
crash: TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#1179] opened 2016-07-27 11:04 UTC
### Expected Behavior
still running forever

### Actual Behavior

in it's current state the bot is pretty stable, stable than ever i can say (and i use it and review it from it's almost start)
but its still not keep running an entire night
```
Traceback (most recent call last):
  File "pokecli.py", line 250, in <module>
    main()
  File "pokecli.py", line 241, in main
    bot.take_step()
  File "/root/PokemonGo-Bot-myprettyusername/pokemongo_bot/__init__.py", line 41, in take_step
    location = self.navigator.take_step()
  File "/root/PokemonGo-Bot-myprettyusername/pokemongo_bot/spiral_navigator.py", line 80, in take_step
    if self._step_walker.step():
  File "/root/PokemonGo-Bot-myprettyusername/pokemongo_bot/step_walker.py", line 63, in step
    self.bot.heartbeat()
  File "/root/PokemonGo-Bot-myprettyusername/pokemongo_bot/__init__.py", line 504, in heartbeat
    self.update_web_location() # updates every tick
  File "/root/PokemonGo-Bot-myprettyusername/pokemongo_bot/__init__.py", line 81, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

### Steps to Reproduce
launch the bot
wait a long amount of time

setting that can help
```
location : "48.893828, 2.390272"
step : 3
walk speed : default (4.16)
```

### Other Information
OS: Debian x86_64
Git Commit: 6a9e74c91b9f5234f74c0cb09ec2568f1f37f01f yes i'm on this not-so-old commit because i found it really stable ans i look at the last commit, i don't think they will resolve my issue

**Comment by TheOssi** [comment] 2016-07-27 11:11
Duplicate: https://github.com/PokemonGoF/PokemonGo-Bot/issues/1001
Might be also caused by server issues

**Comment by TheGoldenXY** [comment] 2016-07-27 18:18
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1001

/closed

**Closed by TheGoldenXY** 2016-07-27 18:18 UTC
