### ISSUE TITLE
Bot doesn't use better ball if there is no any others

### ISSUE THREAD

**Issue by Di9** [PokemonGoF/PokemonGo-Bot#2043] opened 2016-07-31 10:42 UTC
### Expected Behavior
If there is no poketballs or greatballs, and high catch chance, bot have to use Ultraball anyway...

### Actual Behavior
Try to use poketball, logs:
[13:33:40]  A Wild Psyduck appeared! [CP 69] [Potential 0.31]
[13:33:40] IV [Stamina/Attack/Defense] = [5/2/7]
[13:33:44] Using Pokeball (chance: 92.71%)... (-1 left!)

### Steps to Reproduce
get zero poketballs and greatball and try to catch pokemon with high chance..

### Other Information
OS: Mac OS 
Git Commit: bdaddec9ee64691e5b0a8bda55bf76f83442232f

**Comment by xorinzor** [comment] 2016-08-01 18:14
Duplicate of #2097 and #2075

Please check for existing issues first

**Closed** 2016-08-05 08:32 UTC
