### ISSUE TITLE
GET_GYM_DETAILS TypeError: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#1220] opened 2016-07-27 16:11 UTC
### Actual Behavior
[17:55:30] [x] Need to move closer to Pokestop
Traceback (most recent call last):
  File "pokecli.py", line 283, in <module>
    main()
  File "pokecli.py", line 249, in main
    bot.take_step()
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 46, in take_step
    self.process_cells(work_on_forts=True)
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 66, in process_cells
    "catchable_pokemons": catchable_pokemons}, location, work_on_forts)
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 195, in work_on_cell
    if MoveToFortWorker(forts[0], self).work() == WorkerResult.RUNNING:
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 39, in work
    if not step_walker.step():
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/step_walker.py", line 61, in step
    self.bot.heartbeat()
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 489, in heartbeat
    self.update_web_location() # updates every tick
  File "/Users/DimaPro/PokemonGo-Bot/Bot-1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 102, in update_web_location
    fort['gym_details'] = response_gym_details['responses']['GET_GYM_DETAILS']
TypeError: 'bool' object has no attribute '__getitem__'

### Addition
Seam not to have this issue fixed:
https://github.com/PokemonGoF/PokemonGo-Bot/commit/6a9e74c91b9f5234f74c0cb09ec2568f1f37f01f

It's a server problem but the bot should not crash.

### Other Information
OS: OSx
Git Commit: 3a18aa57dfb67e2e09c207087cad6e5aa1867112

**Comment by TheGoldenXY** [comment] 2016-07-27 17:37
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1218

/closed

**Closed by TheGoldenXY** 2016-07-27 17:37 UTC
Labels: duplicate
