### ISSUE TITLE
ImportError: No module named socketIO_client

### ISSUE THREAD

**Issue by rihago** [PokemonGoF/PokemonGo-Bot#1631] opened 2016-07-29 13:08 UTC
Running the latest dev build (also did clean install)

when trying to start i get the following error:

raceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/Users/harmhartsuiker/Documents/PokemonGo-Bot/pokemongo_bot/__init__.py", line 22, in <module>
    from pokemongo_bot.event_handlers import LoggingHandler
  File "/Users/harmhartsuiker/Documents/PokemonGo-Bot/pokemongo_bot/event_handlers/__init__.py", line 2, in <module>
    from socketio_handler import SocketIoHandler
  File "/Users/harmhartsuiker/Documents/PokemonGo-Bot/pokemongo_bot/event_handlers/socketio_handler.py", line 2, in <module>
    from socketIO_client import SocketIO
ImportError: No module named socketIO_client

**Comment by hlavicka** [comment] 2016-07-29 13:11
run pip install -r requirements.txt

**Comment by Lunik** [comment] 2016-07-29 13:24
Duplicated #1596

**Comment by Henji96** [comment] 2016-07-29 14:57
Same error. When installing requirements.txt i get another error. Error plus the 2 last lines of install:

"    building 'markupsafe._speedups' extension
    error: Den angivne fil blev ikke fundet (Translation: The file was not found)

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\magnus\\appdata\\local\\temp\\pip-build-wzsjf8\\MarkupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\magnus\appdata\local\temp\pip-mfjgws-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\magnus\appdata\local\temp\pip-build-wzsjf8\MarkupSafe\"

**Comment by tauntonian** [comment] 2016-07-29 15:42
I'm having the same issue, and the requirements install also fails for me at MarkupSafe

**Comment by TheGoldenXY** [comment] 2016-07-29 18:31
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1596

/closed

**Closed by TheGoldenXY** 2016-07-29 18:31 UTC

**Comment by tauntonian** [comment] 2016-07-29 19:25
It's not a duplicate if running pip install -r requirements.txt doesn't fix it.

**Comment by Henji96** [comment] 2016-07-29 20:11
FIX: uninstall python 2.7 and install 2.7.10. That fixed it for me. Thank to @dropthemic
