### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Yanush7** [PokemonGoF/PokemonGo-Bot#1632] opened 2016-07-29 13:09 UTC
### Expected Behavior
Opening and running a bot.

### Actual Behavior
Error:

Traceback (most recent call last):
  File "C:\Git\PokemonGo-Bot\pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\Git\PokemonGo-Bot\pokemongo_bot\__init__.py", line 22, in <module>
    from pokemongo_bot.event_handlers import LoggingHandler
  File "C:\Git\PokemonGo-Bot\pokemongo_bot\event_handlers\__init__.py", line 2,
in <module>
    from socketio_handler import SocketIoHandler
  File "C:\Git\PokemonGo-Bot\pokemongo_bot\event_handlers\socketio_handler.py",
line 2, in <module>
    from socketIO_client import SocketIO
ImportError: No module named socketIO_client`

### Steps to Reproduce
Running pokecli.py

### Other Information
OS: Windows 7
Git Commit: dfa4f78f85e391e7bc9c6757478e68f724e108fc

**Comment by hlavicka** [comment] 2016-07-29 13:10
run pip install -r requirements.txt

**Comment by Lunik** [comment] 2016-07-29 13:24
Duplicated #1596

**Comment by Yanush7** [comment] 2016-07-29 13:40
Should i comment this one or the one linked in your comment (but that one is already closed)?

**Comment by tiagodiogo** [comment] 2016-07-29 14:25
OS INFO:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

ERROR:
[15:21:43] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 417, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 113, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 6 column 18 (char 164)

**Comment by Yanush7** [comment] 2016-07-29 14:35
I tried everything (reinstalling requirements etc.) and finally decided to make a clean install. I backed up my config.json, deleted PokemonGo-Bot folder and:
$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot
$ cd PokemonGo-Bot
$ virtualenv .
$ source bin/activate
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update

It is working now.

**Comment by TheGoldenXY** [comment] 2016-07-29 18:31
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1596

/closed

**Closed by TheGoldenXY** 2016-07-29 18:31 UTC
