### ISSUE TITLE
Problem with location and move

### ISSUE THREAD

**Issue by mohakevin** [PokemonGoF/PokemonGo-Bot#1046] opened 2016-07-26 20:20 UTC
### Expected Behavior
Set location and begin to move

### Actual Behavior
Incorrect location or movement

### Steps to Reproduce
Log information:

[2016-07-26 20:17:59] [x] PokemonGO Bot v1.0
[2016-07-26 20:17:59] [x] Configuration initialized
[2016-07-26 20:17:59] [x] Coordinates found in passed in location, not geocoding.
[2016-07-26 20:17:59]
[2016-07-26 20:17:59] [x] Address found: 41.656144,-0.879090
[2016-07-26 20:17:59] [x] Position in-game set as: (41.656144, -0.87909, 0.0)
[2016-07-26 20:17:59]
...
[2016-07-26 20:18:01] [#] Scanning area for objects (1 / 25)
[2016-07-26 20:18:01] [#] Walking from (**2.03e-322, 0.0**) to (41.656144, -0.87909) for approx. **1113653.00 seconds**
[#] Attempting to evolve all pokemons ...

Some ideas what could be the problem?

Regards and thank you!

**Comment by k3v1n-eu** [comment] 2016-07-26 20:25
I have that problem as well since some minutes.

**Comment by 03t02** [comment] 2016-07-26 20:25
Same problem...since some minutes too. I'm using master branch

**Comment by karasube** [comment] 2016-07-26 20:30
Same one.

config.json
```json
{
    "auth_service": "google",
    "username": "***",
    "password": "***",
    "location": "**coord**, ***coord***",
    "gmapkey": "***",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}
```

python --version 
`Python 2.7.9`

git pull
`Already up-to-date.`
(branch is master)

Linux Ubuntu 16.04

**Comment by killerhis** [comment] 2016-07-26 20:51
I'm having the same problem!

**Comment by Critically** [comment] 2016-07-26 21:06
Same problem, may be Niantic do something...

**Comment by jovobe** [comment] 2016-07-26 21:12
This is a problem caused by an update in the pgoapi from tejado. It can easily be fixed by pinning the pgoapi pip to the "v1.1.0" tag. Change the first line in the requirements.txt in this way:
`-e git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi`
and update your pip with
`pip install -r requirements.txt`

**Comment by palakz** [comment] 2016-07-26 21:26
But then I'm getting this error:

```
python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/area51/Stuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/home/area51/Stuff/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
```
Ubuntu 16.04 LTS

**Comment by leovarmak** [comment] 2016-07-26 21:28
@palakz Update your ProtoBuf to version 3

**Comment by palakz** [comment] 2016-07-26 21:29
@leovarmak How do I update it?

**Comment by leovarmak** [comment] 2016-07-26 21:34
@palakz Which OS ?

**Comment by palakz** [comment] 2016-07-26 21:39
@leovarmak Ubuntu 16.04 LTS

**Comment by Calcyfer** [comment] 2016-07-26 21:40
`pip install --update -r requirements.txt` to update on any OS.

**Comment by chadsaun** [comment] 2016-07-26 21:47
When I run `pip install --update -r requirements.txt` I get 

```
Usage:
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --update
```

**Comment by palakz** [comment] 2016-07-26 21:49
--upgrade not helpful.

```
area51@Alienware:~/Stuff/PokemonGo-Bot$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/area51/Stuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/home/area51/Stuff/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
area51@Alienware:~/Stuff/PokemonGo-Bot$ pip install --update -r requirements.txt 
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --update
area51@Alienware:~/Stuff/PokemonGo-Bot$ pip install --upgrade -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./src/pgoapi clone (to v1.1.0)
Collecting geopy==1.11.0 (from -r requirements.txt (line 2))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 3))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 4))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 6))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 7))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 8))
  Using cached googlemaps-2.4.4-py2-none-any.whl
Collecting colorama==0.3.7 (from -r requirements.txt (line 9))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 10))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pyyaml==3.11 (from -r requirements.txt (line 11))
Collecting haversine==0.4.5 (from -r requirements.txt (line 12))
Collecting polyline==1.3.1 (from -r requirements.txt (line 13))
  Using cached polyline-1.3.1-py2.py3-none-any.whl
Collecting six>=1.9 (from protobuf==3.0.0b4->-r requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.0.0b4->-r requirements.txt (line 3))
  Using cached setuptools-25.1.0-py2.py3-none-any.whl
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 5))
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 6))
Installing collected packages: geopy, six, setuptools, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, pgoapi, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline
  Running setup.py develop for pgoapi
Successfully installed colorama-0.3.7 enum34-1.1.2 future-0.15.2 geopy-1.11.0 googlemaps-2.4.4 gpsoauth-0.3.0 haversine-0.4.5 pgoapi-1.1.0 polyline-1.3.1 protobuf-2.6.1 protobuf-to-dict-0.1.0 pycryptodomex-3.4.2 pyyaml-3.11 requests-2.9.1 s2sphere-0.2.4 setuptools-20.7.0 six-1.10.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
area51@Alienware:~/Stuff/PokemonGo-Bot$ python pokecli.pyTraceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/area51/Stuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/home/area51/Stuff/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
area51@Alienware:~/Stuff/PokemonGo-Bot$ 

```

**Comment by chadsaun** [comment] 2016-07-26 21:50
I think they meant `pip install update -r requirements.txt`

**Comment by Calcyfer** [comment] 2016-07-26 21:52
Sorry, for linux it should be apt-get install python-protobuf .

**Comment by kriswong** [comment] 2016-07-26 21:57
latest version and still occuring

sudo apt-get install python-protobuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-protobuf is already the newest version (2.6.1-1.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by chadsaun** [comment] 2016-07-26 21:59
I ran `brew update && brew install --devel protobuf` on OSX and still get the `Walking from (0.0, 0.0) to [0.0018, 0.0]`

**Comment by palakz** [comment] 2016-07-26 21:59
Same problem as @kriswong. It says python-protobuf is already the newest version (2.6.1-1.3).

**Comment by Calcyfer** [comment] 2016-07-26 22:00
You can manually isntall it from here : https://github.com/google/protobuf/tree/master/python
Installation instructions are below.

**Comment by kriswong** [comment] 2016-07-26 22:51
I'm mobile so I. Cannot quote dude but this is the answer.

This is a problem caused by an update in the pgoapi from tejado. It can easily be fixed by pinning the pgoapi pip to the "v1.1.0" tag. Change the first line in the requirements.txt in this way:
-e git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi
and update your pip with
pip install -r requirements.txt

**Comment by chadsaun** [comment] 2016-07-26 22:59
I re-installed my whole dev environment after that commit came out.  So my requirements.txt already has that in it.  My submodule is pointing to a commit `83463c2b`

**Comment by surfaace** [comment] 2016-07-26 23:52
Commit has been reverted, please repull. #1065

**Closed by surfaace** 2016-07-26 23:52 UTC
