### ISSUE TITLE
[HELP] No module named pgoapi.exceptions - line 38, in <module>

### ISSUE THREAD

**Issue by Kamidh** [PokemonGoF/PokemonGo-Bot#3261] opened 2016-08-09 11:25 UTC
#Hi I have this problem... 

"Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions"

After this : pip install -r requirements.txt, I have this error :
 
**Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ly/ylvd8kvn1_zf4_21ldq1smz00000gn/T/pip-build-V34e5q/protobuf-to-dict/**

Thanks for help, many users with same problem.

### Other Information
OS: OSX Sierra
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: Python 2.7.10

**Comment by licklake** [comment] 2016-08-09 11:35
Got the same problem after the last pull.
What has changed in pokecli.py or the dir structure??

**Comment by Kamidh** [comment] 2016-08-09 11:41
Yes same problem with line 38. Sorry my english is bad

**Comment by licklake** [comment] 2016-08-09 12:21
This is probably caused by  #3241

But thats just a guess

**Comment by cmezh** [comment] 2016-08-09 12:28
No, it works with #3241. Do you run in vitrualenv?
Maybe you should backup your config and make clean git clone.

**Comment by terbolous** [comment] 2016-08-09 12:28
could you paste more of the pip output? 
afaik #3241 hasn't been merged yet, so unless you're testing that specifically it shouldn't cause this

**Comment by licklake** [comment] 2016-08-09 12:35
I will clone it from scratch and try it again.

**Comment by mattyhead** [comment] 2016-08-09 13:32
You need to `source bin/activate` or add it to your launch script.

**Comment by Kamidh** [comment] 2016-08-09 18:25
I try "source bin/activate" but nothing happen, you think problem is here?

**Comment by pckz** [comment] 2016-08-10 21:09
After: 
`virtualenv . && source bin/activate && pip install -r requirements.txt`
you must run 
`./install.sh`
finally will work doing
`./run.sh`

**Comment by Kamidh** [comment] 2016-08-10 21:31
Ok, i try but same things.

```
(PokemonGo-Bot)plexmediaservermacbookpro15:PokemonGo-Bot Baptiste$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Press any button or wait 20 seconds.Mer 10 aoû 2016 23:29:19 CESTPokebot Stopped.
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Press any button or wait 20 seconds.
```

**Comment by malopetrov** [comment] 2016-08-11 14:18
i did manage to bypass this error after pip install -r requirements.txt BUT pip from the bot/scripts folder not from python:
Win10:
> /c/python27/scripts/pip install -r requirements.txt > checks modules, shows its ok > run > import error
> /c/user/[...]/PokemonGo-Bot/Scripts/pip install -r requirements.txt > installs > run > ok

**Closed** 2016-08-16 09:45 UTC
