### ISSUE TITLE
Daily Limits (Poxemon Catches) (Feature Request)

### ISSUE THREAD

**Issue by BreezeLo** [PokemonGoF/PokemonGo-Bot#3939] opened 2016-08-14 16:35 UTC
Seems quite a few people have been banned with their poxemon catch being at a count of exactly "1000" (from what I've gathered these individuals were using the snipe feature).

In either case, it's the first capped value we've come across, I propose feature request of caching the amount of poxemon caught in the last 24 hours, and using config variable to control catch limits per 24 hours.

Other things that could be limited daily

- EXP per 24 hours (or user defined)
- km walked per 24 hours (or user defined)

**Comment by MasterCATZ** [comment] 2016-08-14 16:38
Level: 21
Total Exp: 329100
Exp to Lvl 22: 69100 / 75000
Pokemon Encountered: 1352
Pokeballs Thrown: 1492
Pokemon Caught: 1000
Eggs Hatched: 24
Unique Pokedex Entries: 96
PokeStops Visited: 926
Kilometers Walked: 50.95

**Comment by h3k1ru** [comment] 2016-08-14 16:47
Pokestops are limited to 2000 per day.

Source for reference: https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/

**Comment by BreezeLo** [comment] 2016-08-14 17:13
Can confirm @h3k1ru

**Comment by oleerik** [comment] 2016-08-14 20:36
Hey! I've already requested this on [feathub](http://feathub.com/PokemonGoF/PokemonGo-Bot/+17) and here: #3922

**Comment by k4n30** [comment] 2016-08-14 23:44
Duplicate of #3922

**Closed by k4n30** 2016-08-14 23:44 UTC
Labels: enhancement, new feature
