### ISSUE TITLE
Inventory Error

### ISSUE THREAD

**Issue by userwau** [PokemonGoF/PokemonGo-Bot#1497] opened 2016-07-28 21:48 UTC
### Expected Behavior
Work as Intended

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 357, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Users\Error\Desktop\WAU\PokemonGo-Bot\pokemongo_bot\__init__.py", line 64, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "C:\Users\Error\Desktop\WAU\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_transfer_worker.py", line 18, in work
    pokemon_groups = self._release_pokemon_get_groups()
  File "C:\Users\Error\Desktop\WAU\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_transfer_worker.py", line 73, in _release_pokemon_get_groups
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']

## Notes
FYI I have 0 Pokeballs in inventory

**Comment by inet-pwnZ** [comment] 2016-07-28 21:50
i think this problem is caused by heavy server load from either google or ptc

**Comment by DavidTai1** [comment] 2016-07-28 21:51
Server problem. The weird part is game on my phone is not lagging at all.

**Comment by userwau** [comment] 2016-07-28 21:58
Its fixed on my end

**Comment by Lunik** [comment] 2016-07-28 22:00
Duplicate #1491

**Comment by tweekah** [comment] 2016-07-28 22:01
Check pokemon server status unstable as f#ck...

**Comment by TheGoldenXY** [comment] 2016-07-28 22:06
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1491

Closing this.

/closed

**Closed by TheGoldenXY** 2016-07-28 22:06 UTC
Labels: duplicate
