### ISSUE TITLE
DEV evolve_all: "Pidgey,Weedle,Rattata" option not working

### ISSUE THREAD

**Issue by Bramzor** [PokemonGoF/PokemonGo-Bot#1525] opened 2016-07-29 01:18 UTC
### Expected Behavior

"evolve_all": "Pidgey,Weedle,Rattata",  Should evolve those 3 types of pokemon

### Actual Behavior

Doing nothing :-( 

### Steps to Reproduce

Latest DEV clone

### Other Information
OS: Mac OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
git log -n 1 --pretty=format:"%H"
ee9e32cd6c413a1e04b1286a1df37e4f27d9b871

**Comment by vicch** [comment] 2016-07-29 01:38
Duplicate #1456

**Comment by TheGoldenXY** [comment] 2016-07-29 18:30
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1456

/closed

**Closed by TheGoldenXY** 2016-07-29 18:30 UTC
