### ISSUE TITLE
[SUGGESTION] Lure Farm Mode

### ISSUE THREAD

**Issue by LostDGod** [PokemonGoF/PokemonGo-Bot#996] opened 2016-07-26 13:54 UTC
#Lure Farm Mode
(Currently this bot is no match at all to human speed when it comes to XP farm (with lures). There are certain areas that have multiple pokestops with lures right next to each other basically 24/7 so this mode would come in handy.)

**How would it work?**
The bot would place the player in specific coords with random very small position changes every few minutes while always staying within a 5m radius from the original position.
Upon capture/release, sets a random timer within 15-20sec and won't battle wild pokes until the timer is off. - this is obviously to mimic human behavior.
Scans for within-range pokes every 3-5sec when not in battle.
Gives priority to certain pokemons.
Spins within-range pokestops every 5min.
The coords, radius distance, random timer and priority list should be configurable in config.json

I'm not a dev, so this might be a naive view but the way I see it, it wouldn't be hard to implement this mode since most of the work is already done. **The main problem is that currently the bot does not detect pokes spawned from lures.** But there must be a way to do that. Finding it would also highly improve the efficiency of the 'all' and 'poke' modes. 
So please, someone work on this!

**Comment by TCB13** [comment] 2016-07-26 13:58
Possible duplicate: This is already being discussed at #881 and #485.

**Comment by LostDGod** [comment] 2016-07-26 14:01
I've already read those. Not a duplicate since I'm not simply suggesting a detection of pokemons spawned by lures. I'm suggesting a complete new mode.

**Comment by ironbishop** [comment] 2016-07-26 14:02
so, a duplicate of #334 ?

**Comment by LostDGod** [comment] 2016-07-26 14:03
AHA yes!

**Comment by surfaace** [comment] 2016-07-26 23:59
duplicate

**Closed by surfaace** 2016-07-26 23:59 UTC
Labels: duplicate
